/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Claude.
-/
module

public import Mathlib

/-!
# Multi-scale sparse domination: the advertised statement

This module states Theorem 1.1 of

D. Beltran, J. Roos, A. Seeger, *Multi-scale sparse domination*,
Mem. Amer. Math. Soc. 298 (2024), no. 1491, https://doi.org/10.1090/memo/1491,
arXiv:2009.00227v3, https://arxiv.org/abs/2009.00227v3.

It contains only the definitions occurring in the statement, copied verbatim (up to
documentation) from `LeanSparse/Auto/Sec1Introduction.lean`, and the theorem `Auto.mainthm`,
proved in `LeanSparse/Auto/Sec4ProofOfMainResult.lean`.

## Conventions and differences from the paper

* $\mathbb R^d$ is `EuclideanSpace ℝ (Fin d)` with Lebesgue measure, and $d \ge 1$ is assumed.
* The scalar field is an arbitrary `RCLike` field ($\mathbb R$ or $\mathbb C$), $B_1$ and
  $B_2$ are Banach spaces over it, and $B_2^*$ is the continuous dual `StrongDual 𝕜 B₂`.
* Test functions are Borel (rather than Lebesgue) measurable simple functions with compact
  support, and the sets $E_Q$ in the definition of sparseness are Borel measurable.
* The weak and Lorentz quasinorms are normalized as in Grafakos rather than via $f^{**}$; this
  changes $A(p)$ and $A(q)$ only by factors depending on $p$ and $q$.
* The adjoint regularity hypothesis is stated in dual (bilinear) form, which is implied by the
  hypothesis of the paper and is what the proof uses.
* The maximal sparse form is the supremum over $\gamma$-sparse families contained in any dyadic
  lattice; the constant $K$ depends only on $d, p, q, \varepsilon, \gamma$.
-/

@[expose] public section

open MeasureTheory Set
open scoped ENNReal NNReal

namespace Auto

/-- Euclidean space $\mathbb R^d$. -/
abbrev Rd (d : ℕ) := EuclideanSpace ℝ (Fin d)

/-! ### Cubes and dyadic lattices -/

/-- A half-open axis-parallel cube $\prod_i [a_i, a_i + \ell)$ in $\mathbb R^d$, with corner $a$
and side length $\ell > 0$. -/
structure Cube (d : ℕ) where
  /-- the lower corner $a$ -/
  corner : Fin d → ℝ
  /-- the side length $\ell$ -/
  side : ℝ
  side_pos : 0 < side

namespace Cube

variable {d : ℕ}

/-- The point set $\prod_i [a_i, a_i + \ell)$ of a cube. -/
def toSet (Q : Cube d) : Set (Rd d) := {x | ∀ i, Q.corner i ≤ x i ∧ x i < Q.corner i + Q.side}

instance : CoeOut (Cube d) (Set (Rd d)) := ⟨toSet⟩

/-- The triple cube $3Q$: the cube with the same center and three times the side length. -/
def triple (Q : Cube d) : Cube d :=
  ⟨fun i => Q.corner i - Q.side, 3 * Q.side, by have := Q.side_pos; positivity⟩

/-- $R \in \mathcal D_l(Q)$: $R$ is one of the $2^{ld}$ subcubes of $Q$ of side length
$2^{-l}\ell(Q)$. -/
def IsDyadicSubcubeAt (Q R : Cube d) (l : ℕ) : Prop :=
  R.side = Q.side / 2 ^ l ∧
    ∃ v : Fin d → ℕ, (∀ i, v i < 2 ^ l) ∧ ∀ i, R.corner i = Q.corner i + v i * R.side

/-- $R \in \mathcal D(Q) = \bigcup_{l \ge 0} \mathcal D_l(Q)$: $R$ is a dyadic subcube of $Q$
(equivalently, $Q$ is an ancestor of $R$). -/
def IsDyadicSubcube (Q R : Cube d) : Prop := ∃ l : ℕ, IsDyadicSubcubeAt Q R l

end Cube

/-- A *dyadic lattice* in the sense of Lerner and Nazarov (Section 1 of the paper): a collection
$\mathcal D$ of cubes such that (i) every child (dyadic subcube of half the side length) of a cube
of $\mathcal D$ is in $\mathcal D$, (ii) every two cubes of $\mathcal D$ have a common ancestor
in $\mathcal D$, and (iii) every compact set is contained in a cube of $\mathcal D$. -/
structure IsDyadicLattice {d : ℕ} (𝒟 : Set (Cube d)) : Prop where
  child_mem : ∀ Q ∈ 𝒟, ∀ R, Q.IsDyadicSubcubeAt R 1 → R ∈ 𝒟
  common_ancestor : ∀ Q ∈ 𝒟, ∀ Q' ∈ 𝒟, ∃ R ∈ 𝒟, R.IsDyadicSubcube Q ∧ R.IsDyadicSubcube Q'
  exists_superset : ∀ K : Set (Rd d), IsCompact K → ∃ Q ∈ 𝒟, K ⊆ (Q : Set (Rd d))

/-- A collection $\mathfrak S$ of cubes is *$\gamma$-sparse* if there are pairwise disjoint
measurable sets $E_Q \subseteq Q$, $Q \in \mathfrak S$, with $|E_Q| \ge \gamma |Q|$. -/
def IsSparse {d : ℕ} (γ : ℝ) (𝔖 : Set (Cube d)) : Prop :=
  ∃ E : Cube d → Set (Rd d), (∀ Q ∈ 𝔖, MeasurableSet (E Q) ∧ E Q ⊆ (Q : Set (Rd d)) ∧
      ENNReal.ofReal γ * volume (Q : Set (Rd d)) ≤ volume (E Q)) ∧
    𝔖.PairwiseDisjoint E

/-! ### Averages and sparse forms -/

/-- The normalized $L^p$ average over a set $Q$:
$$\langle f \rangle_{Q,p} = \Big( |Q|^{-1} \int_Q |f(x)|_B^p \, dx \Big)^{1/p}.$$ -/
noncomputable def avgNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (f : Rd d → B)
    (Q : Set (Rd d)) (p : ℝ) : ℝ≥0∞ :=
  ((volume Q)⁻¹ * ∫⁻ x in Q, ‖f x‖ₑ ^ p) ^ (1 / p)

/-- The sparse form of a collection $\mathfrak S$ of cubes:
$$\Lambda^{\mathfrak S}_{p_1,p_2}(f_1, f_2) = \sum_{Q \in \mathfrak S} |Q| \,
  \langle f_1 \rangle_{Q,p_1} \langle f_2 \rangle_{Q,p_2}.$$ -/
noncomputable def sparseForm {d : ℕ} {B B' : Type*} [NormedAddCommGroup B]
    [NormedAddCommGroup B'] (𝔖 : Set (Cube d)) (p₁ p₂ : ℝ) (f₁ : Rd d → B) (f₂ : Rd d → B') :
    ℝ≥0∞ :=
  ∑' Q : 𝔖, volume ((Q : Cube d) : Set (Rd d)) * avgNorm f₁ (Q : Cube d) p₁ *
    avgNorm f₂ (Q : Cube d) p₂

/-- The maximal sparse form $\Lambda^*_{\gamma,p_1,p_2}(f_1, f_2)$: the supremum of the sparse
forms $\Lambda^{\mathfrak S}_{p_1,p_2}(f_1, f_2)$ over all $\gamma$-sparse collections
$\mathfrak S$ contained in some dyadic lattice. The supremum is taken over all dyadic lattices
as well (this is the reading under which the argument of Section 4.2 of the paper proves the
theorem). -/
noncomputable def maxSparseForm {d : ℕ} {B B' : Type*} [NormedAddCommGroup B]
    [NormedAddCommGroup B'] (γ p₁ p₂ : ℝ) (f₁ : Rd d → B) (f₂ : Rd d → B') : ℝ≥0∞ :=
  ⨆ (𝒟 : Set (Cube d)) (_ : IsDyadicLattice 𝒟) (𝔖 : Set (Cube d)) (_ : 𝔖 ⊆ 𝒟)
    (_ : IsSparse γ 𝔖), sparseForm 𝔖 p₁ p₂ f₁ f₂

/-! ### Simple functions, operators and the pairing -/

section Operators

variable (d : ℕ) (𝕜 : Type*) [RCLike 𝕜] (B : Type*) [NormedAddCommGroup B] [NormedSpace 𝕜 B]

/-- $\mathcal S_B$: the $B$-valued Borel simple functions on $\mathbb R^d$ with compact
support. -/
def SimpleCpt : Submodule 𝕜 (SimpleFunc (Rd d) B) where
  carrier := {f | HasCompactSupport (f : Rd d → B)}
  zero_mem' := by
    change HasCompactSupport ⇑(0 : SimpleFunc (Rd d) B)
    rw [SimpleFunc.coe_zero]
    exact HasCompactSupport.zero
  add_mem' {f g} hf hg := by
    change HasCompactSupport ⇑(f + g)
    rw [SimpleFunc.coe_add]
    exact HasCompactSupport.add hf hg
  smul_mem' c f hf := by
    change HasCompactSupport ⇑(c • f)
    rw [SimpleFunc.coe_smul]
    exact HasCompactSupport.mono hf (Function.support_const_smul_subset c _)

variable {d 𝕜 B}

instance : CoeFun (SimpleCpt d 𝕜 B) (fun _ => Rd d → B) := ⟨fun f => ⇑(f : SimpleFunc (Rd d) B)⟩

/-- Precomposition of an element of $\mathcal S_B$ with a homeomorphism of $\mathbb R^d$. -/
noncomputable def SimpleCpt.compHomeomorph (φ : Rd d ≃ₜ Rd d) :
    SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B where
  toFun f := ⟨(f : SimpleFunc (Rd d) B).comp φ φ.continuous.measurable,
    by
      change HasCompactSupport (⇑((f : SimpleFunc (Rd d) B).comp φ φ.continuous.measurable))
      rw [SimpleFunc.coe_comp]
      exact f.2.comp_homeomorph φ⟩
  map_add' f g := by ext x; rfl
  map_smul' c f := by ext x; rfl

/-- The dilation $\mathrm{Dil}_{2^j} f(x) = f(2^j x)$ on $\mathcal S_B$. -/
noncomputable def SimpleCpt.dil (j : ℤ) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.compHomeomorph (Homeomorph.smulOfNeZero ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero))

/-- The translate $f(\cdot + h)$ on $\mathcal S_B$. -/
noncomputable def SimpleCpt.transl (h : Rd d) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.compHomeomorph (Homeomorph.addRight h)

/-- The difference operator $\Delta_h f(x) = f(x + h) - f(x)$ on $\mathcal S_B$. -/
noncomputable def SimpleCpt.diff (h : Rd d) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.transl h - LinearMap.id

variable (d 𝕜) (B₁ B₂ : Type*) [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- The operator class: $\Bbbk$-linear operators mapping $\mathcal S_{B_1}$ to $B_2$-valued
functions on $\mathbb R^d$. (Measurability is imposed through the hypotheses of the theorem.) -/
abbrev Op := SimpleCpt d 𝕜 B₁ →ₗ[𝕜] (Rd d → B₂)

variable {d 𝕜 B₁ B₂}

/-- The pairing $\langle F, g \rangle = \int g(x)(F(x)) \, dx$ of a $B_2$-valued function with
a $B_2^*$-valued function. -/
noncomputable def pairing (F : Rd d → B₂) (g : Rd d → StrongDual 𝕜 B₂) : 𝕜 :=
  ∫ x, g x (F x)

/-- The rescaled operator
$(\mathrm{Dil}_{2^j} T) f = \mathrm{Dil}_{2^j}(T(\mathrm{Dil}_{2^{-j}} f))$, i.e.
$(\mathrm{Dil}_{2^j} T) f(x) = T[f(2^{-j} \cdot)](2^j x)$. -/
noncomputable def dilOp (j : ℤ) (T : Op d 𝕜 B₁ B₂) (f : SimpleCpt d 𝕜 B₁) : Rd d → B₂ :=
  fun x => T (SimpleCpt.dil (-j) f) ((2 : ℝ) ^ j • x)

end Operators

/-! ### Lorentz quasinorms -/

/-- The weak $L^{p,\infty}$ quasinorm
$\|F\|_{p,\infty} = \sup_{t > 0} t \, |\{|F| > t\}|^{1/p}$
(Grafakos, *Classical Fourier Analysis*, Def. 1.1.5). -/
noncomputable def weakNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (F : Rd d → B) (p : ℝ) :
    ℝ≥0∞ :=
  ⨆ t : ℝ≥0, (t : ℝ≥0∞) * volume {x | (t : ℝ) < ‖F x‖} ^ (1 / p)

/-- The Lorentz $L^{q,1}$ quasinorm
$\|F\|_{q,1} = q \int_0^\infty |\{|F| > t\}|^{1/q} \, dt$
(Grafakos, *Classical Fourier Analysis*, Prop. 1.4.9). -/
noncomputable def lorentzOneNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (F : Rd d → B)
    (q : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal q * ∫⁻ t in Ioi (0 : ℝ), volume {x | t < ‖F x‖} ^ (1 / q)

/-! ### The basic assumptions of Theorem 1.1 -/

section Assumptions

variable {d : ℕ} {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁]
  [NormedSpace 𝕜 B₁] [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- The hypotheses of Theorem 1.1 of the paper on a family $(T_j)_{j \in \mathbb Z}$, with
constants $A(p) = $ `Ap`, $A(q) = $ `Aq`, $A_\circ(p,q) = $ `A₀` and $B$, exponents $p, q$ and
regularity exponent $\varepsilon$; $q'$ is the dual exponent of $q$. -/
structure BasicAssumptions (T : ℤ → Op d 𝕜 B₁ B₂) (p q ε Ap Aq A₀ B : ℝ) : Prop where
  /-- $T_j f$ is a.e. strongly measurable -/
  aestronglyMeasurable : ∀ j f, AEStronglyMeasurable (T j f) volume
  /-- support condition: $(\mathrm{Dil}_{2^j} T_j) f$ vanishes a.e. at distance $> 1$ from
  $\mathrm{supp} f$ -/
  support : ∀ j (f : SimpleCpt d 𝕜 B₁), ∀ᵐ x ∂volume,
    1 < Metric.infDist x (Function.support ⇑f) → dilOp j (T j) f x = 0
  /-- uniform weak type $(p,p)$ of the partial sums -/
  weakType : ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ → ∀ f : SimpleCpt d 𝕜 B₁,
    weakNorm (∑ j ∈ Finset.Icc N₁ N₂, T j f) p ≤ ENNReal.ofReal Ap * eLpNorm f (.ofReal p) volume
  /-- uniform restricted strong type $(q,q)$ of the partial sums -/
  restrictedStrongType : ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ → ∀ f : SimpleCpt d 𝕜 B₁,
    eLpNorm (∑ j ∈ Finset.Icc N₁ N₂, T j f) (.ofReal q) volume ≤
      ENNReal.ofReal Aq * lorentzOneNorm f q
  /-- uniform single scale $L^p \to L^q$ bounds of the rescaled pieces -/
  singleScale : ∀ j f, eLpNorm (dilOp j (T j) f) (.ofReal q) volume ≤
    ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume
  /-- regularity: $\|(\mathrm{Dil}_{2^j} T_j) \circ \Delta_h\|_{L^p \to L^q} \le B |h|^\varepsilon$
  for $|h| \le 1$ -/
  regularity : ∀ j f (h : Rd d), ‖h‖ ≤ 1 →
    eLpNorm (dilOp j (T j) (SimpleCpt.diff h f)) (.ofReal q) volume ≤
      ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume
  /-- adjoint regularity, in dual form:
  $|\langle (\mathrm{Dil}_{2^j} T_j) f, \Delta_h g \rangle|
  \le B |h|^\varepsilon \|f\|_p \|g\|_{q'}$ for $|h| \le 1$ -/
  regularityDual : ∀ j f (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) (h : Rd d), ‖h‖ ≤ 1 →
    ENNReal.ofReal ‖pairing (dilOp j (T j) f) (SimpleCpt.diff h g)‖ ≤
      ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume *
        eLpNorm g (.ofReal q.conjExponent) volume

/-- The constant $\mathcal C = A(p) + A(q) + A_\circ(p,q) \log(2 + B / A_\circ(p,q))$. -/
noncomputable def constC (Ap Aq A₀ B : ℝ) : ℝ := Ap + Aq + A₀ * Real.log (2 + B / A₀)

end Assumptions

/-! ### The statement of Theorem 1.1 -/

universe u₁ u₂ u₃ in
/-- The assertion of Theorem 1.1 of the paper for given $d, p, q, \varepsilon, \gamma$: there is
a constant $K > 0$ such that for every scalar field $\Bbbk$ (real or complex), all Banach spaces
$B_1, B_2$ over $\Bbbk$, every family $(T_j)_{j \in \mathbb Z}$ satisfying `BasicAssumptions`
with constants $A(p), A(q), A_\circ(p,q), B \ge 0$, all integers $N_1 \le N_2$ and all
$f_1 \in \mathcal S_{B_1}$, $f_2 \in \mathcal S_{B_2^*}$,
$$\Big| \Big\langle \sum_{j=N_1}^{N_2} T_j f_1, f_2 \Big\rangle \Big| \le
  K \, \mathcal C \, \Lambda^*_{\gamma,p,q'}(f_1, f_2).$$ -/
def MainTheoremStatement (d : ℕ) (p q ε γ : ℝ) : Prop :=
  ∃ K : ℝ, 0 < K ∧
    ∀ (𝕜 : Type u₁) [RCLike 𝕜] (B₁ : Type u₂) [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
      [CompleteSpace B₁] (B₂ : Type u₃) [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]
      [CompleteSpace B₂] (T : ℤ → Op d 𝕜 B₁ B₂) (Ap Aq A₀ B : ℝ),
      0 ≤ Ap → 0 ≤ Aq → 0 ≤ A₀ → 0 ≤ B → BasicAssumptions T p q ε Ap Aq A₀ B →
      ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ →
      ∀ (f₁ : SimpleCpt d 𝕜 B₁) (f₂ : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)),
        ENNReal.ofReal ‖pairing (∑ j ∈ Finset.Icc N₁ N₂, T j f₁) f₂‖ ≤
          ENNReal.ofReal (K * constC Ap Aq A₀ B) * maxSparseForm γ p q.conjExponent f₁ f₂

/-- **Theorem 1.1** (multi-scale sparse domination). Let $d \ge 1$, $1 < p \le q$,
$\varepsilon > 0$ and $0 < \gamma < 1$. Then `MainTheoremStatement d p q ε γ` holds. -/
theorem mainthm {d : ℕ} (hd : 0 < d) {p q ε γ : ℝ} (hp : 1 < p) (hpq : p ≤ q) (hε : 0 < ε)
    (hγ0 : 0 < γ) (hγ1 : γ < 1) : MainTheoremStatement d p q ε γ := by
  sorry

end Auto
