/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import LeanSparse.Auto.HardyLittlewoodMaximal
public import LeanSparse.Auto.WhitneyDecomposition

/-!
# LeanSparse

This file was automatically generated by Claude.

Top-level import file of the formalization of Beltran–Roos–Seeger,
*Multi-scale sparse domination* (arXiv:2009.00227).
-/
