/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Claude.
-/
module

public import LeanSparse.Auto.Sec4ProofOfMainResult

/-!
# Multi-scale sparse domination: Palomar solution surface

This is the Palomar solution surface. It only imports the formalization; the compared theorem
`Auto.mainthm` (Theorem 1.1 of Beltran, Roos, Seeger, *Multi-scale sparse domination*) is proved
in the module `LeanSparse.Auto.Sec4ProofOfMainResult`
(file `LeanSparse/Auto/Sec4ProofOfMainResult.lean`), and its statement is defined in
`LeanSparse/Auto/Sec1Introduction.lean`.
-/
