/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# The Hardy–Littlewood maximal theorem (weak type (1,1))

This file was automatically generated by Claude.

Let `E` be a finite-dimensional real normed space with an additive Haar measure `μ`
(for instance `ℝ^d` with Lebesgue measure). For a nonnegative function `f` the
*uncentered Hardy–Littlewood maximal function* is
`𝓜f(x) = sup { μ(B)⁻¹ ∫_B f dμ : B an open ball containing x }`.

The **Hardy–Littlewood maximal theorem** in its weak type `(1,1)` form states that
`λ · μ {x : 𝓜f(x) > λ} ≤ C ∫ f dμ` for all `λ`, with a constant `C` depending only on the
dimension. We prove it with `C = 4 ^ dim E`, using the Vitali covering lemma (with enlargement
factor `4 > 3`) and inner regularity of `μ`. We also record that the superlevel sets of `𝓜f` are
open, which is used for Whitney decompositions.

## Main results

* `Auto.hlMaximal`: the uncentered maximal function over open balls.
* `Auto.isOpen_setOf_lt_hlMaximal`: the superlevel sets `{𝓜f > λ}` are open.
* `Auto.hlMaximal_weakType_one_one`: `λ · μ {𝓜f > λ} ≤ 4 ^ (finrank ℝ E) · ∫⁻ f dμ`.

## References

* E. M. Stein, *Singular integrals and differentiability properties of functions*,
  Princeton Univ. Press, 1970, Chapter I, §1.1, Theorem 1.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., GTM 249, Springer, 2014,
  Theorem 2.1.6.
-/

@[expose] public section

open MeasureTheory Metric Set Module
open scoped ENNReal

namespace Auto

variable {E : Type*} [NormedAddCommGroup E] [MeasurableSpace E]

/-- The uncentered Hardy–Littlewood maximal function of a nonnegative function `f` with respect to
the measure `μ`: the supremum of the averages `μ(B)⁻¹ ∫_B f dμ` over all open balls `B` containing
`x`. -/
noncomputable def hlMaximal (μ : Measure E) (f : E → ℝ≥0∞) (x : E) : ℝ≥0∞ :=
  ⨆ (c : E) (r : ℝ) (_ : 0 < r) (_ : x ∈ ball c r),
    (μ (ball c r))⁻¹ * ∫⁻ y in ball c r, f y ∂μ

/-- The average of `f` over an open ball containing `x` is at most `𝓜f(x)`. -/
theorem le_hlMaximal (μ : Measure E) (f : E → ℝ≥0∞) {x c : E} {r : ℝ} (hr : 0 < r)
    (hx : x ∈ ball c r) :
    (μ (ball c r))⁻¹ * ∫⁻ y in ball c r, f y ∂μ ≤ hlMaximal μ f x :=
  le_iSup_of_le c <| le_iSup_of_le r <| le_iSup_of_le hr <| le_iSup_of_le hx le_rfl

/-- The superlevel set `{𝓜f > λ}` is the union of the open balls on which the average of `f`
exceeds `λ`. -/
theorem setOf_lt_hlMaximal (μ : Measure E) (f : E → ℝ≥0∞) (t : ℝ≥0∞) :
    {x | t < hlMaximal μ f x} =
      ⋃ (c : E) (r : ℝ) (_ : 0 < r) (_ : t < (μ (ball c r))⁻¹ * ∫⁻ y in ball c r, f y ∂μ),
        ball c r := by
  ext x
  simp only [hlMaximal, mem_ofPred_eq, lt_iSup_iff, mem_iUnion, exists_prop]
  constructor
  · rintro ⟨c, r, hr, hx, ht⟩
    exact ⟨c, r, hr, ht, hx⟩
  · rintro ⟨c, r, hr, ht, hx⟩
    exact ⟨c, r, hr, hx, ht⟩

/-- The superlevel sets of the uncentered maximal function are open. -/
theorem isOpen_setOf_lt_hlMaximal (μ : Measure E) (f : E → ℝ≥0∞) (t : ℝ≥0∞) :
    IsOpen {x | t < hlMaximal μ f x} := by
  rw [setOf_lt_hlMaximal]
  exact isOpen_iUnion fun _ => isOpen_iUnion fun _ => isOpen_iUnion fun _ =>
    isOpen_iUnion fun _ => isOpen_ball

variable [NormedSpace ℝ E] [FiniteDimensional ℝ E] [BorelSpace E]

/-- The weak type `(1,1)` estimate on a compact subset of a superlevel set, obtained from a finite
subcover and the Vitali covering lemma. -/
theorem hlMaximal_weakType_compact (μ : Measure E) [μ.IsAddHaarMeasure] (f : E → ℝ≥0∞)
    (t : ℝ≥0∞) {K : Set E} (hK : IsCompact K) (hKU : K ⊆ {x | t < hlMaximal μ f x}) :
    t * μ K ≤ 4 ^ finrank ℝ E * ∫⁻ x, f x ∂μ := by
  classical
  -- the index type of admissible balls
  let ι := {p : E × ℝ // 0 < p.2 ∧ t < (μ (ball p.1 p.2))⁻¹ * ∫⁻ y in ball p.1 p.2, f y ∂μ}
  have hcover : K ⊆ ⋃ i : ι, ball i.1.1 i.1.2 := by
    intro x hx
    have := hKU hx
    rw [setOf_lt_hlMaximal] at this
    simp only [mem_iUnion, exists_prop] at this
    obtain ⟨c, r, hr, ht, hxb⟩ := this
    exact mem_iUnion.2 ⟨⟨(c, r), hr, ht⟩, hxb⟩
  obtain ⟨s, hs⟩ := hK.elim_finite_subcover (fun i : ι => ball i.1.1 i.1.2)
    (fun _ => isOpen_ball) hcover
  -- Vitali selection with enlargement factor 4
  obtain ⟨u, hut, hudisj, hucov⟩ := Vitali.exists_disjoint_subfamily_covering_enlargement_ball
    (s : Set ι) (fun i => i.1.1) (fun i => i.1.2) (∑ i ∈ s, i.1.2)
    (fun a ha => Finset.single_le_sum (f := fun i : ι => i.1.2)
      (fun i _ => i.2.1.le) (Finset.mem_coe.1 ha)) 4 (by norm_num)
  have hufin : u.Finite := (s.finite_toSet).subset hut
  set v := hufin.toFinset with hv
  have hKv : K ⊆ ⋃ b ∈ v, ball b.1.1 (4 * b.1.2) := by
    intro x hx
    obtain ⟨a, has, hxa⟩ := mem_iUnion₂.1 (hs hx)
    obtain ⟨b, hbu, hab⟩ := hucov a (Finset.mem_coe.2 has)
    exact mem_iUnion₂.2 ⟨b, hufin.mem_toFinset.2 hbu, hab hxa⟩
  -- each selected ball satisfies `t μ(B) ≤ ∫_B f`
  have hball : ∀ b : ι, t * μ (ball b.1.1 b.1.2) ≤ ∫⁻ y in ball b.1.1 b.1.2, f y ∂μ := by
    intro b
    have h0 : μ (ball b.1.1 b.1.2) ≠ 0 := (measure_ball_pos μ _ b.2.1).ne'
    have htop : μ (ball b.1.1 b.1.2) ≠ ∞ := measure_ball_lt_top.ne
    calc t * μ (ball b.1.1 b.1.2)
        ≤ ((μ (ball b.1.1 b.1.2))⁻¹ * ∫⁻ y in ball b.1.1 b.1.2, f y ∂μ) *
            μ (ball b.1.1 b.1.2) := by gcongr; exact b.2.2.le
      _ = ∫⁻ y in ball b.1.1 b.1.2, f y ∂μ := by
          rw [mul_comm, ← mul_assoc, ENNReal.mul_inv_cancel h0 htop, one_mul]
  have hscale : ∀ b : ι, μ (ball b.1.1 (4 * b.1.2)) =
      4 ^ finrank ℝ E * μ (ball b.1.1 b.1.2) := by
    intro b
    rw [Measure.addHaar_ball_mul_of_pos μ _ (by norm_num : (0 : ℝ) < 4),
      Measure.addHaar_ball_center μ b.1.1]
    congr 1
    rw [ENNReal.ofReal_pow (by norm_num)]
    norm_num
  have hdisj : (v : Set ι).PairwiseDisjoint fun b => ball b.1.1 b.1.2 := by
    rw [hv, Set.Finite.coe_toFinset]
    exact hudisj
  calc t * μ K ≤ t * ∑ b ∈ v, μ (ball b.1.1 (4 * b.1.2)) :=
        mul_le_mul_right ((measure_mono hKv).trans (measure_biUnion_finset_le _ _)) _
    _ = 4 ^ finrank ℝ E * ∑ b ∈ v, t * μ (ball b.1.1 b.1.2) := by
        simp_rw [hscale, Finset.mul_sum]
        refine Finset.sum_congr rfl fun b _ => ?_
        ring
    _ ≤ 4 ^ finrank ℝ E * ∑ b ∈ v, ∫⁻ y in ball b.1.1 b.1.2, f y ∂μ := by
        gcongr with b
        exact hball b
    _ = 4 ^ finrank ℝ E * ∫⁻ y in ⋃ b ∈ v, ball b.1.1 b.1.2, f y ∂μ := by
        rw [lintegral_biUnion_finset hdisj (fun _ _ => measurableSet_ball)]
    _ ≤ 4 ^ finrank ℝ E * ∫⁻ x, f x ∂μ :=
        mul_le_mul_right (setLIntegral_le_lintegral _ _) _

/-- **Hardy–Littlewood maximal theorem**, weak type `(1,1)` form: for every nonnegative `f` and
every level `t`, `t · μ {x : 𝓜f(x) > t} ≤ 4 ^ (dim E) · ∫ f dμ`. -/
theorem hlMaximal_weakType_one_one (μ : Measure E) [μ.IsAddHaarMeasure] (f : E → ℝ≥0∞)
    (t : ℝ≥0∞) :
    t * μ {x | t < hlMaximal μ f x} ≤ 4 ^ finrank ℝ E * ∫⁻ x, f x ∂μ := by
  rw [(isOpen_setOf_lt_hlMaximal μ f t).measure_eq_iSup_isCompact μ, ENNReal.mul_iSup]
  refine iSup_le fun K => ?_
  rw [ENNReal.mul_iSup]
  refine iSup_le fun hKU => ?_
  rw [ENNReal.mul_iSup]
  exact iSup_le fun hK => hlMaximal_weakType_compact μ f t hK hKU

end Auto
