/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Multi-scale sparse domination, §1: setup

This file was automatically generated by Claude.

Definitions from §1 of D. Beltran, J. Roos, A. Seeger, *Multi-scale sparse domination*,
Mem. Amer. Math. Soc. (2024), arXiv:2009.00227 (TeX lines 409–533):

* half-open cubes in `ℝ^d`, their dyadic subcubes `𝒟_l(Q)`, triple cubes `3Q`,
  and dyadic lattices in the sense of Lerner–Nazarov (axioms (i)–(iii));
* `γ`-sparse collections, the averages `⟨f⟩_{Q,p,B}`, sparse forms `Λ^𝔖_{p₁,p₂}` (sparseform)
  and the maximal sparse form `Λ*_{γ,p₁,p₂}` (eqn:maxform);
* compactly supported simple functions `𝒮_B`, the operator class, the pairing `⟨Tf₁, f₂⟩`;
* weak `L^{p,∞}` and Lorentz `L^{q,1}` quasinorms;
* dilations `Dil_t`, differences `Δ_h` (defDeltah), the basic assumptions
  (support-assu)–(p-q-rescaled-reg-b) of Theorem 1.1 and the constant `𝒞` (eqn:cCdef).

Conventions (see `automation/ErrorReport.md`): `ℝ^d` is `EuclideanSpace ℝ (Fin d)`, scalars are
an arbitrary `RCLike 𝕜`, `B₂*` is `StrongDual 𝕜 B₂`; `Λ*_γ` is the supremum over `γ`-sparse
families in all dyadic lattices (E1); Lorentz quasinorms follow Grafakos (E2); the adjoint
regularity hypothesis is stated in dual form (E3).
-/

@[expose] public section

open MeasureTheory Set
open scoped ENNReal NNReal

namespace Auto

/-- Euclidean space `ℝ^d`. -/
abbrev Rd (d : ℕ) := EuclideanSpace ℝ (Fin d)

/-! ### Cubes and dyadic lattices -/

/-- A half-open axis-parallel cube `∏ᵢ [aᵢ, aᵢ + ℓ)` in `ℝ^d`, with corner `a` and side length
`ℓ > 0`. -/
structure Cube (d : ℕ) where
  /-- the lower corner `a` -/
  corner : Fin d → ℝ
  /-- the side length `ℓ` -/
  side : ℝ
  side_pos : 0 < side

namespace Cube

variable {d : ℕ}

/-- The point set `∏ᵢ [aᵢ, aᵢ + ℓ)` of a cube. -/
def toSet (Q : Cube d) : Set (Rd d) := {x | ∀ i, Q.corner i ≤ x i ∧ x i < Q.corner i + Q.side}

instance : CoeOut (Cube d) (Set (Rd d)) := ⟨toSet⟩

/-- The triple cube `3Q`: the cube with the same center and three times the side length. -/
def triple (Q : Cube d) : Cube d :=
  ⟨fun i => Q.corner i - Q.side, 3 * Q.side, by have := Q.side_pos; positivity⟩

/-- `R ∈ 𝒟_l(Q)`: `R` is one of the `2^{ld}` subcubes of `Q` of side length `2^{-l}ℓ(Q)`. -/
def IsDyadicSubcubeAt (Q R : Cube d) (l : ℕ) : Prop :=
  R.side = Q.side / 2 ^ l ∧
    ∃ v : Fin d → ℕ, (∀ i, v i < 2 ^ l) ∧ ∀ i, R.corner i = Q.corner i + v i * R.side

/-- `R ∈ 𝒟(Q) = ⋃_{l ≥ 0} 𝒟_l(Q)`: `R` is a dyadic subcube of `Q` (equivalently, `Q` is an
ancestor of `R`). -/
def IsDyadicSubcube (Q R : Cube d) : Prop := ∃ l : ℕ, IsDyadicSubcubeAt Q R l

end Cube

/-- A *dyadic lattice* in the sense of Lerner–Nazarov (BRS §1, TeX l.428–432): a collection `𝒟`
of cubes such that (i) every child of a cube of `𝒟` is in `𝒟`, (ii) every two cubes of `𝒟`
have a common ancestor in `𝒟`, and (iii) every compact set is contained in a cube of `𝒟`. -/
structure IsDyadicLattice {d : ℕ} (𝒟 : Set (Cube d)) : Prop where
  child_mem : ∀ Q ∈ 𝒟, ∀ R, Q.IsDyadicSubcubeAt R 1 → R ∈ 𝒟
  common_ancestor : ∀ Q ∈ 𝒟, ∀ Q' ∈ 𝒟, ∃ R ∈ 𝒟, R.IsDyadicSubcube Q ∧ R.IsDyadicSubcube Q'
  exists_superset : ∀ K : Set (Rd d), IsCompact K → ∃ Q ∈ 𝒟, K ⊆ (Q : Set (Rd d))

/-- A collection `𝔖` of cubes is *`γ`-sparse* (BRS §1, Definition) if there are pairwise
disjoint measurable sets `E_Q ⊆ Q`, `Q ∈ 𝔖`, with `|E_Q| ≥ γ |Q|`. -/
def IsSparse {d : ℕ} (γ : ℝ) (𝔖 : Set (Cube d)) : Prop :=
  ∃ E : Cube d → Set (Rd d), (∀ Q ∈ 𝔖, MeasurableSet (E Q) ∧ E Q ⊆ (Q : Set (Rd d)) ∧
      ENNReal.ofReal γ * volume (Q : Set (Rd d)) ≤ volume (E Q)) ∧
    𝔖.PairwiseDisjoint E

/-! ### Averages and sparse forms -/

/-- The normalized `L^p` average `⟨f⟩_{Q,p,B} = (|Q|⁻¹ ∫_Q |f|_B^p)^{1/p}` over a set `Q`. -/
noncomputable def avgNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (f : Rd d → B)
    (Q : Set (Rd d)) (p : ℝ) : ℝ≥0∞ :=
  ((volume Q)⁻¹ * ∫⁻ x in Q, ‖f x‖ₑ ^ p) ^ (1 / p)

/-- The sparse form `Λ^𝔖_{p₁,p₂}(f₁, f₂) = ∑_{Q ∈ 𝔖} |Q| ⟨f₁⟩_{Q,p₁} ⟨f₂⟩_{Q,p₂}`
(BRS eq. (sparseform)). -/
noncomputable def sparseForm {d : ℕ} {B B' : Type*} [NormedAddCommGroup B]
    [NormedAddCommGroup B'] (𝔖 : Set (Cube d)) (p₁ p₂ : ℝ) (f₁ : Rd d → B) (f₂ : Rd d → B') :
    ℝ≥0∞ :=
  ∑' Q : 𝔖, volume ((Q : Cube d) : Set (Rd d)) * avgNorm f₁ (Q : Cube d) p₁ *
    avgNorm f₂ (Q : Cube d) p₂

/-- The maximal sparse form `Λ*_{γ,p₁,p₂}(f₁, f₂)`: the supremum of the sparse forms over all
`γ`-sparse collections of cubes contained in a dyadic lattice (BRS eq. (eqn:maxform); see
ErrorReport E1 for the quantification over lattices). -/
noncomputable def maxSparseForm {d : ℕ} {B B' : Type*} [NormedAddCommGroup B]
    [NormedAddCommGroup B'] (γ p₁ p₂ : ℝ) (f₁ : Rd d → B) (f₂ : Rd d → B') : ℝ≥0∞ :=
  ⨆ (𝒟 : Set (Cube d)) (_ : IsDyadicLattice 𝒟) (𝔖 : Set (Cube d)) (_ : 𝔖 ⊆ 𝒟)
    (_ : IsSparse γ 𝔖), sparseForm 𝔖 p₁ p₂ f₁ f₂

/-! ### Simple functions, operators and the pairing -/

section Operators

variable (d : ℕ) (𝕜 : Type*) [RCLike 𝕜] (B : Type*) [NormedAddCommGroup B] [NormedSpace 𝕜 B]

/-- `𝒮_B`: the `B`-valued simple functions on `ℝ^d` with compact support (BRS §1, TeX l.409). -/
def SimpleCpt : Submodule 𝕜 (SimpleFunc (Rd d) B) where
  carrier := {f | HasCompactSupport (f : Rd d → B)}
  zero_mem' := by simp [HasCompactSupport.zero]
  add_mem' {f g} hf hg := by
    simp only [mem_ofPred_eq, SimpleFunc.coe_add] at hf hg ⊢
    exact hf.add hg
  smul_mem' c f hf := by
    simp only [mem_ofPred_eq, SimpleFunc.coe_smul] at hf ⊢
    exact hf.mono (Function.support_const_smul_subset c _)

variable {d 𝕜 B}

instance : CoeFun (SimpleCpt d 𝕜 B) (fun _ => Rd d → B) := ⟨fun f => ⇑(f : SimpleFunc (Rd d) B)⟩

/-- Precomposition of an element of `𝒮_B` with a homeomorphism of `ℝ^d` that is measurable. -/
noncomputable def SimpleCpt.compHomeomorph (φ : Rd d ≃ₜ Rd d) :
    SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B where
  toFun f := ⟨(f : SimpleFunc (Rd d) B).comp φ φ.continuous.measurable,
    by
      change HasCompactSupport (⇑((f : SimpleFunc (Rd d) B).comp φ φ.continuous.measurable))
      rw [SimpleFunc.coe_comp]
      exact f.2.comp_homeomorph φ⟩
  map_add' f g := by ext x; rfl
  map_smul' c f := by ext x; rfl

/-- The dilation `Dil_{2^j} f(x) = f(2^j x)` on `𝒮_B`. -/
noncomputable def SimpleCpt.dil (j : ℤ) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.compHomeomorph (Homeomorph.smulOfNeZero ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero))

/-- The translate `f(· + h)` on `𝒮_B`. -/
noncomputable def SimpleCpt.transl (h : Rd d) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.compHomeomorph (Homeomorph.addRight h)

/-- The difference operator `Δ_h f(x) = f(x + h) - f(x)` (BRS eq. (defDeltah)) on `𝒮_B`. -/
noncomputable def SimpleCpt.diff (h : Rd d) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B :=
  SimpleCpt.transl h - LinearMap.id

variable (d 𝕜) (B₁ B₂ : Type*) [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- The operator class: `𝕜`-linear operators mapping `𝒮_{B₁}` to `B₂`-valued functions on `ℝ^d`.
(Measurability and integrability are imposed through the hypotheses of Theorem 1.1.) -/
abbrev Op := SimpleCpt d 𝕜 B₁ →ₗ[𝕜] (Rd d → B₂)

variable {d 𝕜 B₁ B₂}

/-- The pairing `⟨F, g⟩ = ∫ ⟨F(x), g(x)⟩ dx` of a `B₂`-valued function with a
`B₂*`-valued function. -/
noncomputable def pairing (F : Rd d → B₂) (g : Rd d → StrongDual 𝕜 B₂) : 𝕜 :=
  ∫ x, g x (F x)

/-- The dilated operator `(Dil_{2^j} T) f = Dil_{2^j} (T (Dil_{2^{-j}} f))`, i.e.
`(Dil_{2^j} T) f (x) = T[f(2^{-j} ·)](2^j x)` (BRS §1.1, TeX l.497). -/
noncomputable def dilOp (j : ℤ) (T : Op d 𝕜 B₁ B₂) (f : SimpleCpt d 𝕜 B₁) : Rd d → B₂ :=
  fun x => T (SimpleCpt.dil (-j) f) ((2 : ℝ) ^ j • x)

end Operators

/-! ### Lorentz quasinorms -/

/-- The weak `L^{p,∞}` quasinorm `‖F‖_{p,∞} = sup_{t > 0} t |{|F| > t}|^{1/p}`
(Grafakos, *Classical Fourier Analysis*, Def. 1.1.5). -/
noncomputable def weakNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (F : Rd d → B) (p : ℝ) :
    ℝ≥0∞ :=
  ⨆ t : ℝ≥0, (t : ℝ≥0∞) * volume {x | (t : ℝ) < ‖F x‖} ^ (1 / p)

/-- The Lorentz `L^{q,1}` quasinorm `‖F‖_{q,1} = q ∫_0^∞ |{|F| > t}|^{1/q} dt`
(Grafakos, *Classical Fourier Analysis*, Prop. 1.4.9). -/
noncomputable def lorentzOneNorm {d : ℕ} {B : Type*} [NormedAddCommGroup B] (F : Rd d → B)
    (q : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal q * ∫⁻ t in Ioi (0 : ℝ), volume {x | t < ‖F x‖} ^ (1 / q)

/-! ### The basic assumptions of Theorem 1.1 -/

section Assumptions

variable {d : ℕ} {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁]
  [NormedSpace 𝕜 B₁] [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- The basic assumptions of Theorem 1.1 (BRS §1.1, TeX l.502–533) on a family `(T_j)_{j ∈ ℤ}`
with constants `A(p) = Ap`, `A(q) = Aq`, `A∘(p,q) = A₀` and `B`, for exponents `p, q` and
regularity exponent `ε`; `q'` denotes the dual exponent of `q`. -/
structure BasicAssumptions (T : ℤ → Op d 𝕜 B₁ B₂) (p q ε Ap Aq A₀ B : ℝ) : Prop where
  /-- `T_j f` is strongly measurable (implied by the norm hypotheses, TeX l.531) -/
  aestronglyMeasurable : ∀ j f, AEStronglyMeasurable (T j f) volume
  /-- (support-assu): `supp (Dil_{2^j} T_j) f ⊂ {x : dist(x, supp f) ≤ 1}` -/
  support : ∀ j (f : SimpleCpt d 𝕜 B₁), ∀ᵐ x ∂volume,
    1 < Metric.infDist x (Function.support ⇑f) → dilOp j (T j) f x = 0
  /-- (bdness-wt): uniform weak type `(p,p)` of the partial sums -/
  weakType : ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ → ∀ f : SimpleCpt d 𝕜 B₁,
    weakNorm (∑ j ∈ Finset.Icc N₁ N₂, T j f) p ≤ ENNReal.ofReal Ap * eLpNorm f (.ofReal p) volume
  /-- (bdness-rt): uniform restricted strong type `(q,q)` of the partial sums -/
  restrictedStrongType : ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ → ∀ f : SimpleCpt d 𝕜 B₁,
    eLpNorm (∑ j ∈ Finset.Icc N₁ N₂, T j f) (.ofReal q) volume ≤
      ENNReal.ofReal Aq * lorentzOneNorm f q
  /-- (p-q-rescaled): uniform single scale `L^p → L^q` bounds of the rescaled pieces -/
  singleScale : ∀ j f, eLpNorm (dilOp j (T j) f) (.ofReal q) volume ≤
    ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume
  /-- (p-q-rescaled-reg-a): `‖(Dil_{2^j} T_j) ∘ Δ_h‖_{L^p → L^q} ≤ B |h|^ε` for `|h| ≤ 1` -/
  regularity : ∀ j f (h : Rd d), ‖h‖ ≤ 1 →
    eLpNorm (dilOp j (T j) (SimpleCpt.diff h f)) (.ofReal q) volume ≤
      ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume
  /-- (p-q-rescaled-reg-b), dual form (ErrorReport E3):
  `|⟨(Dil_{2^j} T_j) f, Δ_h g⟩| ≤ B |h|^ε ‖f‖_p ‖g‖_{q'}` for `|h| ≤ 1` -/
  regularityDual : ∀ j f (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) (h : Rd d), ‖h‖ ≤ 1 →
    ENNReal.ofReal ‖pairing (dilOp j (T j) f) (SimpleCpt.diff h g)‖ ≤
      ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume *
        eLpNorm g (.ofReal q.conjExponent) volume

/-- The constant `𝒞 = A(p) + A(q) + A∘(p,q) log(2 + B / A∘(p,q))` (BRS eq. (eqn:cCdef)). -/
noncomputable def constC (Ap Aq A₀ B : ℝ) : ℝ := Ap + Aq + A₀ * Real.log (2 + B / A₀)

end Assumptions

/-! ### The statement of Theorem 1.1 -/

universe u₁ u₂ u₃ in
/-- The assertion of **Theorem 1.1** (BRS, `\label{mainthm}`) for given `d`, `p`, `q`, `ε`, `γ`:
there is a constant `K = K(p,q,ε,γ,d)` such that for every scalar field `𝕜`, all Banach spaces
`B₁`, `B₂` over `𝕜`, every family `(T_j)_{j ∈ ℤ}` of operators satisfying the basic assumptions
with constants `A(p), A(q), A∘(p,q), B ≥ 0`, all integers `N₁ ≤ N₂` and all
`f₁ ∈ 𝒮_{B₁}`, `f₂ ∈ 𝒮_{B₂*}`,
`|⟨∑_{j=N₁}^{N₂} T_j f₁, f₂⟩| ≤ K 𝒞 Λ*_{γ,p,q'}(f₁, f₂)`,
i.e. `‖∑_{j=N₁}^{N₂} T_j‖_{Sp_γ(p,B₁,q',B₂*)} ≤ K 𝒞` (eq. (vectsparsebound)). -/
def MainTheoremStatement (d : ℕ) (p q ε γ : ℝ) : Prop :=
  ∃ K : ℝ, 0 < K ∧
    ∀ (𝕜 : Type u₁) [RCLike 𝕜] (B₁ : Type u₂) [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
      [CompleteSpace B₁] (B₂ : Type u₃) [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]
      [CompleteSpace B₂] (T : ℤ → Op d 𝕜 B₁ B₂) (Ap Aq A₀ B : ℝ),
      0 ≤ Ap → 0 ≤ Aq → 0 ≤ A₀ → 0 ≤ B → BasicAssumptions T p q ε Ap Aq A₀ B →
      ∀ N₁ N₂ : ℤ, N₁ ≤ N₂ →
      ∀ (f₁ : SimpleCpt d 𝕜 B₁) (f₂ : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)),
        ENNReal.ofReal ‖pairing (∑ j ∈ Finset.Icc N₁ N₂, T j f₁) f₂‖ ≤
          ENNReal.ofReal (K * constC Ap Aq A₀ B) * maxSparseForm γ p q.conjExponent f₁ f₂

/-! ### Grid lattices and the prototype dyadic lattice (BRS §1, TeX l.420–427)

A *grid lattice* has, at every level `L ∈ ℤ`, the cubes of side `s 2^L` with corners
`s 2^L (t + o_L)`, `t ∈ ℤ^d`, for offsets `o_L` with `2 o_L - o_{L-1} ∈ ℤ^d` (so that children
of level `L` cubes are level `L - 1` cubes) and with the fractional parts of `-o_L` uniformly
away from `0` and `1` (which gives axiom (iii)). The prototype lattice of the paper is the case
`s = 1`, `o_L = (-1)^L / 3`. -/

namespace Cube

variable {d : ℕ}

@[ext] theorem ext' {Q R : Cube d} (hc : Q.corner = R.corner) (hs : Q.side = R.side) : Q = R := by
  cases Q; cases R; simp_all

theorem corner_mem (Q : Cube d) : WithLp.toLp 2 Q.corner ∈ (Q : Set (Rd d)) := by
  intro i
  have := Q.side_pos
  exact ⟨le_rfl, by simp; linarith⟩

theorem nonempty (Q : Cube d) : (Q : Set (Rd d)).Nonempty := ⟨_, Q.corner_mem⟩

theorem IsDyadicSubcubeAt.subset {Q R : Cube d} {l : ℕ} (h : Q.IsDyadicSubcubeAt R l) :
    (R : Set (Rd d)) ⊆ Q := by
  obtain ⟨hs, v, hv, hc⟩ := h
  intro x hx i
  have h2 : (0 : ℝ) < 2 ^ l := by positivity
  have hRs : R.side * 2 ^ l = Q.side := by rw [hs]; field_simp
  have hvi : (v i : ℝ) + 1 ≤ 2 ^ l := by exact_mod_cast hv i
  have := hx i
  rw [hc i] at this
  have hRpos := R.side_pos
  constructor
  · nlinarith [this.1, (Nat.cast_nonneg (v i) : (0 : ℝ) ≤ v i)]
  · nlinarith [this.2]

theorem IsDyadicSubcubeAt.trans {Q R S : Cube d} {l l' : ℕ} (h : Q.IsDyadicSubcubeAt R l)
    (h' : R.IsDyadicSubcubeAt S l') : Q.IsDyadicSubcubeAt S (l + l') := by
  obtain ⟨hs, v, hv, hc⟩ := h
  obtain ⟨hs', v', hv', hc'⟩ := h'
  have hRS : R.side = S.side * 2 ^ l' := by rw [hs']; field_simp
  refine ⟨by rw [hs', hs, pow_add]; field_simp, fun i => v i * 2 ^ l' + v' i, fun i => ?_,
    fun i => ?_⟩
  · calc v i * 2 ^ l' + v' i < v i * 2 ^ l' + 2 ^ l' := by have := hv' i; omega
      _ = (v i + 1) * 2 ^ l' := by ring
      _ ≤ 2 ^ l * 2 ^ l' := Nat.mul_le_mul_right _ (hv i)
      _ = 2 ^ (l + l') := by rw [pow_add]
  · rw [hc' i, hc i, hRS]
    push_cast
    ring

theorem IsDyadicSubcubeAt.refl (Q : Cube d) : Q.IsDyadicSubcubeAt Q 0 :=
  ⟨by simp, fun _ => 0, fun _ => by simp, fun _ => by simp⟩

theorem IsDyadicSubcube.trans {Q R S : Cube d} (h : Q.IsDyadicSubcube R)
    (h' : R.IsDyadicSubcube S) : Q.IsDyadicSubcube S := by
  obtain ⟨l, hl⟩ := h
  obtain ⟨l', hl'⟩ := h'
  exact ⟨l + l', hl.trans hl'⟩

theorem IsDyadicSubcube.subset {Q R : Cube d} (h : Q.IsDyadicSubcube R) :
    (R : Set (Rd d)) ⊆ Q := by
  obtain ⟨l, hl⟩ := h
  exact hl.subset

end Cube

/-- The data of a grid lattice: a scale `s > 0`, offsets `o_L` with `2 o_L - o_{L-1} ∈ ℤ^d`,
and a margin `η > 0` with `η ≤ fract(-o_L) ≤ 1 - η`. -/
structure GridData (d : ℕ) where
  /-- the scale -/
  s : ℝ
  s_pos : 0 < s
  /-- the offsets -/
  o : ℤ → Fin d → ℝ
  /-- the integer shifts `2 o_L - o_{L-1}` -/
  k : ℤ → Fin d → ℤ
  nest : ∀ L i, 2 * o L i - o (L - 1) i = k L i
  /-- the margin -/
  η : ℝ
  η_pos : 0 < η
  margin : ∀ L i, η ≤ Int.fract (-o L i) ∧ Int.fract (-o L i) ≤ 1 - η

namespace GridData

variable {d : ℕ} (G : GridData d)

/-- The side length `s 2^L` of the level `L` cubes. -/
noncomputable def side (L : ℤ) : ℝ := G.s * (2 : ℝ) ^ L

theorem side_pos (L : ℤ) : 0 < G.side L := mul_pos G.s_pos (zpow_pos (by norm_num) L)

theorem side_sub_one (L : ℤ) : G.side (L - 1) = G.side L / 2 := by
  simp only [side, zpow_sub_one₀ (two_ne_zero' ℝ)]
  ring

/-- The level `L` cube with index `t ∈ ℤ^d`. -/
noncomputable def cube (L : ℤ) (t : Fin d → ℤ) : Cube d :=
  ⟨fun i => G.side L * (t i + G.o L i), G.side L, G.side_pos L⟩

/-- The grid lattice: all cubes of all levels. -/
def lattice : Set (Cube d) := {Q | ∃ L t, Q = G.cube L t}

/-- The index of the level `L` cube containing `x`. -/
noncomputable def idx (L : ℤ) (x : Rd d) : Fin d → ℤ := fun i => ⌊x i / G.side L - G.o L i⌋

theorem mem_cube_iff {L : ℤ} {t : Fin d → ℤ} {x : Rd d} :
    x ∈ (G.cube L t : Set (Rd d)) ↔ t = G.idx L x := by
  have hs := G.side_pos L
  simp only [Cube.toSet, cube, mem_ofPred_eq]
  rw [funext_iff]
  refine forall_congr' fun i => ?_
  rw [eq_comm, idx, Int.floor_eq_iff, le_sub_iff_add_le, sub_lt_iff_lt_add, le_div_iff₀ hs,
    div_lt_iff₀ hs]
  constructor <;> rintro ⟨h1, h2⟩ <;> constructor <;> nlinarith

theorem mem_cube_idx (L : ℤ) (x : Rd d) : x ∈ (G.cube L (G.idx L x) : Set (Rd d)) :=
  G.mem_cube_iff.2 rfl

theorem eq_of_mem_cube {L : ℤ} {t t' : Fin d → ℤ} {x : Rd d}
    (h : x ∈ (G.cube L t : Set (Rd d))) (h' : x ∈ (G.cube L t' : Set (Rd d))) : t = t' :=
  (G.mem_cube_iff.1 h).trans (G.mem_cube_iff.1 h').symm

theorem cube_side (L : ℤ) (t : Fin d → ℤ) : (G.cube L t).side = G.side L := rfl

theorem side_injective : Function.Injective G.side := by
  intro L L' h
  simp only [side] at h
  have := mul_left_cancel₀ G.s_pos.ne' h
  exact zpow_right_injective₀ (by norm_num) (by norm_num) this

theorem cube_injective {L L' : ℤ} {t t' : Fin d → ℤ} (h : G.cube L t = G.cube L' t') :
    L = L' ∧ t = t' := by
  have hL : L = L' := G.side_injective (by rw [← cube_side, h, cube_side])
  subst hL
  refine ⟨rfl, ?_⟩
  exact G.eq_of_mem_cube (h ▸ (G.cube L t).corner_mem) (G.cube L t').corner_mem

/-- The children of the level `L` cube `t` are the level `L - 1` cubes `2t + k_L + v`,
`v ∈ {0,1}^d`. -/
theorem isDyadicSubcubeAt_child (L : ℤ) (t : Fin d → ℤ) (v : Fin d → ℕ) (hv : ∀ i, v i < 2) :
    (G.cube L t).IsDyadicSubcubeAt (G.cube (L - 1) fun i => 2 * t i + G.k L i + v i) 1 := by
  refine ⟨by simp [cube, side_sub_one], v, by simpa using hv, fun i => ?_⟩
  simp only [cube, side_sub_one]
  have := G.nest L i
  push_cast
  rw [← this]
  ring

theorem child_eq {L : ℤ} {t : Fin d → ℤ} {R : Cube d}
    (h : (G.cube L t).IsDyadicSubcubeAt R 1) :
    ∃ t', R = G.cube (L - 1) t' := by
  obtain ⟨hs, v, hv, hc⟩ := h
  refine ⟨fun i => 2 * t i + G.k L i + v i, Cube.ext' ?_ ?_⟩
  · funext i
    rw [hc i, hs]
    simp only [cube, side_sub_one, pow_one]
    have := G.nest L i
    push_cast
    rw [← this]
    ring
  · rw [hs]
    simp [cube, side_sub_one]

/-- The parent index of a level `L - 1` cube. -/
def parent (L : ℤ) (t : Fin d → ℤ) : Fin d → ℤ := fun i => (t i - G.k L i) / 2

theorem isDyadicSubcubeAt_parent (L : ℤ) (t : Fin d → ℤ) :
    (G.cube L (G.parent L t)).IsDyadicSubcubeAt (G.cube (L - 1) t) 1 := by
  have h := G.isDyadicSubcubeAt_child L (G.parent L t) (fun i => ((t i - G.k L i) % 2).toNat)
    (fun i => by have := Int.emod_two_eq_zero_or_one (t i - G.k L i); omega)
  convert h using 2
  funext i
  simp only [parent]
  have h0 := Int.emod_nonneg (t i - G.k L i) (by norm_num : (2 : ℤ) ≠ 0)
  rw [Int.toNat_of_nonneg h0]
  omega

/-- Every level `L` cube has an ancestor at every level `L + l`. -/
theorem exists_ancestor (L : ℤ) (t : Fin d → ℤ) (l : ℕ) :
    ∃ t', (G.cube (L + l) t').IsDyadicSubcubeAt (G.cube L t) l := by
  induction l with
  | zero => exact ⟨t, by simpa using Cube.IsDyadicSubcubeAt.refl _⟩
  | succ l ih =>
    obtain ⟨t', ht'⟩ := ih
    refine ⟨G.parent (L + (l + 1 : ℕ)) t', ?_⟩
    have h := G.isDyadicSubcubeAt_parent (L + (l + 1 : ℕ)) t'
    have hL : L + ((l + 1 : ℕ) : ℤ) - 1 = L + l := by push_cast; ring
    rw [hL] at h
    have := h.trans ht'
    rwa [add_comm 1 l] at this

/-- The ancestor at level `L' ≥ L` of a level `L` cube containing `x` is the level `L'` cube
containing `x`. -/
theorem isDyadicSubcube_of_mem {L L' : ℤ} (hLL' : L ≤ L') {t : Fin d → ℤ} {x : Rd d}
    (hx : x ∈ (G.cube L t : Set (Rd d))) :
    (G.cube L' (G.idx L' x)).IsDyadicSubcubeAt (G.cube L t) (L' - L).toNat := by
  obtain ⟨t', ht'⟩ := G.exists_ancestor L t (L' - L).toNat
  have hL : L + ((L' - L).toNat : ℤ) = L' := by omega
  rw [hL] at ht'
  have := G.eq_of_mem_cube (ht'.subset hx) (G.mem_cube_idx L' x)
  rwa [this] at ht'

/-- Grid cubes are nested or disjoint (laminarity); if they meet, the smaller is a dyadic
subcube of the larger. -/
theorem isDyadicSubcube_of_inter {L L' : ℤ} (hLL' : L ≤ L') {t t' : Fin d → ℤ}
    (hne : ((G.cube L t : Set (Rd d)) ∩ G.cube L' t').Nonempty) :
    (G.cube L' t').IsDyadicSubcube (G.cube L t) := by
  obtain ⟨x, hx, hx'⟩ := hne
  have h := G.isDyadicSubcube_of_mem hLL' hx
  rw [← G.mem_cube_iff.1 hx'] at h
  exact ⟨_, h⟩

/-- The level `L` cube containing `0` contains the open ball of radius `η s 2^L`. -/
theorem ball_subset_cube_zero (L : ℤ) :
    Metric.ball (0 : Rd d) (G.η * G.side L) ⊆ G.cube L (G.idx L 0) := by
  intro x hx i
  have hs := G.side_pos L
  have hxi : |x i| < G.η * G.side L := by
    have := PiLp.norm_apply_le x i
    rw [mem_ball_zero_iff] at hx
    rw [← Real.norm_eq_abs]
    linarith
  obtain ⟨h1, h2⟩ := G.margin L i
  have hfr : (⌊-G.o L i⌋ : ℝ) + Int.fract (-G.o L i) = -G.o L i := Int.floor_add_fract _
  have hc : G.side L * ((⌊-G.o L i⌋ : ℝ) + G.o L i) = -(G.side L * Int.fract (-G.o L i)) := by
    rw [show (⌊-G.o L i⌋ : ℝ) + G.o L i = -Int.fract (-G.o L i) by linarith]
    ring
  have h3 : G.side L * G.η ≤ G.side L * Int.fract (-G.o L i) := mul_le_mul_of_nonneg_left h1 hs.le
  have h4 : G.side L * Int.fract (-G.o L i) ≤ G.side L * (1 - G.η) :=
    mul_le_mul_of_nonneg_left h2 hs.le
  simp only [cube, idx, PiLp.zero_apply, zero_div, zero_sub]
  rw [abs_lt] at hxi
  rw [hc]
  constructor <;> nlinarith

theorem exists_cube_superset_of_isCompact {K : Set (Rd d)} (hK : IsCompact K) :
    ∃ L₀ : ℤ, ∀ L ≥ L₀, K ⊆ G.cube L (G.idx L 0) := by
  obtain ⟨R, hR⟩ := hK.isBounded.subset_closedBall (0 : Rd d)
  obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt (R / (G.η * G.s)) (by norm_num : (1 : ℝ) < 2)
  refine ⟨n, fun L hL => hR.trans ((Metric.closedBall_subset_ball ?_).trans
    (G.ball_subset_cube_zero L))⟩
  have hηs : 0 < G.η * G.s := mul_pos G.η_pos G.s_pos
  have h2 : (2 : ℝ) ^ n ≤ (2 : ℝ) ^ L := by
    rw [← zpow_natCast]
    exact zpow_le_zpow_right₀ (by norm_num) hL
  rw [div_lt_iff₀ hηs] at hn
  simp only [side]
  nlinarith

/-- Grid lattices are dyadic lattices in the sense of Lerner–Nazarov. -/
theorem isDyadicLattice : IsDyadicLattice G.lattice where
  child_mem := by
    rintro _ ⟨L, t, rfl⟩ R hR
    obtain ⟨t', rfl⟩ := G.child_eq hR
    exact ⟨_, _, rfl⟩
  common_ancestor := by
    rintro _ ⟨L, t, rfl⟩ _ ⟨L', t', rfl⟩
    have hK : IsCompact ({WithLp.toLp 2 (G.cube L t).corner} ∪
        {WithLp.toLp 2 (G.cube L' t').corner} : Set (Rd d)) :=
      isCompact_singleton.union isCompact_singleton
    obtain ⟨L₀, hL₀⟩ := G.exists_cube_superset_of_isCompact hK
    set M := max L₀ (max L L')
    have hM := hL₀ M (le_max_left _ _)
    refine ⟨G.cube M (G.idx M 0), ⟨_, _, rfl⟩, ?_, ?_⟩
    · have h1 := G.isDyadicSubcube_of_mem (le_trans (le_max_left L L') (le_max_right L₀ (max L L')))
        (G.cube L t).corner_mem
      rw [← G.mem_cube_iff.1 (hM (Or.inl rfl))] at h1
      exact ⟨_, h1⟩
    · have h1 := G.isDyadicSubcube_of_mem
        (le_trans (le_max_right L L') (le_max_right L₀ (max L L')))
        (G.cube L' t').corner_mem
      rw [← G.mem_cube_iff.1 (hM (Or.inr rfl))] at h1
      exact ⟨_, h1⟩
  exists_superset := by
    intro K hK
    obtain ⟨L₀, hL₀⟩ := G.exists_cube_superset_of_isCompact hK
    exact ⟨_, ⟨L₀, _, rfl⟩, hL₀ L₀ le_rfl⟩

theorem dist_le_of_mem_cube {L : ℤ} {t : Fin d → ℤ} {x y : Rd d}
    (hx : x ∈ (G.cube L t : Set (Rd d))) (hy : y ∈ (G.cube L t : Set (Rd d))) :
    dist x y ≤ Real.sqrt d * G.side L := by
  rw [EuclideanSpace.dist_eq]
  have hs := G.side_pos L
  have hcoord : ∀ i, dist (x i) (y i) ^ 2 ≤ G.side L ^ 2 := by
    intro i
    have h1 := hx i
    have h2 := hy i
    simp only [cube] at h1 h2
    rw [Real.dist_eq, sq_abs]
    nlinarith [h1.1, h1.2, h2.1, h2.2]
  calc Real.sqrt (∑ i, dist (x i) (y i) ^ 2) ≤ Real.sqrt (∑ _i : Fin d, G.side L ^ 2) :=
        Real.sqrt_le_sqrt (Finset.sum_le_sum fun i _ => hcoord i)
    _ = Real.sqrt d * G.side L := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul,
          Real.sqrt_mul (Nat.cast_nonneg d), Real.sqrt_sq hs.le]

end GridData

/-- The prototype dyadic lattice `𝔔` of the paper (BRS §1, TeX l.420–427): cubes of side
`2^L` with corners `2^L (m + (-1)^L/3)`, `m ∈ ℤ^d` (with `L = -k` in the paper's notation). -/
noncomputable def protoGrid (d : ℕ) : GridData d where
  s := 1
  s_pos := one_pos
  o L _ := (-1 : ℝ) ^ L / 3
  k L _ := if Even L then 1 else -1
  nest L i := by
    rcases Int.even_or_odd L with he | ho
    · have ho' : Odd (L - 1) := he.sub_odd odd_one
      rw [he.neg_one_zpow, ho'.neg_one_zpow]
      simp only [he, ↓reduceIte]
      norm_num
    · have he' : Even (L - 1) := ho.sub_odd odd_one
      rw [ho.neg_one_zpow, he'.neg_one_zpow]
      simp only [Int.not_even_iff_odd.2 ho, ↓reduceIte]
      norm_num
  η := 1 / 3
  η_pos := by norm_num
  margin L _ := by
    rcases Int.even_or_odd L with he | ho
    · rw [he.neg_one_zpow]
      have : Int.fract (-(1 / 3 : ℝ)) = 2 / 3 := by
        rw [Int.fract_neg (by rw [Int.fract_eq_self.2 ⟨by norm_num, by norm_num⟩]; norm_num),
          Int.fract_eq_self.2 ⟨by norm_num, by norm_num⟩]
        norm_num
      norm_num [this]
    · rw [ho.neg_one_zpow]
      have : Int.fract (-(-1 / 3 : ℝ)) = 1 / 3 := by
        rw [neg_div, neg_neg, Int.fract_eq_self.2 ⟨by norm_num, by norm_num⟩]
      norm_num [this]

end Auto
