/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import LeanSparse.Auto.Sec1Introduction

/-!
# Multi-scale sparse domination, §3: single scale estimates

This file was automatically generated by Claude.

Results from §3 of D. Beltran, J. Roos, A. Seeger, *Multi-scale sparse domination*
(arXiv:2009.00227, TeX lines 1389–1632), together with the elementary measure-theoretic facts
they need:

* volumes of cubes and the change of variables under dilations;
* the rescaled single-scale bound (eqn:Tjrescale) and the rescaled support property of `T_j`;
* Hölder's inequality for the pairing `⟨F, g⟩`;
* Lemma 3.1 (single-scale-lem);
* the conditional expectations `𝔼_n` and Corollary 3.4 / (Tjrega), (Tjregb), proved by a direct
  martingale-difference argument (ErrorReport E4).
-/

@[expose] public section

open MeasureTheory Set Module Pointwise
open scoped ENNReal NNReal

namespace Auto

variable {d : ℕ}

/-! ### Cubes: measurability and volume -/

namespace Cube

theorem toSet_eq (Q : Cube d) :
    (Q : Set (Rd d)) =
      (WithLp.ofLp) ⁻¹' Set.pi univ fun i => Ico (Q.corner i) (Q.corner i + Q.side) := by
  ext x
  simp [toSet]

theorem measurableSet (Q : Cube d) : MeasurableSet (Q : Set (Rd d)) := by
  rw [toSet_eq]
  exact (MeasurableSet.univ_pi fun _ => measurableSet_Ico).preimage
    (PiLp.volume_preserving_ofLp _).measurable

theorem volume_eq (Q : Cube d) : volume (Q : Set (Rd d)) = ENNReal.ofReal (Q.side ^ d) := by
  rw [toSet_eq, (PiLp.volume_preserving_ofLp (Fin d)).measure_preimage
    (MeasurableSet.univ_pi fun _ => measurableSet_Ico).nullMeasurableSet, Real.volume_pi_Ico]
  simp only [add_sub_cancel_left, Finset.prod_const, Finset.card_univ, Fintype.card_fin]
  rw [ENNReal.ofReal_pow Q.side_pos.le]

theorem volume_ne_zero (Q : Cube d) : volume (Q : Set (Rd d)) ≠ 0 := by
  rw [volume_eq]
  exact (ENNReal.ofReal_pos.2 (pow_pos Q.side_pos d)).ne'

theorem volume_ne_top (Q : Cube d) : volume (Q : Set (Rd d)) ≠ ∞ := by
  rw [volume_eq]
  exact ENNReal.ofReal_ne_top

theorem triple_side (Q : Cube d) : Q.triple.side = 3 * Q.side := rfl

theorem volume_triple (Q : Cube d) :
    volume (Q.triple : Set (Rd d)) = 3 ^ d * volume (Q : Set (Rd d)) := by
  rw [volume_eq, volume_eq, triple_side, mul_pow, ENNReal.ofReal_mul (by positivity),
    ENNReal.ofReal_pow (by norm_num)]
  norm_num

theorem subset_triple (Q : Cube d) : (Q : Set (Rd d)) ⊆ Q.triple := by
  intro x hx i
  have := hx i
  have := Q.side_pos
  simp only [triple]
  constructor <;> linarith [(hx i).1, (hx i).2]

end Cube

/-! ### Dilations and change of variables -/

theorem finrank_rd : finrank ℝ (Rd d) = d := finrank_euclideanSpace_fin

/-- Change of variables `∫ G(r x) dx = |r|^{-d} ∫ G` for nonnegative functions. -/
theorem lintegral_comp_smul (G : Rd d → ℝ≥0∞) {r : ℝ} (hr : r ≠ 0) :
    ∫⁻ x, G (r • x) = ENNReal.ofReal (|r ^ d|⁻¹) * ∫⁻ x, G x := by
  let e : Rd d ≃ᵐ Rd d := (Homeomorph.smulOfNeZero r hr).toMeasurableEquiv
  have h1 : ∫⁻ x, G (r • x) = ∫⁻ x, G x ∂(Measure.map e volume) :=
    (lintegral_map_equiv G e).symm
  rw [h1]
  have h2 : Measure.map e volume = Measure.map (r • ·) (volume : Measure (Rd d)) := rfl
  rw [h2, Measure.map_addHaar_smul volume hr, lintegral_smul_measure, finrank_rd, abs_inv,
    smul_eq_mul]

theorem aestronglyMeasurable_comp_smul {B : Type*} [NormedAddCommGroup B] {F : Rd d → B}
    (hF : AEStronglyMeasurable F volume) {r : ℝ} (hr : r ≠ 0) :
    AEStronglyMeasurable (fun x => F (r • x)) volume :=
  hF.comp_quasiMeasurePreserving (Measure.quasiMeasurePreserving_smul volume hr)

/-- `‖F(r ·)‖_p = |r|^{-d/p} ‖F‖_p` for `0 < p < ∞`. -/
theorem eLpNorm_comp_smul {B : Type*} [NormedAddCommGroup B] {F : Rd d → B}
    (hF : AEStronglyMeasurable F volume) {r : ℝ} (hr : r ≠ 0) {p : ℝ} (hp : 0 < p) :
    eLpNorm (fun x => F (r • x)) (.ofReal p) volume =
      ENNReal.ofReal (|r ^ d|⁻¹) ^ (1 / p) * eLpNorm F (.ofReal p) volume := by
  have hp0 : ENNReal.ofReal p ≠ 0 := by simpa using hp
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 ENNReal.ofReal_ne_top
      (aestronglyMeasurable_comp_smul hF hr),
    eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 ENNReal.ofReal_ne_top hF,
    ENNReal.toReal_ofReal hp.le, lintegral_comp_smul (fun x => ‖F x‖ₑ ^ p) hr,
    ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]

theorem SimpleCpt.dil_apply {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B] [NormedSpace 𝕜 B]
    (j : ℤ) (f : SimpleCpt d 𝕜 B) (x : Rd d) :
    SimpleCpt.dil j f x = f ((2 : ℝ) ^ j • x) := rfl

theorem SimpleCpt.transl_apply {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (h : Rd d) (f : SimpleCpt d 𝕜 B) (x : Rd d) :
    SimpleCpt.transl h f x = f (x + h) := rfl

theorem SimpleCpt.diff_apply {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (h : Rd d) (f : SimpleCpt d 𝕜 B) (x : Rd d) :
    SimpleCpt.diff h f x = f (x + h) - f x := rfl

theorem SimpleCpt.dil_neg_dil {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (j : ℤ) (f : SimpleCpt d 𝕜 B) :
    SimpleCpt.dil (-j) (SimpleCpt.dil j f) = f := by
  ext x
  change f ((2 : ℝ) ^ j • (2 : ℝ) ^ (-j) • x) = f x
  rw [smul_smul, ← zpow_add₀ two_ne_zero, add_neg_cancel, zpow_zero, one_smul]

/-! ### Restrictions, `L^p` norms over cubes and Hölder for the pairing -/

/-- The restriction `f 1_S` of `f ∈ 𝒮_B` to a measurable set `S`. -/
noncomputable def SimpleCpt.restrict {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (f : SimpleCpt d 𝕜 B) {S : Set (Rd d)} (hS : MeasurableSet S) :
    SimpleCpt d 𝕜 B :=
  ⟨(f : SimpleFunc (Rd d) B).restrict S, by
    change HasCompactSupport ⇑((f : SimpleFunc (Rd d) B).restrict S)
    rw [SimpleFunc.coe_restrict _ hS]
    exact f.2.mono fun x hx => by by_cases h : x ∈ S <;> simp_all⟩

theorem SimpleCpt.restrict_apply {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (f : SimpleCpt d 𝕜 B) {S : Set (Rd d)} (hS : MeasurableSet S) :
    ⇑(SimpleCpt.restrict f hS) = S.indicator f :=
  SimpleFunc.coe_restrict _ hS

theorem SimpleCpt.aestronglyMeasurable {𝕜 B : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedSpace 𝕜 B] (f : SimpleCpt d 𝕜 B) : AEStronglyMeasurable f volume :=
  (f : SimpleFunc (Rd d) B).aestronglyMeasurable

/-- `‖f 1_S‖_p = |S|^{1/p} ⟨f⟩_{S,p}` for `0 < |S| < ∞`. -/
theorem eLpNorm_indicator_eq_avgNorm {B : Type*} [NormedAddCommGroup B] {f : Rd d → B}
    (hf : AEStronglyMeasurable f volume) {S : Set (Rd d)} (hS : MeasurableSet S)
    (hS0 : volume S ≠ 0) (hStop : volume S ≠ ∞) {p : ℝ} (hp : 0 < p) :
    eLpNorm (S.indicator f) (.ofReal p) volume = volume S ^ (1 / p) * avgNorm f S p := by
  have hp0 : ENNReal.ofReal p ≠ 0 := by simpa using hp
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 ENNReal.ofReal_ne_top
    (hf.indicator hS), ENNReal.toReal_ofReal hp.le, avgNorm,
    ← ENNReal.mul_rpow_of_nonneg _ _ (by positivity), ← mul_assoc,
    ENNReal.mul_inv_cancel hS0 hStop, one_mul]
  congr 1
  rw [← lintegral_indicator hS]
  refine lintegral_congr fun x => ?_
  by_cases hx : x ∈ S
  · simp [hx]
  · simp [hx, ENNReal.zero_rpow_of_pos hp]

section Pairing

variable {𝕜 : Type*} [RCLike 𝕜] {B₂ : Type*} [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- Hölder's inequality for the pairing: `|⟨F, g⟩| ≤ ‖F‖_q ‖g‖_{q'}`. -/
theorem enorm_pairing_le {F : Rd d → B₂} {g : Rd d → StrongDual 𝕜 B₂}
    (hF : AEStronglyMeasurable F volume) (hg : AEStronglyMeasurable g volume) {q : ℝ}
    (hq : 1 < q) :
    ‖pairing F g‖ₑ ≤
      eLpNorm F (.ofReal q) volume * eLpNorm g (.ofReal q.conjExponent) volume := by
  have hpq := Real.HolderConjugate.conjExponent hq
  have hq0 : ENNReal.ofReal q ≠ 0 := by simpa using hpq.pos
  have hq'0 : ENNReal.ofReal q.conjExponent ≠ 0 := by simpa using hpq.symm.pos
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hq0 ENNReal.ofReal_ne_top hF,
    eLpNorm_eq_lintegral_rpow_enorm_toReal hq'0 ENNReal.ofReal_ne_top hg,
    ENNReal.toReal_ofReal hpq.pos.le, ENNReal.toReal_ofReal hpq.symm.pos.le]
  calc ‖pairing F g‖ₑ ≤ ∫⁻ x, ‖g x (F x)‖ₑ := enorm_integral_le_lintegral_enorm _
    _ ≤ ∫⁻ x, ‖F x‖ₑ * ‖g x‖ₑ := by
        refine lintegral_mono fun x => ?_
        rw [mul_comm]
        exact (g x).le_opENorm (F x)
    _ ≤ _ := ENNReal.lintegral_mul_le_Lp_mul_Lq volume hpq hF.enorm hg.enorm

/-- If `F = 0` almost everywhere outside `S`, then `⟨F, g⟩ = ⟨F, g 1_S⟩`. -/
theorem pairing_eq_pairing_indicator {F : Rd d → B₂} {g : Rd d → StrongDual 𝕜 B₂}
    {S : Set (Rd d)} (hF : ∀ᵐ x ∂volume, x ∉ S → F x = 0) :
    pairing F g = pairing F (S.indicator g) := by
  unfold pairing
  refine integral_congr_ae ?_
  filter_upwards [hF] with x hx
  by_cases hxS : x ∈ S
  · simp [hxS]
  · simp [hxS, hx hxS]

end Pairing

/-! ### Rescaling: the single scale bound and the support property for `T_j` -/

/-- The volume `2^{jd}` of a cube of side length `2^j`. -/
noncomputable def scaleVol (d : ℕ) (j : ℤ) : ℝ≥0∞ := ENNReal.ofReal (((2 : ℝ) ^ j) ^ d)

theorem scaleVol_ne_zero (j : ℤ) : scaleVol d j ≠ 0 := by
  unfold scaleVol
  exact (ENNReal.ofReal_pos.2 (by positivity)).ne'

theorem scaleVol_ne_top (j : ℤ) : scaleVol d j ≠ ∞ := ENNReal.ofReal_ne_top

theorem scaleVol_neg (j : ℤ) : ENNReal.ofReal (|((2 : ℝ) ^ (-j)) ^ d|⁻¹) = scaleVol d j := by
  unfold scaleVol
  congr 1
  rw [zpow_neg, inv_pow, abs_inv, inv_inv, abs_of_pos (by positivity)]

theorem scaleVol_pos_inv (j : ℤ) :
    ENNReal.ofReal (|((2 : ℝ) ^ j) ^ d|⁻¹) = (scaleVol d j)⁻¹ := by
  unfold scaleVol
  rw [abs_of_pos (by positivity), ENNReal.ofReal_inv_of_pos (by positivity)]

theorem Cube.volume_eq_scaleVol (Q : Cube d) {j : ℤ} (hQ : Q.side = (2 : ℝ) ^ j) :
    volume (Q : Set (Rd d)) = scaleVol d j := by
  rw [Q.volume_eq, hQ, scaleVol]

section Rescaling

variable {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

theorem op_apply_eq_dilOp (T : Op d 𝕜 B₁ B₂) (j : ℤ) (f : SimpleCpt d 𝕜 B₁) (y : Rd d) :
    T f y = dilOp j T (SimpleCpt.dil j f) ((2 : ℝ) ^ (-j) • y) := by
  simp only [dilOp, SimpleCpt.dil_neg_dil, smul_smul, ← zpow_add₀ (two_ne_zero (α := ℝ)),
    add_neg_cancel, zpow_zero, one_smul]

/-- (eqn:Tjrescale): `‖T_j‖_{L^p → L^q} ≤ 2^{-jd(1/p - 1/q)} A∘(p,q)`, with
`2^{jd} = scaleVol d j`. -/
theorem eLpNorm_op_le_of_singleScale {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q A₀ : ℝ} (hp : 0 < p)
    (hq : 0 < q) (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (hss : ∀ f, eLpNorm (dilOp j T f) (.ofReal q) volume ≤
      ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume) (f : SimpleCpt d 𝕜 B₁) :
    eLpNorm (T f) (.ofReal q) volume ≤
      ENNReal.ofReal A₀ * scaleVol d j ^ (1 / q - 1 / p) * eLpNorm f (.ofReal p) volume := by
  have hG : AEStronglyMeasurable (dilOp j T (SimpleCpt.dil j f)) volume := by
    have : dilOp j T (SimpleCpt.dil j f) = fun x => T f ((2 : ℝ) ^ j • x) := by
      funext x
      simp only [dilOp, SimpleCpt.dil_neg_dil]
    rw [this]
    exact aestronglyMeasurable_comp_smul (hmeas f) (zpow_ne_zero j two_ne_zero)
  have h1 : (T f) = fun y => dilOp j T (SimpleCpt.dil j f) ((2 : ℝ) ^ (-j) • y) := by
    funext y
    exact op_apply_eq_dilOp T j f y
  have h2 : eLpNorm (SimpleCpt.dil j f) (.ofReal p) volume =
      (scaleVol d j)⁻¹ ^ (1 / p) * eLpNorm f (.ofReal p) volume := by
    have := eLpNorm_comp_smul (F := ⇑f) (SimpleCpt.aestronglyMeasurable f)
      (zpow_ne_zero j two_ne_zero) hp
    rw [scaleVol_pos_inv] at this
    exact this
  rw [h1, eLpNorm_comp_smul hG (zpow_ne_zero (-j) two_ne_zero) hq, scaleVol_neg]
  calc scaleVol d j ^ (1 / q) * eLpNorm (dilOp j T (SimpleCpt.dil j f)) (.ofReal q) volume
      ≤ scaleVol d j ^ (1 / q) * (ENNReal.ofReal A₀ *
          ((scaleVol d j)⁻¹ ^ (1 / p) * eLpNorm f (.ofReal p) volume)) := by
        gcongr
        rw [← h2]
        exact hss _
    _ = ENNReal.ofReal A₀ * scaleVol d j ^ (1 / q - 1 / p) * eLpNorm f (.ofReal p) volume := by
        rw [ENNReal.inv_rpow, ← ENNReal.rpow_neg, sub_eq_add_neg,
          ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j)]
        ring

/-- The rescaled support property: `T_j f = 0` a.e. on `{x : dist(x, supp f) > 2^j}`. -/
theorem ae_op_eq_zero_of_support {T : Op d 𝕜 B₁ B₂} {j : ℤ}
    (hsupp : ∀ f : SimpleCpt d 𝕜 B₁, ∀ᵐ x ∂volume,
      1 < Metric.infDist x (Function.support ⇑f) → dilOp j T f x = 0)
    (f : SimpleCpt d 𝕜 B₁) :
    ∀ᵐ y ∂volume, (2 : ℝ) ^ j < Metric.infDist y (Function.support ⇑f) → T f y = 0 := by
  have hr : (2 : ℝ) ^ (-j) ≠ 0 := zpow_ne_zero _ two_ne_zero
  filter_upwards [(Measure.quasiMeasurePreserving_smul volume hr).ae
    (hsupp (SimpleCpt.dil j f))] with y hy hdist
  rw [op_apply_eq_dilOp T j f y]
  apply hy
  have hsupp_eq : Function.support ⇑(SimpleCpt.dil j f) =
      (2 : ℝ) ^ (-j) • Function.support ⇑f := by
    ext x
    rw [Set.mem_smul_set_iff_inv_smul_mem₀ hr, zpow_neg, inv_inv]
    simp [SimpleCpt.dil_apply]
  rw [hsupp_eq, infDist_smul₀ hr, Real.norm_eq_abs, abs_of_pos (by positivity), zpow_neg,
    ← div_eq_inv_mul, lt_div_iff₀ (by positivity), one_mul]
  exact hdist

end Rescaling

/-! ### Lemma 3.1 -/

namespace Cube

/-- The closed triple cube `∏ᵢ [aᵢ - ℓ, aᵢ + 2ℓ]`. -/
def closedTriple (Q : Cube d) : Set (Rd d) :=
  {x | ∀ i, Q.corner i - Q.side ≤ x i ∧ x i ≤ Q.corner i + 2 * Q.side}

theorem triple_ae_eq_closedTriple (Q : Cube d) :
    (Q.triple : Set (Rd d)) =ᵐ[volume] Q.closedTriple := by
  have h1 : (Q.triple : Set (Rd d)) = (WithLp.ofLp) ⁻¹'
      Set.pi univ fun i => Ico (Q.corner i - Q.side) (Q.corner i + 2 * Q.side) := by
    rw [toSet_eq]
    congr 1
    ext x
    simp only [triple, mem_pi, mem_univ, forall_const, mem_Ico]
    constructor <;> intro h i <;> constructor <;> linarith [(h i).1, (h i).2]
  have h2 : Q.closedTriple = (WithLp.ofLp) ⁻¹'
      Icc (fun i => Q.corner i - Q.side) (fun i => Q.corner i + 2 * Q.side) := by
    ext x
    simp only [closedTriple, mem_ofPred_eq, mem_preimage, mem_Icc, Pi.le_def]
    exact ⟨fun h => ⟨fun i => (h i).1, fun i => (h i).2⟩, fun h i => ⟨h.1 i, h.2 i⟩⟩
  rw [h1, h2]
  exact (PiLp.volume_preserving_ofLp (Fin d)).quasiMeasurePreserving.preimage_ae_eq
    (Measure.univ_pi_Ico_ae_eq_Icc (μ := fun _ => volume))

/-- Points outside the closed triple cube are at distance `> ℓ(Q)` from every nonempty subset
of `Q`. -/
theorem side_lt_infDist (Q : Cube d) {S : Set (Rd d)} (hS : S ⊆ Q) (hSne : S.Nonempty)
    {y : Rd d} (hy : y ∉ Q.closedTriple) : Q.side < Metric.infDist y S := by
  simp only [closedTriple, mem_ofPred_eq, not_forall, not_and_or, not_le] at hy
  obtain ⟨i, hi⟩ := hy
  have key : ∀ g : ℝ, Q.side < g → (∀ z ∈ S, g ≤ dist y z) → Q.side < Metric.infDist y S := by
    intro g hg hz
    refine lt_of_lt_of_le hg ?_
    by_contra hlt
    rw [not_le, Metric.infDist_lt_iff hSne] at hlt
    obtain ⟨z, hzS, hz'⟩ := hlt
    exact absurd (hz z hzS) (not_le.2 hz')
  have hcoord : ∀ z : Rd d, |y i - z i| ≤ dist y z := fun z => by
    rw [← Real.dist_eq]
    exact PiLp.dist_apply_le y z i
  rcases hi with hi | hi
  · refine key (Q.corner i - y i) (by linarith) fun z hz => ?_
    have := (hS hz i).1
    exact le_trans (by rw [abs_sub_comm]; exact le_trans (by linarith) (le_abs_self _))
      (hcoord z)
  · refine key (y i - Q.corner i - Q.side) (by linarith) fun z hz => ?_
    have := (hS hz i).2
    exact le_trans (le_trans (by linarith) (le_abs_self _)) (hcoord z)

end Cube

section Lemma31

variable {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

theorem SimpleCpt.eq_zero_of_support_empty {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
    (f : SimpleCpt d 𝕜 B) (hf : Function.support ⇑f = ∅) : f = 0 := by
  ext x
  have : x ∉ Function.support ⇑f := by rw [hf]; exact Set.notMem_empty x
  simpa using this

/-- If `supp f ⊆ Q` with `ℓ(Q) = 2^j`, then `T_j f = 0` a.e. outside `3Q`. -/
theorem ae_op_eq_zero_outside_triple {T : Op d 𝕜 B₁ B₂} {j : ℤ}
    (hsupp : ∀ f : SimpleCpt d 𝕜 B₁, ∀ᵐ x ∂volume,
      1 < Metric.infDist x (Function.support ⇑f) → dilOp j T f x = 0)
    (Q : Cube d) (hQ : Q.side = (2 : ℝ) ^ j) (f : SimpleCpt d 𝕜 B₁)
    (hf : Function.support ⇑f ⊆ Q) :
    ∀ᵐ y ∂volume, y ∉ (Q.triple : Set (Rd d)) → T f y = 0 := by
  rcases (Function.support ⇑f).eq_empty_or_nonempty with he | hne
  · rw [SimpleCpt.eq_zero_of_support_empty f he, map_zero]
    exact Filter.Eventually.of_forall fun _ _ => rfl
  filter_upwards [ae_op_eq_zero_of_support hsupp f, Q.triple_ae_eq_closedTriple] with y hy hyC
    hy3
  apply hy
  rw [← hQ]
  refine Q.side_lt_infDist hf hne fun hyc => hy3 ?_
  have : (y ∈ (Q.triple : Set (Rd d))) = (y ∈ Q.closedTriple) := hyC
  rw [this]
  exact hyc

/-- **Lemma 3.1** (single-scale-lem). If `T_j` satisfies the support condition (support-assu) and
the single scale condition (p-q-rescaled), then for every cube `Q` of side length `2^j`,
`|⟨T_j[f₁ 1_Q], f₂⟩| ≤ 3^{d/q'} A∘(p,q) |Q| ⟨f₁⟩_{Q,p} ⟨f₂⟩_{3Q,q'}`. -/
theorem single_scale_lem {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q A₀ : ℝ} (hp : 1 < p) (hq : 1 < q)
    (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (hsupp : ∀ f : SimpleCpt d 𝕜 B₁, ∀ᵐ x ∂volume,
      1 < Metric.infDist x (Function.support ⇑f) → dilOp j T f x = 0)
    (hss : ∀ f, eLpNorm (dilOp j T f) (.ofReal q) volume ≤
      ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume)
    (Q : Cube d) (hQ : Q.side = (2 : ℝ) ^ j) (f₁ : SimpleCpt d 𝕜 B₁)
    (f₂ : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) :
    ‖pairing (T (SimpleCpt.restrict f₁ Q.measurableSet)) f₂‖ₑ ≤
      (3 ^ d : ℝ≥0∞) ^ (1 / q.conjExponent) * ENNReal.ofReal A₀ * volume (Q : Set (Rd d)) *
        avgNorm f₁ Q p * avgNorm f₂ Q.triple q.conjExponent := by
  have hpq := Real.HolderConjugate.conjExponent hq
  set g := SimpleCpt.restrict f₁ Q.measurableSet with hg
  have hgsupp : Function.support ⇑g ⊆ Q := by
    rw [hg, SimpleCpt.restrict_apply]
    exact Set.support_indicator_subset
  rw [pairing_eq_pairing_indicator (ae_op_eq_zero_outside_triple hsupp Q hQ g hgsupp)]
  have hσ := Q.volume_eq_scaleVol hQ
  have h3 := Q.triple.measurableSet
  refine (enorm_pairing_le (hmeas g)
    ((SimpleCpt.aestronglyMeasurable f₂).indicator h3) hq).trans ?_
  rw [eLpNorm_indicator_eq_avgNorm (SimpleCpt.aestronglyMeasurable f₂) h3
    Q.triple.volume_ne_zero Q.triple.volume_ne_top hpq.symm.pos, Q.volume_triple]
  have hT := eLpNorm_op_le_of_singleScale (by linarith) (by linarith) hmeas hss g
  rw [hg, SimpleCpt.restrict_apply, eLpNorm_indicator_eq_avgNorm
    (SimpleCpt.aestronglyMeasurable f₁) Q.measurableSet Q.volume_ne_zero Q.volume_ne_top
    (by linarith)] at hT
  calc eLpNorm (T g) (.ofReal q) volume *
        ((3 ^ d * volume (Q : Set (Rd d))) ^ (1 / q.conjExponent) *
          avgNorm f₂ Q.triple q.conjExponent)
      ≤ (ENNReal.ofReal A₀ * scaleVol d j ^ (1 / q - 1 / p) *
          (volume (Q : Set (Rd d)) ^ (1 / p) * avgNorm f₁ Q p)) *
        ((3 ^ d * volume (Q : Set (Rd d))) ^ (1 / q.conjExponent) *
          avgNorm f₂ Q.triple q.conjExponent) := by gcongr
    _ = (3 ^ d : ℝ≥0∞) ^ (1 / q.conjExponent) * ENNReal.ofReal A₀ *
          (scaleVol d j ^ (1 / q - 1 / p) * scaleVol d j ^ (1 / p) *
            scaleVol d j ^ (1 / q.conjExponent)) *
          avgNorm f₁ Q p * avgNorm f₂ Q.triple q.conjExponent := by
        rw [hσ, ENNReal.mul_rpow_of_nonneg _ _ (by have := hpq.symm.pos; positivity)]
        ring
    _ = _ := by
        rw [← ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j),
          ← ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j), hσ]
        have : 1 / q - 1 / p + 1 / p + 1 / q.conjExponent = 1 := by
          have := hpq.inv_add_inv_eq_one
          simp only [one_div] at this ⊢
          linarith
        rw [this, ENNReal.rpow_one]

end Lemma31

/-! ### Averages over sets of positive finite measure -/

section Averages

variable {B : Type*} [NormedAddCommGroup B] [NormedSpace ℝ B]

/-- The normalized restriction `|S|⁻¹ 1_S dx`. -/
noncomputable def normRestrict (S : Set (Rd d)) : Measure (Rd d) :=
  (volume S)⁻¹ • volume.restrict S

theorem isProbabilityMeasure_normRestrict {S : Set (Rd d)} (hS0 : volume S ≠ 0)
    (hStop : volume S ≠ ∞) : IsProbabilityMeasure (normRestrict S) := by
  constructor
  simp [normRestrict, ENNReal.inv_mul_cancel hS0 hStop]

omit [NormedSpace ℝ B] in
theorem avgNorm_eq_eLpNorm' (f : Rd d → B) (S : Set (Rd d)) (p : ℝ) :
    avgNorm f S p = eLpNorm' f p (normRestrict S) := by
  simp [avgNorm, eLpNorm', normRestrict, lintegral_smul_measure]

/-- `|⨍_S f| ≤ ⟨f⟩_{S,p}` for `p ≥ 1`. -/
theorem enorm_setAverage_le_avgNorm {f : Rd d → B} (hf : AEStronglyMeasurable f volume)
    {S : Set (Rd d)} (hS0 : volume S ≠ 0) (hStop : volume S ≠ ∞) {p : ℝ} (hp : 1 ≤ p) :
    ‖⨍ x in S, f x‖ₑ ≤ avgNorm f S p := by
  have := isProbabilityMeasure_normRestrict hS0 hStop
  rw [setAverage_eq', avgNorm_eq_eLpNorm']
  have hfm : AEStronglyMeasurable f (normRestrict S) :=
    (hf.restrict).smul_measure _
  calc ‖∫ x, f x ∂(volume S)⁻¹ • volume.restrict S‖ₑ
      ≤ ∫⁻ x, ‖f x‖ₑ ∂(normRestrict S) := enorm_integral_le_lintegral_enorm _
    _ = eLpNorm' f 1 (normRestrict S) := by simp [eLpNorm']
    _ ≤ eLpNorm' f p (normRestrict S) :=
        eLpNorm'_le_eLpNorm'_of_exponent_le one_pos hp _ hfm

/-- `|S| |⨍_S f|^p ≤ ∫_S |f|^p` for `p ≥ 1`. -/
theorem volume_mul_enorm_setAverage_rpow_le {f : Rd d → B}
    (hf : AEStronglyMeasurable f volume) {S : Set (Rd d)} (hS0 : volume S ≠ 0)
    (hStop : volume S ≠ ∞) {p : ℝ} (hp : 1 ≤ p) :
    volume S * ‖⨍ x in S, f x‖ₑ ^ p ≤ ∫⁻ x in S, ‖f x‖ₑ ^ p := by
  have h := enorm_setAverage_le_avgNorm hf hS0 hStop hp
  have hp0 : 0 < p := by linarith
  calc volume S * ‖⨍ x in S, f x‖ₑ ^ p ≤ volume S * avgNorm f S p ^ p := by gcongr
    _ = ∫⁻ x in S, ‖f x‖ₑ ^ p := by
        rw [avgNorm, ← ENNReal.rpow_mul, one_div, inv_mul_cancel₀ hp0.ne', ENNReal.rpow_one,
          ← mul_assoc, ENNReal.mul_inv_cancel hS0 hStop, one_mul]

end Averages

/-! ### Conditional expectations with respect to a grid lattice -/

namespace GridData

variable (G : GridData d)

theorem cube_measurableSet (L : ℤ) (t : Fin d → ℤ) :
    MeasurableSet (G.cube L t : Set (Rd d)) := Cube.measurableSet _

theorem pairwiseDisjoint_cube (L : ℤ) :
    Pairwise fun t t' : Fin d → ℤ => Disjoint (G.cube L t : Set (Rd d)) (G.cube L t') := by
  intro t t' hne
  rw [Set.disjoint_left]
  intro x hx hx'
  exact hne (G.eq_of_mem_cube hx hx')

theorem iUnion_cube (L : ℤ) : ⋃ t, (G.cube L t : Set (Rd d)) = univ :=
  eq_univ_of_forall fun x => mem_iUnion.2 ⟨_, G.mem_cube_idx L x⟩

/-- Integrals over `ℝ^d` split over the level `L` cubes. -/
theorem lintegral_eq_tsum_cube (L : ℤ) (F : Rd d → ℝ≥0∞) :
    ∫⁻ x, F x = ∑' t, ∫⁻ x in (G.cube L t : Set (Rd d)), F x := by
  rw [← lintegral_iUnion (G.cube_measurableSet L) (G.pairwiseDisjoint_cube L), G.iUnion_cube,
    Measure.restrict_univ]

theorem cube_isBounded (L : ℤ) (t : Fin d → ℤ) :
    Bornology.IsBounded (G.cube L t : Set (Rd d)) := by
  refine (Metric.isBounded_closedBall (x := WithLp.toLp 2 (G.cube L t).corner)
    (r := Real.sqrt d * G.side L)).subset fun x hx => ?_
  rw [Metric.mem_closedBall]
  exact G.dist_le_of_mem_cube hx (G.cube L t).corner_mem

/-- The cubes of level `L` meeting a bounded set have indices in a finite box. -/
theorem exists_finset_of_isBounded (L : ℤ) {S : Set (Rd d)} (hS : Bornology.IsBounded S) :
    ∃ I : Finset (Fin d → ℤ), ∀ t, ((G.cube L t : Set (Rd d)) ∩ S).Nonempty → t ∈ I := by
  obtain ⟨R, hR⟩ := hS.subset_closedBall (0 : Rd d)
  let N : Fin d → ℤ := fun i => ⌈R / G.side L + |G.o L i|⌉ + 1
  refine ⟨Fintype.piFinset fun i => Finset.Icc (-N i) (N i), fun t ⟨x, hxQ, hxS⟩ => ?_⟩
  rw [Fintype.mem_piFinset]
  intro i
  have hs := G.side_pos L
  have hx := hR hxS
  have hxi : |x i| ≤ R := by
    have := PiLp.norm_apply_le x i
    rw [Metric.mem_closedBall, dist_zero_right] at hx
    rw [← Real.norm_eq_abs]
    linarith
  rw [G.mem_cube_iff] at hxQ
  have hti : t i = ⌊x i / G.side L - G.o L i⌋ := by rw [hxQ]; rfl
  have h1 : |x i / G.side L| ≤ R / G.side L := by
    rw [abs_div, abs_of_pos hs]
    exact div_le_div_of_nonneg_right hxi hs.le
  have hc := Int.le_ceil (R / G.side L + |G.o L i|)
  rw [Finset.mem_Icc, hti]
  rw [abs_le] at h1
  have ho := neg_abs_le (G.o L i)
  have ho' := le_abs_self (G.o L i)
  constructor
  · have := Int.lt_floor_add_one (x i / G.side L - G.o L i)
    have h2 : (-(N i : ℝ)) < ⌊x i / G.side L - G.o L i⌋ + 1 := by
      simp only [N]; push_cast; linarith
    have : -(N i) < ⌊x i / G.side L - G.o L i⌋ + 1 := by exact_mod_cast h2
    omega
  · have := Int.floor_le (x i / G.side L - G.o L i)
    have h2 : ((⌊x i / G.side L - G.o L i⌋ : ℤ) : ℝ) ≤ N i := by
      simp only [N]; push_cast; linarith
    exact_mod_cast h2

end GridData

section CondExp

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
  [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] (G : GridData d)

/-- The conditional expectation `𝔼_L f(x) = ⨍_{Q} f` with respect to the level `L` cubes of a
grid lattice, `Q ∋ x` the level `L` cube containing `x` (BRS §3.3, TeX l.1459–1460, with
`𝔼_n` corresponding to level `L = -n`). -/
noncomputable def condExpFun (L : ℤ) (f : Rd d → B) (x : Rd d) : B :=
  ⨍ y in (G.cube L (G.idx L x) : Set (Rd d)), f y

theorem condExpFun_eq_of_mem {L : ℤ} {t : Fin d → ℤ} {x : Rd d}
    (hx : x ∈ (G.cube L t : Set (Rd d))) (f : Rd d → B) :
    condExpFun G L f x = ⨍ y in (G.cube L t : Set (Rd d)), f y := by
  rw [condExpFun, ← G.mem_cube_iff.1 hx]

omit [NormedSpace ℝ B] in
theorem simpleFunc_coe_finset_sum {ι : Type*} (I : Finset ι) (F : ι → SimpleFunc (Rd d) B) :
    ⇑(∑ t ∈ I, F t) = ∑ t ∈ I, ⇑(F t) := by
  classical
  induction I using Finset.induction_on with
  | empty => simp
  | insert a I ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, SimpleFunc.coe_add, ih]

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] in
theorem SimpleCpt.integrableOn_cube (f : SimpleCpt d 𝕜 B) (Q : Cube d) :
    IntegrableOn f (Q : Set (Rd d)) volume := by
  have : IsFiniteMeasure (volume.restrict (Q : Set (Rd d))) :=
    isFiniteMeasure_restrict.2 Q.volume_ne_top
  exact SimpleFunc.integrable_of_isFiniteMeasure (f : SimpleFunc (Rd d) B)

omit [IsScalarTower ℝ 𝕜 B] in
/-- `𝔼_L f` is again a compactly supported simple function. -/
theorem exists_simpleCpt_condExpFun (L : ℤ) (f : SimpleCpt d 𝕜 B) :
    ∃ g : SimpleCpt d 𝕜 B, ⇑g = condExpFun G L f := by
  obtain ⟨I, hI⟩ := G.exists_finset_of_isBounded L f.2.isCompact.isBounded
  let g : SimpleFunc (Rd d) B := ∑ t ∈ I,
    (SimpleFunc.const (Rd d) (⨍ y in (G.cube L t : Set (Rd d)), f y)).restrict
      (G.cube L t : Set (Rd d))
  have hg : ∀ x, g x = condExpFun G L f x := by
    intro x
    simp only [g, simpleFunc_coe_finset_sum, Finset.sum_apply,
      SimpleFunc.coe_restrict _ (G.cube_measurableSet L _), SimpleFunc.coe_const]
    rw [Finset.sum_eq_single (G.idx L x)]
    · rw [indicator_of_mem (G.mem_cube_idx L x)]
      rfl
    · intro t _ ht
      rw [indicator_of_notMem]
      intro hx
      exact ht (G.mem_cube_iff.1 hx)
    · intro hnot
      rw [indicator_of_mem (G.mem_cube_idx L x), Function.const_apply]
      have hzero : ∀ y ∈ (G.cube L (G.idx L x) : Set (Rd d)), f y = 0 := by
        intro y hy
        by_contra hfy
        exact hnot (hI _ ⟨y, hy, subset_tsupport _ hfy⟩)
      rw [setAverage_eq, setIntegral_congr_fun (G.cube_measurableSet L _) hzero]
      simp
  have hgc : HasCompactSupport ⇑g := by
    have hsub : Function.support ⇑g ⊆ ⋃ t ∈ I, (G.cube L t : Set (Rd d)) := by
      intro x hx
      simp only [g, Function.mem_support, simpleFunc_coe_finset_sum, Finset.sum_apply,
        SimpleFunc.coe_restrict _ (G.cube_measurableSet L _)] at hx
      obtain ⟨t, ht, hne⟩ := Finset.exists_ne_zero_of_sum_ne_zero hx
      exact mem_iUnion₂.2 ⟨t, ht, by by_contra h; exact hne (indicator_of_notMem h _)⟩
    have hb : Bornology.IsBounded (⋃ t ∈ I, (G.cube L t : Set (Rd d))) :=
      (Bornology.isBounded_biUnion_finset _).2 fun t _ => G.cube_isBounded L t
    exact HasCompactSupport.intro' hb.isCompact_closure isClosed_closure
      fun x hx => by_contra fun h => hx (hsub.trans subset_closure (Function.mem_support.2 h))
  exact ⟨⟨g, hgc⟩, funext hg⟩

/-- The conditional expectation `𝔼_L` as a linear operator on `𝒮_B`. -/
noncomputable def condExp (L : ℤ) : SimpleCpt d 𝕜 B →ₗ[𝕜] SimpleCpt d 𝕜 B where
  toFun f := Classical.choose (exists_simpleCpt_condExpFun G L f)
  map_add' f g := by
    apply Subtype.ext
    apply SimpleFunc.ext
    intro x
    change Classical.choose (exists_simpleCpt_condExpFun G L (f + g)) x =
      Classical.choose (exists_simpleCpt_condExpFun G L f) x +
        Classical.choose (exists_simpleCpt_condExpFun G L g) x
    rw [Classical.choose_spec (exists_simpleCpt_condExpFun G L (f + g)),
      Classical.choose_spec (exists_simpleCpt_condExpFun G L f),
      Classical.choose_spec (exists_simpleCpt_condExpFun G L g)]
    simp only [condExpFun]
    change ⨍ y in _, ((f : SimpleFunc (Rd d) B) + (g : SimpleFunc (Rd d) B)) y = _
    rw [SimpleFunc.coe_add]
    exact setAverage_add (SimpleCpt.integrableOn_cube f _) (SimpleCpt.integrableOn_cube g _)
  map_smul' c f := by
    apply Subtype.ext
    apply SimpleFunc.ext
    intro x
    change Classical.choose (exists_simpleCpt_condExpFun G L (c • f)) x =
      c • Classical.choose (exists_simpleCpt_condExpFun G L f) x
    rw [Classical.choose_spec (exists_simpleCpt_condExpFun G L (c • f)),
      Classical.choose_spec (exists_simpleCpt_condExpFun G L f)]
    simp only [condExpFun]
    change ⨍ y in _, (c • (f : SimpleFunc (Rd d) B)) y = _
    rw [SimpleFunc.coe_smul]
    rw [setAverage_eq, setAverage_eq]
    simp only [Pi.smul_apply]
    rw [integral_smul, smul_comm]

theorem condExp_apply (L : ℤ) (f : SimpleCpt d 𝕜 B) :
    ⇑(condExp G L f) = condExpFun G L f :=
  Classical.choose_spec (exists_simpleCpt_condExpFun G L f)

/-- `𝔼_L` is a contraction on `L^p`, `p ≥ 1`. -/
theorem eLpNorm_condExp_le (L : ℤ) (f : SimpleCpt d 𝕜 B) {p : ℝ} (hp : 1 ≤ p) :
    eLpNorm (condExp G L f) (.ofReal p) volume ≤ eLpNorm f (.ofReal p) volume := by
  have hp0 : ENNReal.ofReal p ≠ 0 := by simp; linarith
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 ENNReal.ofReal_ne_top
      (SimpleCpt.aestronglyMeasurable _),
    eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 ENNReal.ofReal_ne_top
      (SimpleCpt.aestronglyMeasurable _), ENNReal.toReal_ofReal (by linarith)]
  gcongr 1
  rw [G.lintegral_eq_tsum_cube L, G.lintegral_eq_tsum_cube L]
  refine ENNReal.tsum_le_tsum fun t => ?_
  rw [condExp_apply]
  calc ∫⁻ x in (G.cube L t : Set (Rd d)), ‖condExpFun G L (⇑f) x‖ₑ ^ p
      = ∫⁻ x in (G.cube L t : Set (Rd d)), ‖⨍ y in (G.cube L t : Set (Rd d)), f y‖ₑ ^ p :=
        setLIntegral_congr_fun (G.cube_measurableSet L t) fun x hx => by
          rw [condExpFun_eq_of_mem G hx]
    _ = volume (G.cube L t : Set (Rd d)) * ‖⨍ y in (G.cube L t : Set (Rd d)), f y‖ₑ ^ p := by
        rw [setLIntegral_const, mul_comm]
    _ ≤ _ := volume_mul_enorm_setAverage_rpow_le (SimpleCpt.aestronglyMeasurable f)
        (Cube.volume_ne_zero _) (Cube.volume_ne_top _) hp

end CondExp

/-! ### The martingale differences as sums of differences `Δ_h` (ErrorReport E4) -/

namespace GridData

variable (G : GridData d)

/-- The index set `{0,1}^d` of the children of a cube. -/
def bits (d : ℕ) : Finset (Fin d → ℤ) := Fintype.piFinset fun _ => ({0, 1} : Finset ℤ)

theorem card_bits : (bits d).card = 2 ^ d := by
  simp [bits, Fintype.card_piFinset]

theorem mem_bits {w : Fin d → ℤ} : w ∈ bits d ↔ ∀ i, w i = 0 ∨ w i = 1 := by
  simp [bits, Fintype.mem_piFinset]

/-- The position `t - k_L mod 2 ∈ {0,1}^d` of the level `L - 1` cube `t` inside its parent. -/
def childType (L : ℤ) (t : Fin d → ℤ) : Fin d → ℤ := fun i => (t i - G.k L i) % 2

theorem childType_mem_bits (L : ℤ) (t : Fin d → ℤ) : G.childType L t ∈ bits d :=
  mem_bits.2 fun i => by simp only [childType]; omega

theorem eq_child_parent (L : ℤ) (t : Fin d → ℤ) :
    t = fun i => 2 * G.parent L t i + G.k L i + G.childType L t i := by
  funext i
  simp only [parent, childType]
  omega

theorem idx_add_shift (L : ℤ) (x : Rd d) (n : Fin d → ℤ) :
    G.idx L (x + WithLp.toLp 2 (fun i => (n i : ℝ) * G.side L)) = G.idx L x + n := by
  funext i
  have hs := (G.side_pos L).ne'
  simp only [idx, PiLp.add_apply, Pi.add_apply]
  rw [add_div, mul_div_cancel_right₀ _ hs, show x i / G.side L + n i - G.o L i =
    (x i / G.side L - G.o L i) + n i by ring, Int.floor_add_intCast]

/-- The level `L` cube containing `x` is the parent of the level `L - 1` cube containing `x`. -/
theorem idx_eq_parent_idx (L : ℤ) (x : Rd d) :
    G.idx L x = G.parent L (G.idx (L - 1) x) :=
  G.eq_of_mem_cube (G.mem_cube_idx L x)
    ((G.isDyadicSubcubeAt_parent L _).subset (G.mem_cube_idx (L - 1) x))

/-- The set of points lying in level `L - 1` cubes of type `w`. -/
def typeSet (L : ℤ) (w : Fin d → ℤ) : Set (Rd d) := {x | G.childType L (G.idx (L - 1) x) = w}

theorem typeSet_eq (L : ℤ) (w : Fin d → ℤ) :
    G.typeSet L w =
      ⋃ (t : Fin d → ℤ) (_ : G.childType L t = w), (G.cube (L - 1) t : Set (Rd d)) := by
  ext x
  simp only [typeSet, mem_ofPred_eq, mem_iUnion, exists_prop]
  constructor
  · intro h
    exact ⟨_, h, G.mem_cube_idx _ x⟩
  · rintro ⟨t, ht, hx⟩
    rw [← G.mem_cube_iff.1 hx]
    exact ht

theorem measurableSet_typeSet (L : ℤ) (w : Fin d → ℤ) : MeasurableSet (G.typeSet L w) := by
  rw [typeSet_eq]
  exact MeasurableSet.iUnion fun t => MeasurableSet.iUnion fun _ => G.cube_measurableSet _ t

/-- The translation `h_{vw} = (w - v) 2^{L-1} s` between children of types `v` and `w`. -/
noncomputable def shift (L : ℤ) (v w : Fin d → ℤ) : Rd d :=
  WithLp.toLp 2 fun i => ((w i - v i : ℤ) : ℝ) * G.side (L - 1)

theorem norm_shift_le (L : ℤ) {v w : Fin d → ℤ} (hv : v ∈ bits d) (hw : w ∈ bits d) :
    ‖G.shift L v w‖ ≤ Real.sqrt d * G.side (L - 1) := by
  have hs := (G.side_pos (L - 1)).le
  rw [EuclideanSpace.norm_eq]
  have hcoord : ∀ i, ‖(G.shift L v w) i‖ ^ 2 ≤ G.side (L - 1) ^ 2 := by
    intro i
    have h1 := (mem_bits.1 hv) i
    have h2 := (mem_bits.1 hw) i
    simp only [shift, PiLp.toLp_apply, Real.norm_eq_abs, sq_abs]
    have : ((w i - v i : ℤ) : ℝ) ^ 2 ≤ 1 := by
      rcases h1 with h1 | h1 <;> rcases h2 with h2 | h2 <;> simp [h1, h2]
    nlinarith
  calc Real.sqrt (∑ i, ‖(G.shift L v w) i‖ ^ 2) ≤ Real.sqrt (∑ _i : Fin d, G.side (L - 1) ^ 2) :=
        Real.sqrt_le_sqrt (Finset.sum_le_sum fun i _ => hcoord i)
    _ = Real.sqrt d * G.side (L - 1) := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul,
          Real.sqrt_mul (Nat.cast_nonneg d), Real.sqrt_sq hs]

end GridData

section CoeLemmas

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]

@[simp] theorem SimpleCpt.coe_add' (f g : SimpleCpt d 𝕜 B) : ⇑(f + g) = ⇑f + ⇑g :=
  SimpleFunc.coe_add _ _

@[simp] theorem SimpleCpt.coe_sub' (f g : SimpleCpt d 𝕜 B) : ⇑(f - g) = ⇑f - ⇑g :=
  SimpleFunc.coe_sub _ _

@[simp] theorem SimpleCpt.coe_neg' (f : SimpleCpt d 𝕜 B) : ⇑(-f) = -⇑f :=
  SimpleFunc.coe_neg _

@[simp] theorem SimpleCpt.coe_smul' (c : 𝕜) (f : SimpleCpt d 𝕜 B) : ⇑(c • f) = c • ⇑f :=
  SimpleFunc.coe_smul _ _

@[simp] theorem SimpleCpt.coe_zero' : ⇑(0 : SimpleCpt d 𝕜 B) = 0 := SimpleFunc.coe_zero

@[simp] theorem SimpleCpt.coe_sum' {ι : Type*} (I : Finset ι) (F : ι → SimpleCpt d 𝕜 B) :
    ⇑(∑ t ∈ I, F t) = ∑ t ∈ I, ⇑(F t) := by
  classical
  induction I using Finset.induction_on with
  | empty => simp
  | insert a I ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, SimpleCpt.coe_add', ih]

end CoeLemmas

section Haar

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
  [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] (G : GridData d)

omit [IsScalarTower ℝ 𝕜 B] in
/-- The average over a level `L` cube is the mean of the averages over its `2^d` children. -/
theorem setAverage_cube_eq_sum_children (L : ℤ) (t : Fin d → ℤ) (f : SimpleCpt d 𝕜 B) :
    ⨍ y in (G.cube L t : Set (Rd d)), f y = ((2 : ℝ) ^ d)⁻¹ •
      ∑ w ∈ GridData.bits d,
        ⨍ y in (G.cube (L - 1) (fun i => 2 * t i + G.k L i + w i) : Set (Rd d)), f y := by
  classical
  set child : (Fin d → ℤ) → Set (Rd d) :=
    fun w => (G.cube (L - 1) (fun i => 2 * t i + G.k L i + w i) : Set (Rd d)) with hchild
  have hunion : (G.cube L t : Set (Rd d)) = ⋃ w ∈ GridData.bits d, child w := by
    ext y
    simp only [mem_iUnion, exists_prop, hchild]
    constructor
    · intro hy
      have hp : G.parent L (G.idx (L - 1) y) = t :=
        (G.idx_eq_parent_idx L y).symm.trans (G.mem_cube_iff.1 hy).symm
      refine ⟨G.childType L (G.idx (L - 1) y), G.childType_mem_bits L _, ?_⟩
      have := G.eq_child_parent L (G.idx (L - 1) y)
      rw [hp] at this
      rw [← this]
      exact G.mem_cube_idx _ y
    · rintro ⟨w, hw, hy⟩
      have h := G.isDyadicSubcubeAt_child L t (fun i => (w i).toNat)
        (fun i => by have := (GridData.mem_bits.1 hw) i; omega)
      have heq : (fun i => 2 * t i + G.k L i + ((w i).toNat : ℤ)) =
          fun i => 2 * t i + G.k L i + w i := by
        funext i
        have := (GridData.mem_bits.1 hw) i
        congr 1
        omega
      rw [heq] at h
      exact h.subset hy
  have hdisj : (GridData.bits d : Set (Fin d → ℤ)).PairwiseDisjoint child := by
    intro w _ w' _ hne
    apply G.pairwiseDisjoint_cube (L - 1)
    intro h
    apply hne
    funext i
    have := congrFun h i
    omega
  have hvolc : ∀ w, volume.real (child w) =
      ((2 : ℝ) ^ d)⁻¹ * volume.real (G.cube L t : Set (Rd d)) := by
    intro w
    simp only [hchild, Measure.real, Cube.volume_eq, GridData.cube, GridData.side_sub_one]
    rw [ENNReal.toReal_ofReal (by have := G.side_pos L; positivity),
      ENNReal.toReal_ofReal (by have := G.side_pos L; positivity), div_pow]
    field_simp
  have hvolP : volume.real (G.cube L t : Set (Rd d)) ≠ 0 := by
    rw [Measure.real, ENNReal.toReal_ne_zero]
    exact ⟨Cube.volume_ne_zero _, Cube.volume_ne_top _⟩
  rw [setAverage_eq, hunion, integral_biUnion_finset _ (fun w _ => G.cube_measurableSet _ _) hdisj
    (fun w _ => SimpleCpt.integrableOn_cube f _), ← hunion, Finset.smul_sum, Finset.smul_sum]
  refine Finset.sum_congr rfl fun w _ => ?_
  rw [setAverage_eq, smul_smul, hvolc w]
  congr 1
  field_simp

/-- The functions `g_w = (𝔼_{L-1} f) 1_{U_w}`. -/
noncomputable def haarPiece (L : ℤ) (w : Fin d → ℤ) (f : SimpleCpt d 𝕜 B) : SimpleCpt d 𝕜 B :=
  SimpleCpt.restrict (condExp G (L - 1) f) (G.measurableSet_typeSet L w)

/-- **Haar decomposition** of the martingale difference:
`𝔼_{L-1} f - 𝔼_L f = -2^{-d} ∑_{v,w ∈ {0,1}^d} Δ_{h_{vw}} g_w`. -/
theorem condExp_sub_condExp_eq (L : ℤ) (f : SimpleCpt d 𝕜 B) :
    condExp G (L - 1) f - condExp G L f = -(((2 : 𝕜) ^ d)⁻¹ •
      ∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d,
        SimpleCpt.diff (G.shift L v w) (haarPiece G L w f)) := by
  classical
  apply Subtype.ext
  apply SimpleFunc.ext
  intro x
  have hx : ∀ g : SimpleCpt d 𝕜 B, (g : SimpleFunc (Rd d) B) x = g x := fun _ => rfl
  rw [hx, hx]
  simp only [SimpleCpt.coe_sub', SimpleCpt.coe_neg', SimpleCpt.coe_smul', SimpleCpt.coe_sum',
    Pi.sub_apply, Pi.neg_apply, Pi.smul_apply, Finset.sum_apply, SimpleCpt.diff_apply]
  set t' := G.idx (L - 1) x with ht'
  set u := G.childType L t' with hu
  set P := G.parent L t' with hP
  have hpiece : ∀ w y, (haarPiece G L w f) y =
      if G.childType L (G.idx (L - 1) y) = w then
        ⨍ z in (G.cube (L - 1) (G.idx (L - 1) y) : Set (Rd d)), f z else 0 := by
    intro w y
    rw [haarPiece, SimpleCpt.restrict_apply, condExp_apply]
    by_cases h : G.childType L (G.idx (L - 1) y) = w
    · rw [indicator_of_mem (show y ∈ G.typeSet L w from h), ite_eq_left h]
      rfl
    · rw [indicator_of_notMem (show y ∉ G.typeSet L w from h), ite_eq_right h]
  set A : (Fin d → ℤ) → B := fun w =>
    ⨍ z in (G.cube (L - 1) (fun i => 2 * P i + G.k L i + w i) : Set (Rd d)), f z with hA
  set a : B := ⨍ z in (G.cube (L - 1) t' : Set (Rd d)), f z with ha
  have key1 : ∀ v ∈ GridData.bits d, ∀ w ∈ GridData.bits d,
      (haarPiece G L w f) (x + G.shift L v w) = if v = u then A w else 0 := by
    intro v hv w hw
    rw [hpiece, GridData.shift, G.idx_add_shift (L - 1) x (fun i => w i - v i)]
    have hiff : G.childType L (G.idx (L - 1) x + fun i => w i - v i) = w ↔ v = u := by
      constructor
      · intro h
        funext i
        have h1 := congrFun h i
        have h2 := (GridData.mem_bits.1 hv) i
        have h3 := (GridData.mem_bits.1 hw) i
        simp only [GridData.childType, Pi.add_apply] at h1
        simp only [hu, ht', GridData.childType]
        omega
      · rintro rfl
        funext i
        have h3 := (GridData.mem_bits.1 hw) i
        simp only [hu, ht', GridData.childType, Pi.add_apply]
        omega
    by_cases hvu : v = u
    · have hidx : (G.idx (L - 1) x + fun i => w i - v i) =
          fun i => 2 * P i + G.k L i + w i := by
        funext i
        have := congrFun (G.eq_child_parent L t') i
        have h' := congrFun hvu i
        simp only [Pi.add_apply, ← ht', ← hP, ← hu] at this h' ⊢
        omega
      have hc := hiff.2 hvu
      simp only [hc, ↓reduceIte]
      rw [hidx]
      simp only [hvu, ↓reduceIte, hA]
    · have hc : ¬G.childType L (G.idx (L - 1) x + fun i => w i - v i) = w :=
        fun h => hvu (hiff.1 h)
      simp only [hc, hvu, ↓reduceIte]
  have key2 : ∀ w ∈ GridData.bits d, (haarPiece G L w f) x = if w = u then a else 0 := by
    intro w _
    rw [hpiece]
    by_cases hwu : w = u
    · have h1 : G.childType L (G.idx (L - 1) x) = w := by rw [← ht', ← hu, hwu]
      simp only [h1, hwu, ↓reduceIte]
      rfl
    · have h1 : G.childType L (G.idx (L - 1) x) ≠ w := by
        rw [← ht', ← hu]; exact Ne.symm hwu
      simp only [h1, hwu, ↓reduceIte]
  have hsum : ∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d,
      ((haarPiece G L w f) (x + G.shift L v w) - (haarPiece G L w f) x) =
      ∑ w ∈ GridData.bits d, A w - (2 ^ d : ℕ) • a := by
    rw [Finset.sum_congr rfl fun v hv => Finset.sum_congr rfl fun w hw => by
      rw [key1 v hv w hw, key2 w hw]]
    have hu_mem : u ∈ GridData.bits d := G.childType_mem_bits L t'
    have s1 : ∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d, (if v = u then A w else 0) =
        ∑ w ∈ GridData.bits d, A w := by
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl fun w _ => ?_
      rw [Finset.sum_ite_eq' (GridData.bits d) u (fun _ => A w)]
      simp only [hu_mem, ↓reduceIte]
    have s2 : ∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d, (if w = u then a else 0) =
        (2 ^ d : ℕ) • a := by
      rw [Finset.sum_congr rfl fun v _ => Finset.sum_ite_eq' (GridData.bits d) u (fun _ => a)]
      simp only [hu_mem, ↓reduceIte, Finset.sum_const, GridData.card_bits]
    simp only [Finset.sum_sub_distrib]
    rw [s1, s2]
  have hparent := setAverage_cube_eq_sum_children G L P f
  have hEL : condExpFun G L (⇑f) x = ⨍ y in (G.cube L P : Set (Rd d)), f y := by
    rw [condExpFun, G.idx_eq_parent_idx L x]
  rw [condExp_apply, condExp_apply, hEL, hsum]
  change a - _ = _
  rw [hparent, ← hA]
  have h2 : ((2 : 𝕜) ^ d)⁻¹ • (∑ w ∈ GridData.bits d, A w - (2 ^ d : ℕ) • a) =
      ((2 : ℝ) ^ d)⁻¹ • (∑ w ∈ GridData.bits d, A w - (2 ^ d : ℕ) • a) := by
    rw [← algebraMap_smul 𝕜 ((2 : ℝ) ^ d)⁻¹]
    congr 1
    simp [map_ofNat]
  rw [h2, smul_sub, ← Nat.cast_smul_eq_nsmul ℝ, smul_smul, Nat.cast_pow, Nat.cast_ofNat,
    inv_mul_cancel₀ (by positivity), one_smul]
  abel

end Haar

/-! ### Convergence of `𝔼_L f` to `f` in `L^p` as `L → -∞` -/

namespace GridData

variable (G : GridData d)

/-- Every open set is the union of the grid cubes it contains. -/
theorem isOpen_eq_iUnion_cubes {O : Set (Rd d)} (hO : IsOpen O) :
    O = ⋃ (p : ℤ × (Fin d → ℤ)) (_ : (G.cube p.1 p.2 : Set (Rd d)) ⊆ O),
      (G.cube p.1 p.2 : Set (Rd d)) := by
  ext x
  simp only [mem_iUnion, exists_prop]
  constructor
  · intro hx
    obtain ⟨r, hr, hball⟩ := Metric.isOpen_iff.1 hO x hx
    obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one (div_pos hr
      (mul_pos (by positivity : (0 : ℝ) < Real.sqrt d + 1) G.s_pos)) (by norm_num : (1/2 : ℝ) < 1)
    refine ⟨(-(n : ℤ), G.idx (-(n : ℤ)) x), fun y hy => hball ?_, G.mem_cube_idx _ x⟩
    have h1 := G.dist_le_of_mem_cube hy (G.mem_cube_idx _ x)
    rw [Metric.mem_ball]
    have h2 : G.side (-(n : ℤ)) = G.s * (1 / 2) ^ n := by
      simp [side, zpow_neg, zpow_natCast]
    rw [h2] at h1
    rw [lt_div_iff₀ (mul_pos (by positivity) G.s_pos)] at hn
    have h3 := Real.sqrt_nonneg (d : ℝ)
    have h4 : (0 : ℝ) ≤ (1 / 2) ^ n := by positivity
    nlinarith [G.s_pos]
  · rintro ⟨p, hp, hx⟩
    exact hp hx

/-- Measurable sets of finite measure are approximated in measure by finite unions of grid
cubes. -/
theorem exists_finset_cubes_approx {A : Set (Rd d)} (hA : MeasurableSet A) (hAfin : volume A ≠ ∞)
    {δ : ℝ≥0∞} (hδ : 0 < δ) :
    ∃ F : Finset (ℤ × (Fin d → ℤ)),
      volume (symmDiff A (⋃ p ∈ F, (G.cube p.1 p.2 : Set (Rd d)))) < δ := by
  classical
  by_cases hδtop : δ = ∞
  · refine ⟨∅, ?_⟩
    have : symmDiff A
        (⋃ p ∈ (∅ : Finset (ℤ × (Fin d → ℤ))), (G.cube p.1 p.2 : Set (Rd d))) = A := by
      ext x; simp [symmDiff]
    rw [this, hδtop]
    exact hAfin.lt_top
  have hδ2 : 0 < δ / 2 := ENNReal.div_pos hδ.ne' (by norm_num)
  obtain ⟨O, hAO, hO, hOμ⟩ := Set.exists_isOpen_lt_of_lt A (volume A + δ / 2)
    (ENNReal.lt_add_right hAfin hδ2.ne')
  have hOfin : volume O ≠ ∞ := (hOμ.trans (ENNReal.add_lt_top.2 ⟨hAfin.lt_top,
    ENNReal.div_lt_top hδtop (by norm_num)⟩)).ne
  obtain ⟨e, he⟩ := exists_surjective_nat (ℤ × (Fin d → ℤ))
  let s : ℕ → Set (Rd d) := fun k =>
    if (G.cube (e k).1 (e k).2 : Set (Rd d)) ⊆ O then G.cube (e k).1 (e k).2 else ∅
  have hsU : ⋃ k, s k = O := by
    conv_rhs => rw [G.isOpen_eq_iUnion_cubes hO]
    ext x
    simp only [s, mem_iUnion, exists_prop]
    constructor
    · rintro ⟨k, hk⟩
      by_cases h : (G.cube (e k).1 (e k).2 : Set (Rd d)) ⊆ O
      · rw [ite_eq_left h] at hk; exact ⟨e k, h, hk⟩
      · rw [ite_eq_right h] at hk; exact absurd hk (notMem_empty x)
    · rintro ⟨p, hp, hx⟩
      obtain ⟨k, rfl⟩ := he p
      exact ⟨k, by rw [ite_eq_left hp]; exact hx⟩
  have hsup : volume O = ⨆ n, volume (accumulate s n) := by
    rw [← hsU, measure_iUnion_eq_iSup_accumulate]
  have hex : ∃ n, volume O < volume (accumulate s n) + δ / 2 := by
    by_cases h0 : volume O = 0
    · exact ⟨0, by rw [h0]; exact lt_of_lt_of_le hδ2 le_add_self⟩
    · have hlt := ENNReal.sub_lt_self hOfin h0 hδ2.ne'
      conv_rhs at hlt => rw [hsup]
      obtain ⟨n, hn⟩ := lt_iSup_iff.1 hlt
      exact ⟨n, ENNReal.lt_add_of_sub_lt_right (Or.inl hOfin) hn⟩
  obtain ⟨n, hn⟩ := hex
  refine ⟨((Finset.range (n + 1)).image e).filter
    fun p => (G.cube p.1 p.2 : Set (Rd d)) ⊆ O, ?_⟩
  set U := ⋃ p ∈ ((Finset.range (n + 1)).image e).filter
    (fun p => (G.cube p.1 p.2 : Set (Rd d)) ⊆ O), (G.cube p.1 p.2 : Set (Rd d)) with hU
  have hUacc : U = accumulate s n := by
    ext x
    simp only [hU, mem_iUnion, exists_prop, Finset.mem_filter, Finset.mem_image,
      Finset.mem_range, mem_accumulate, s]
    constructor
    · rintro ⟨p, ⟨⟨k, hk, rfl⟩, hp⟩, hx⟩
      exact ⟨k, by omega, by rw [ite_eq_left hp]; exact hx⟩
    · rintro ⟨k, hk, hx⟩
      by_cases h : (G.cube (e k).1 (e k).2 : Set (Rd d)) ⊆ O
      · rw [ite_eq_left h] at hx; exact ⟨e k, ⟨⟨k, by omega, rfl⟩, h⟩, hx⟩
      · rw [ite_eq_right h] at hx; exact absurd hx (notMem_empty x)
  have hUO : U ⊆ O := by
    intro x hx
    simp only [hU, mem_iUnion, exists_prop, Finset.mem_filter] at hx
    obtain ⟨p, ⟨_, hp⟩, hx⟩ := hx
    exact hp hx
  have hUmeas : MeasurableSet U :=
    Finset.measurableSet_biUnion _ fun p _ => G.cube_measurableSet _ _
  have h1 : volume (O \ U) < δ / 2 := by
    rw [measure_sdiff hUO hUmeas.nullMeasurableSet (ne_top_of_le_ne_top hOfin (measure_mono hUO))]
    rw [← hUacc, add_comm] at hn
    exact ENNReal.sub_lt_of_lt_add (measure_mono hUO) hn
  have h2 : volume (O \ A) < δ / 2 := by
    rw [measure_sdiff hAO hA.nullMeasurableSet hAfin]
    exact ENNReal.sub_lt_of_lt_add (measure_mono hAO) (by rwa [add_comm] at hOμ)
  calc volume (symmDiff A U) ≤ volume ((O \ U) ∪ (O \ A)) := by
        apply measure_mono
        rintro x (⟨hxA, hxU⟩ | ⟨hxU, hxA⟩)
        · exact Or.inl ⟨hAO hxA, hxU⟩
        · exact Or.inr ⟨hUO hxU, hxA⟩
    _ ≤ volume (O \ U) + volume (O \ A) := measure_union_le _ _
    _ < δ / 2 + δ / 2 := ENNReal.add_lt_add h1 h2
    _ = δ := ENNReal.add_halves δ

end GridData

section Convergence

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
  [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] (G : GridData d)

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
/-- The element `b 1_S ∈ 𝒮_B` for a bounded measurable set `S`. -/
noncomputable def SimpleCpt.indConst {S : Set (Rd d)} (hS : MeasurableSet S)
    (hSb : Bornology.IsBounded S) (b : B) : SimpleCpt d 𝕜 B :=
  ⟨(SimpleFunc.const (Rd d) b).restrict S, by
    change HasCompactSupport ⇑((SimpleFunc.const (Rd d) b).restrict S)
    rw [SimpleFunc.coe_restrict _ hS]
    refine HasCompactSupport.intro' hSb.isCompact_closure isClosed_closure fun x hx => ?_
    rw [indicator_of_notMem (fun h => hx (subset_closure h))]⟩

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
theorem SimpleCpt.indConst_apply {S : Set (Rd d)} (hS : MeasurableSet S)
    (hSb : Bornology.IsBounded S) (b : B) :
    ⇑(SimpleCpt.indConst (𝕜 := 𝕜) hS hSb b) = S.indicator fun _ => b :=
  SimpleFunc.coe_restrict _ hS

/-- If a set `U` is a union of grid cubes of levels `≥ L`, then `𝔼_L (b 1_U) = b 1_U`. -/
theorem condExp_indConst_union {F : Finset (ℤ × (Fin d → ℤ))} {L : ℤ}
    (hL : ∀ p ∈ F, L ≤ p.1) (hmeas : MeasurableSet (⋃ p ∈ F, (G.cube p.1 p.2 : Set (Rd d))))
    (hb : Bornology.IsBounded (⋃ p ∈ F, (G.cube p.1 p.2 : Set (Rd d)))) (b : B) :
    condExp G L (SimpleCpt.indConst (𝕜 := 𝕜) hmeas hb b) = SimpleCpt.indConst hmeas hb b := by
  set U := ⋃ p ∈ F, (G.cube p.1 p.2 : Set (Rd d)) with hU
  apply Subtype.ext
  apply SimpleFunc.ext
  intro x
  change (condExp G L (SimpleCpt.indConst (𝕜 := 𝕜) hmeas hb b)) x =
    (SimpleCpt.indConst (𝕜 := 𝕜) hmeas hb b) x
  rw [condExp_apply, condExpFun, SimpleCpt.indConst_apply]
  set C := (G.cube L (G.idx L x) : Set (Rd d)) with hC
  have hCvol : volume C ≠ 0 := Cube.volume_ne_zero _
  by_cases hx : x ∈ U
  · have hCU : C ⊆ U := by
      simp only [hU, mem_iUnion, exists_prop] at hx
      obtain ⟨p, hp, hxp⟩ := hx
      have h := G.isDyadicSubcube_of_inter (hL p hp) ⟨x, G.mem_cube_idx L x, hxp⟩
      exact h.subset.trans (subset_biUnion_of_mem (u := fun p : ℤ × (Fin d → ℤ) =>
        (G.cube p.1 p.2 : Set (Rd d))) hp)
    rw [indicator_of_mem hx, setAverage_congr_fun (G.cube_measurableSet _ _)
      (Filter.Eventually.of_forall fun y hy => indicator_of_mem (hCU hy) _),
      setAverage_const hCvol (Cube.volume_ne_top _)]
  · have hCU : ∀ y ∈ C, y ∉ U := by
      intro y hy hyU
      simp only [hU, mem_iUnion, exists_prop] at hyU
      obtain ⟨p, hp, hyp⟩ := hyU
      have h := G.isDyadicSubcube_of_inter (hL p hp) ⟨y, hy, hyp⟩
      exact hx (subset_biUnion_of_mem (u := fun p : ℤ × (Fin d → ℤ) =>
        (G.cube p.1 p.2 : Set (Rd d))) hp (h.subset (G.mem_cube_idx L x)))
    rw [indicator_of_notMem hx, setAverage_congr_fun (G.cube_measurableSet _ _)
      (Filter.Eventually.of_forall fun y hy => indicator_of_notMem (hCU y hy) _)]
    simp

/-- `𝔼_L (b 1_A) → b 1_A` in `L^p` as `L → -∞`. -/
theorem eventually_eLpNorm_indConst_sub_condExp_le {A : Set (Rd d)} (hA : MeasurableSet A)
    (hAb : Bornology.IsBounded A) (b : B) (g : SimpleCpt d 𝕜 B)
    (hg : g = SimpleCpt.indConst hA hAb b) {p : ℝ} (hp : 1 ≤ p) {ε : ℝ≥0∞} (hε : 0 < ε) :
    ∀ᶠ L in Filter.atBot, eLpNorm (⇑(g - condExp G L g)) (.ofReal p) volume ≤ ε := by
  classical
  by_cases hεtop : ε = ∞
  · exact Filter.Eventually.of_forall fun _ => hεtop ▸ le_top
  by_cases hb : b = 0
  · have : g = 0 := by
      apply Subtype.ext; apply SimpleFunc.ext; intro x
      change g x = 0
      rw [hg, SimpleCpt.indConst_apply, hb]
      simp
    refine Filter.Eventually.of_forall fun L => ?_
    rw [this]
    simp
  have hp0 : 0 < p := by linarith
  set c := ‖b‖ₑ with hc
  have hc0 : c ≠ 0 := by rw [hc]; exact enorm_ne_zero.2 hb
  have hctop : c ≠ ∞ := enorm_ne_top
  set δ := (ε / 2 / c) ^ p with hδ
  have hδpos : 0 < δ := by
    apply ENNReal.rpow_pos
    · exact ENNReal.div_pos (ENNReal.div_pos hε.ne' (by norm_num)).ne' hctop
    · exact ENNReal.div_ne_top (ENNReal.div_ne_top hεtop (by norm_num)) hc0
  obtain ⟨F, hF⟩ := G.exists_finset_cubes_approx hA hAb.measure_lt_top.ne hδpos
  set U := ⋃ p ∈ F, (G.cube p.1 p.2 : Set (Rd d)) with hU
  have hUm : MeasurableSet U := Finset.measurableSet_biUnion _ fun p _ => G.cube_measurableSet _ _
  have hUb : Bornology.IsBounded U :=
    (Bornology.isBounded_biUnion_finset _).2 fun p _ => G.cube_isBounded _ _
  set gU := SimpleCpt.indConst (𝕜 := 𝕜) hUm hUb b with hgU
  set L₀ : ℤ := -∑ q ∈ F, |q.1|
  have hL₀ : ∀ q ∈ F, L₀ ≤ q.1 := by
    intro q hq
    have := Finset.single_le_sum (f := fun q : ℤ × (Fin d → ℤ) => |q.1|)
      (fun _ _ => abs_nonneg _) hq
    have := neg_abs_le q.1
    linarith
  -- the error `‖g - gU‖_p`
  have herr : eLpNorm (⇑(g - gU)) (.ofReal p) volume ≤ ε / 2 := by
    have heq : eLpNorm (⇑(g - gU)) (.ofReal p) volume =
        eLpNorm ((symmDiff A U).indicator fun _ => b) (.ofReal p) volume := by
      refine eLpNorm_congr_enorm_ae (SimpleCpt.aestronglyMeasurable _)
        ((aestronglyMeasurable_const).indicator (hA.symmDiff hUm))
        (Filter.Eventually.of_forall fun x => ?_)
      rw [SimpleCpt.coe_sub', Pi.sub_apply, hg, hgU, SimpleCpt.indConst_apply,
        SimpleCpt.indConst_apply]
      by_cases hxA : x ∈ A <;> by_cases hxU : x ∈ U <;>
        simp [hxA, hxU, Set.indicator, symmDiff, enorm_neg]
    rw [heq, eLpNorm_indicator_const (hA.symmDiff hUm).nullMeasurableSet
      (by simp; linarith) ENNReal.ofReal_ne_top, ENNReal.toReal_ofReal hp0.le, ← hc]
    calc c * volume (symmDiff A U) ^ (1 / p) ≤ c * δ ^ (1 / p) := by
          gcongr
      _ = ε / 2 := by
          rw [hδ, ← ENNReal.rpow_mul, mul_one_div_cancel hp0.ne', ENNReal.rpow_one,
            ENNReal.mul_div_cancel hc0 hctop]
  rw [Filter.eventually_atBot]
  refine ⟨L₀, fun L hL => ?_⟩
  have hEgU : condExp G L gU = gU :=
    condExp_indConst_union G (fun q hq => le_trans hL (hL₀ q hq)) hUm hUb b
  have hdecomp : g - condExp G L g = (g - gU) - condExp G L (g - gU) := by
    rw [map_sub, hEgU]
    abel
  rw [hdecomp, SimpleCpt.coe_sub']
  calc eLpNorm (⇑(g - gU) - ⇑(condExp G L (g - gU))) (.ofReal p) volume
      ≤ eLpNorm (⇑(g - gU)) (.ofReal p) volume +
          eLpNorm (⇑(condExp G L (g - gU))) (.ofReal p) volume :=
        eLpNorm_sub_le (by simp; linarith)
    _ ≤ ε / 2 + ε / 2 := add_le_add herr ((eLpNorm_condExp_le G L _ hp).trans herr)
    _ = ε := ENNReal.add_halves ε

/-- **`𝔼_L f → f` in `L^p`** (`1 ≤ p < ∞`) as `L → -∞`, for `f ∈ 𝒮_B`. -/
theorem eventually_eLpNorm_sub_condExp_le (f : SimpleCpt d 𝕜 B) {p : ℝ} (hp : 1 ≤ p)
    {ε : ℝ≥0∞} (hε : 0 < ε) :
    ∀ᶠ L in Filter.atBot, eLpNorm (⇑(f - condExp G L f)) (.ofReal p) volume ≤ ε := by
  classical
  set S := (f : SimpleFunc (Rd d) B).range.filter (· ≠ 0) with hS
  have hfib : ∀ b, MeasurableSet ((f : SimpleFunc (Rd d) B) ⁻¹' {b}) :=
    fun b => SimpleFunc.measurableSet_fiber _ b
  have hfibb : ∀ b ∈ S, Bornology.IsBounded ((f : SimpleFunc (Rd d) B) ⁻¹' {b}) := by
    intro b hb
    refine f.2.isCompact.isBounded.subset fun x hx => subset_tsupport _ ?_
    rw [mem_preimage, mem_singleton_iff] at hx
    change f x ≠ 0
    rw [show f x = (f : SimpleFunc (Rd d) B) x from rfl, hx]
    exact (Finset.mem_filter.1 hb).2
  let gb : B → SimpleCpt d 𝕜 B := fun b =>
    if h : b ∈ S then SimpleCpt.indConst (hfib b) (hfibb b h) b else 0
  have hf : f = ∑ b ∈ S, gb b := by
    apply Subtype.ext; apply SimpleFunc.ext; intro x
    change f x = (∑ b ∈ S, gb b) x
    rw [SimpleCpt.coe_sum', Finset.sum_apply]
    have hterm : ∀ b ∈ S, (gb b) x =
        ((f : SimpleFunc (Rd d) B) ⁻¹' {b}).indicator (fun _ => b) x := by
      intro b hb
      simp only [gb, hb, ↓reduceDIte, SimpleCpt.indConst_apply]
    rw [Finset.sum_congr rfl hterm]
    by_cases hx : f x = 0
    · rw [hx]
      refine (Finset.sum_eq_zero fun b hb => indicator_of_notMem ?_ _).symm
      intro hmem
      rw [mem_preimage, mem_singleton_iff] at hmem
      exact (Finset.mem_filter.1 hb).2 (hmem ▸ hx)
    · have hmem : f x ∈ S := Finset.mem_filter.2 ⟨SimpleFunc.mem_range_self _ x, hx⟩
      rw [Finset.sum_eq_single_of_mem (f x) hmem]
      · rw [indicator_of_mem (by rfl)]
      · intro b _ hbx
        refine indicator_of_notMem ?_ _
        intro hmem'
        rw [mem_preimage, mem_singleton_iff] at hmem'
        exact hbx hmem'.symm
  by_cases hS0 : S.card = 0
  · rw [Finset.card_eq_zero] at hS0
    rw [hf, hS0, Finset.sum_empty]
    exact Filter.Eventually.of_forall fun _ => by simp
  set N : ℝ≥0∞ := (S.card : ℝ≥0∞) with hN
  have hN0 : N ≠ 0 := by rw [hN]; exact_mod_cast hS0
  have hεN : 0 < ε / N := ENNReal.div_pos hε.ne' (ENNReal.natCast_ne_top _)
  have hall : ∀ᶠ L in Filter.atBot, ∀ b ∈ S,
      eLpNorm (⇑(gb b - condExp G L (gb b))) (.ofReal p) volume ≤ ε / N := by
    rw [Filter.eventually_all_finset]
    intro b hb
    exact eventually_eLpNorm_indConst_sub_condExp_le G (hfib b) (hfibb b hb) b (gb b)
      (by simp only [gb, hb, ↓reduceDIte]) hp hεN
  filter_upwards [hall] with L hL
  have hsum : f - condExp G L f = ∑ b ∈ S, (gb b - condExp G L (gb b)) := by
    conv_lhs => rw [hf]
    rw [map_sum, Finset.sum_sub_distrib]
  rw [hsum, SimpleCpt.coe_sum']
  calc eLpNorm (∑ b ∈ S, ⇑(gb b - condExp G L (gb b))) (.ofReal p) volume
      ≤ ∑ b ∈ S, eLpNorm (⇑(gb b - condExp G L (gb b))) (.ofReal p) volume :=
        eLpNorm_sum_le (by simp; linarith)
    _ ≤ ∑ _b ∈ S, ε / N := Finset.sum_le_sum hL
    _ = ε := by
        rw [Finset.sum_const, nsmul_eq_mul, ← hN, ENNReal.mul_div_cancel hN0
          (ENNReal.natCast_ne_top _)]

end Convergence

/-! ### Corollary 3.4 for subadditive functionals

We prove the estimate `Φ((I - 𝔼_L) f) ≤ (∑_k a_k) ‖f‖_p` for a subadditive, absolutely
homogeneous functional `Φ` on `𝒮_B` dominated by `C₀ ‖·‖_p`, from bounds `a_k` on the
martingale differences `Φ((𝔼_{L-k-1} - 𝔼_{L-k}) u)`. The bounds on the martingale differences come
either from the Haar decomposition and a regularity estimate for `Φ ∘ Δ_h`, or from the trivial
bound. This covers both `Φ(u) = ‖T_j u‖_q` (Tjrega) and `Φ(g) = |⟨T_j f, g⟩|` (Tjregb). -/

section AbstractCor34

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
  [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] (G : GridData d)

/-- A subadditive, absolutely homogeneous functional on `𝒮_B`. -/
structure IsSubadditiveFun (Φ : SimpleCpt d 𝕜 B → ℝ≥0∞) : Prop where
  add_le : ∀ u v, Φ (u + v) ≤ Φ u + Φ v
  smul_eq : ∀ (c : 𝕜) u, Φ (c • u) = ‖c‖ₑ * Φ u

namespace IsSubadditiveFun

variable {Φ : SimpleCpt d 𝕜 B → ℝ≥0∞} (hΦ : IsSubadditiveFun Φ)
include hΦ

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
theorem map_zero : Φ 0 = 0 := by
  have := hΦ.smul_eq 0 0
  rwa [zero_smul, enorm_zero, zero_mul] at this

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
theorem map_neg (u : SimpleCpt d 𝕜 B) : Φ (-u) = Φ u := by
  have := hΦ.smul_eq (-1) u
  rwa [show (-1 : 𝕜) • u = -u from neg_one_smul 𝕜 u, enorm_neg, enorm_one, one_mul] at this

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
theorem sub_le (u v : SimpleCpt d 𝕜 B) : Φ (u - v) ≤ Φ u + Φ v := by
  rw [sub_eq_add_neg, ← hΦ.map_neg v]
  exact hΦ.add_le _ _

omit [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B] in
theorem sum_le {ι : Type*} (s : Finset ι) (u : ι → SimpleCpt d 𝕜 B) :
    Φ (∑ i ∈ s, u i) ≤ ∑ i ∈ s, Φ (u i) :=
  Finset.le_sum_of_subadditive Φ hΦ.map_zero.le hΦ.add_le s u

omit [CompleteSpace B] in
/-- Per-level bound from the Haar decomposition and a bound for `Φ ∘ Δ_h`. -/
theorem condExp_sub_le_of_diff {m : ℤ} {r : ℝ≥0∞} {p : ℝ} (hp : 1 ≤ p)
    (hr : ∀ v ∈ GridData.bits d, ∀ w ∈ GridData.bits d, ∀ u,
      Φ (SimpleCpt.diff (G.shift m v w) u) ≤ r * eLpNorm u (.ofReal p) volume)
    (u : SimpleCpt d 𝕜 B) :
    Φ (condExp G (m - 1) u - condExp G m u) ≤ 2 ^ d * r * eLpNorm u (.ofReal p) volume := by
  rw [condExp_sub_condExp_eq, hΦ.map_neg, hΦ.smul_eq]
  have hpiece : ∀ w, eLpNorm (haarPiece G m w u) (.ofReal p) volume ≤
      eLpNorm u (.ofReal p) volume := by
    intro w
    rw [haarPiece, SimpleCpt.restrict_apply]
    exact (eLpNorm_indicator_le _ (G.measurableSet_typeSet m w)).trans
      (eLpNorm_condExp_le G _ u hp)
  have hnorm : ‖((2 : 𝕜) ^ d)⁻¹‖ₑ = (2 ^ d)⁻¹ := by
    rw [enorm_inv (by simp), enorm_pow]
    congr 2
    rw [← ofReal_norm, RCLike.norm_two]
    simp
  rw [hnorm]
  calc (2 ^ d)⁻¹ * Φ (∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d,
        SimpleCpt.diff (G.shift m v w) (haarPiece G m w u))
      ≤ (2 ^ d)⁻¹ * ∑ v ∈ GridData.bits d, ∑ w ∈ GridData.bits d,
          r * eLpNorm u (.ofReal p) volume := by
        gcongr
        refine (hΦ.sum_le _ _).trans (Finset.sum_le_sum fun v hv => ?_)
        refine (hΦ.sum_le _ _).trans (Finset.sum_le_sum fun w hw => ?_)
        exact (hr v hv w hw _).trans (by gcongr; exact hpiece w)
    _ = 2 ^ d * r * eLpNorm u (.ofReal p) volume := by
        simp only [Finset.sum_const, GridData.card_bits, nsmul_eq_mul]
        push_cast
        rw [← mul_assoc, ← mul_assoc, ← mul_assoc, ENNReal.inv_mul_cancel (by simp) (by simp),
          one_mul]

omit [CompleteSpace B] in
/-- Per-level bound from the trivial bound `Φ ≤ C₀ ‖·‖_p`. -/
theorem condExp_sub_le_of_bdd {C₀ : ℝ≥0∞} {p : ℝ} (hp : 1 ≤ p)
    (hbdd : ∀ u, Φ u ≤ C₀ * eLpNorm u (.ofReal p) volume) (m : ℤ) (u : SimpleCpt d 𝕜 B) :
    Φ (condExp G (m - 1) u - condExp G m u) ≤ 2 * C₀ * eLpNorm u (.ofReal p) volume := by
  calc Φ (condExp G (m - 1) u - condExp G m u) ≤ Φ (condExp G (m - 1) u) + Φ (condExp G m u) :=
        hΦ.sub_le _ _
    _ ≤ C₀ * eLpNorm u (.ofReal p) volume + C₀ * eLpNorm u (.ofReal p) volume := by
        gcongr
        · exact (hbdd _).trans (by gcongr; exact eLpNorm_condExp_le G _ u hp)
        · exact (hbdd _).trans (by gcongr; exact eLpNorm_condExp_le G _ u hp)
    _ = 2 * C₀ * eLpNorm u (.ofReal p) volume := by ring

end IsSubadditiveFun

omit [CompleteSpace B] in
theorem condExp_telescope (L : ℤ) (f : SimpleCpt d 𝕜 B) (n : ℕ) :
    f - condExp G L f = (f - condExp G (L - n) f) +
      ∑ k ∈ Finset.range n, (condExp G (L - k - 1) f - condExp G (L - k) f) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ, ih]
    push_cast
    rw [show L - ((n : ℤ) + 1) = L - n - 1 by ring]
    abel

/-- **Abstract Corollary 3.4.** -/
theorem IsSubadditiveFun.le_of_condExp_sub_le {Φ : SimpleCpt d 𝕜 B → ℝ≥0∞}
    (hΦ : IsSubadditiveFun Φ) {C₀ : ℝ≥0∞} (hC₀ : C₀ ≠ ∞) {p : ℝ} (hp : 1 ≤ p)
    (hbdd : ∀ u, Φ u ≤ C₀ * eLpNorm u (.ofReal p) volume) (L : ℤ) (a : ℕ → ℝ≥0∞)
    (ha : ∀ (k : ℕ) u, Φ (condExp G (L - k - 1) u - condExp G (L - k) u) ≤
      a k * eLpNorm u (.ofReal p) volume) (f : SimpleCpt d 𝕜 B) :
    Φ (f - condExp G L f) ≤ (∑' k, a k) * eLpNorm f (.ofReal p) volume := by
  refine ENNReal.le_of_forall_pos_le_add fun η hη _ => ?_
  have hη' : (0 : ℝ≥0∞) < η / (C₀ + 1) :=
    ENNReal.div_pos (by exact_mod_cast hη.ne') (by simp [hC₀])
  obtain ⟨L₀, hL₀⟩ := Filter.eventually_atBot.1 (eventually_eLpNorm_sub_condExp_le G f hp hη')
  set n := (L - L₀).toNat
  have hn : L - (n : ℤ) ≤ L₀ := by omega
  rw [condExp_telescope G L f n]
  calc Φ ((f - condExp G (L - n) f) +
        ∑ k ∈ Finset.range n, (condExp G (L - k - 1) f - condExp G (L - k) f))
      ≤ Φ (f - condExp G (L - n) f) +
          ∑ k ∈ Finset.range n, Φ (condExp G (L - k - 1) f - condExp G (L - k) f) :=
        (hΦ.add_le _ _).trans (add_le_add le_rfl (hΦ.sum_le _ _))
    _ ≤ C₀ * (η / (C₀ + 1)) + ∑ k ∈ Finset.range n, a k * eLpNorm f (.ofReal p) volume := by
        gcongr with k
        · exact (hbdd _).trans (by gcongr; exact hL₀ _ hn)
        · exact ha k f
    _ ≤ η + (∑' k, a k) * eLpNorm f (.ofReal p) volume := by
        refine add_le_add ?_ ?_
        · calc C₀ * (η / (C₀ + 1)) ≤ (C₀ + 1) * (η / (C₀ + 1)) := by gcongr; exact le_self_add
            _ = η := ENNReal.mul_div_cancel (by simp) (by simp [hC₀])
        · rw [← Finset.sum_mul]
          gcongr
          exact ENNReal.sum_le_tsum _
    _ = (∑' k, a k) * eLpNorm f (.ofReal p) volume + η := add_comm _ _

end AbstractCor34

/-! ### Rescaled regularity of `T_j` -/

section RescaledRegularity

variable {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

theorem eLpNorm_dil (j : ℤ) (u : SimpleCpt d 𝕜 B₁) {p : ℝ} (hp : 0 < p) :
    eLpNorm (SimpleCpt.dil j u) (.ofReal p) volume =
      (scaleVol d j)⁻¹ ^ (1 / p) * eLpNorm u (.ofReal p) volume := by
  have := eLpNorm_comp_smul (F := ⇑u) (SimpleCpt.aestronglyMeasurable u)
    (zpow_ne_zero j two_ne_zero) hp
  rw [scaleVol_pos_inv] at this
  exact this

theorem eLpNorm_op_eq_dilOp {T : Op d 𝕜 B₁ B₂} (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (j : ℤ) (u : SimpleCpt d 𝕜 B₁) {q : ℝ} (hq : 0 < q) :
    eLpNorm (T u) (.ofReal q) volume =
      scaleVol d j ^ (1 / q) * eLpNorm (dilOp j T (SimpleCpt.dil j u)) (.ofReal q) volume := by
  have hG : AEStronglyMeasurable (dilOp j T (SimpleCpt.dil j u)) volume := by
    have : dilOp j T (SimpleCpt.dil j u) = fun x => T u ((2 : ℝ) ^ j • x) := by
      funext x
      simp only [dilOp, SimpleCpt.dil_neg_dil]
    rw [this]
    exact aestronglyMeasurable_comp_smul (hmeas u) (zpow_ne_zero j two_ne_zero)
  have h1 : (T u) = fun y => dilOp j T (SimpleCpt.dil j u) ((2 : ℝ) ^ (-j) • y) := by
    funext y
    exact op_apply_eq_dilOp T j u y
  rw [h1, eLpNorm_comp_smul hG (zpow_ne_zero (-j) two_ne_zero) hq, scaleVol_neg]

theorem SimpleCpt.dil_diff {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B] (j : ℤ)
    (h : Rd d) (u : SimpleCpt d 𝕜 B) :
    SimpleCpt.dil j (SimpleCpt.diff h u) =
      SimpleCpt.diff ((2 : ℝ) ^ (-j) • h) (SimpleCpt.dil j u) := by
  apply Subtype.ext; apply SimpleFunc.ext; intro x
  change (SimpleCpt.diff h u) ((2 : ℝ) ^ j • x) =
    (SimpleCpt.dil j u) (x + (2 : ℝ) ^ (-j) • h) - (SimpleCpt.dil j u) x
  rw [SimpleCpt.diff_apply, SimpleCpt.dil_apply, SimpleCpt.dil_apply, smul_add, smul_smul,
    ← zpow_add₀ two_ne_zero, add_neg_cancel, zpow_zero, one_smul]

theorem norm_two_zpow_smul (j : ℤ) (h : Rd d) : ‖(2 : ℝ) ^ (-j) • h‖ = ‖h‖ / 2 ^ j := by
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (by positivity), zpow_neg, inv_mul_eq_div]

/-- Rescaled regularity: `‖T_j Δ_h‖_{L^p → L^q} ≤ B (|h| 2^{-j})^ε 2^{-jd(1/p - 1/q)}` for
`|h| ≤ 2^j`. -/
theorem eLpNorm_op_diff_le {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q ε B : ℝ} (hp : 0 < p) (hq : 0 < q)
    (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (hreg : ∀ f (h : Rd d), ‖h‖ ≤ 1 →
      eLpNorm (dilOp j T (SimpleCpt.diff h f)) (.ofReal q) volume ≤
        ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume)
    (u : SimpleCpt d 𝕜 B₁) (h : Rd d) (hh : ‖h‖ ≤ 2 ^ j) :
    eLpNorm (T (SimpleCpt.diff h u)) (.ofReal q) volume ≤
      ENNReal.ofReal (B * (‖h‖ / 2 ^ j) ^ ε) * scaleVol d j ^ (1 / q - 1 / p) *
        eLpNorm u (.ofReal p) volume := by
  have hh' : ‖(2 : ℝ) ^ (-j) • h‖ ≤ 1 := by
    rw [norm_two_zpow_smul, div_le_one (by positivity)]
    exact hh
  rw [eLpNorm_op_eq_dilOp hmeas j _ hq, SimpleCpt.dil_diff]
  calc scaleVol d j ^ (1 / q) * eLpNorm (dilOp j T (SimpleCpt.diff ((2 : ℝ) ^ (-j) • h)
        (SimpleCpt.dil j u))) (.ofReal q) volume
      ≤ scaleVol d j ^ (1 / q) * (ENNReal.ofReal (B * ‖(2 : ℝ) ^ (-j) • h‖ ^ ε) *
          ((scaleVol d j)⁻¹ ^ (1 / p) * eLpNorm u (.ofReal p) volume)) := by
        gcongr
        rw [← eLpNorm_dil j u hp]
        exact hreg _ _ hh'
    _ = _ := by
        rw [norm_two_zpow_smul, ENNReal.inv_rpow, ← ENNReal.rpow_neg, sub_eq_add_neg,
          ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j)]
        ring

/-- Change of variables for the pairing: `⟨T u, g⟩ = 2^{jd} ⟨(Dil_{2^j} T)(Dil_{2^j} u),
Dil_{2^j} g⟩`. -/
theorem pairing_op_eq_dilOp (T : Op d 𝕜 B₁ B₂) (j : ℤ) (u : SimpleCpt d 𝕜 B₁)
    (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) :
    pairing (T u) g = (scaleVol d j).toReal •
      pairing (dilOp j T (SimpleCpt.dil j u)) (SimpleCpt.dil j g) := by
  unfold pairing
  have h := Measure.integral_comp_smul (μ := (volume : Measure (Rd d)))
    (fun y => g y (T u y)) ((2 : ℝ) ^ j)
  have hfun : (fun x : Rd d => g ((2 : ℝ) ^ j • x) (T u ((2 : ℝ) ^ j • x))) =
      fun x => (SimpleCpt.dil j g) x ((dilOp j T (SimpleCpt.dil j u)) x) := by
    funext x
    simp only [dilOp, SimpleCpt.dil_neg_dil, SimpleCpt.dil_apply]
  simp only [hfun, finrank_rd] at h
  rw [h, smul_smul]
  have : (scaleVol d j).toReal * |(((2 : ℝ) ^ j) ^ d)⁻¹| = 1 := by
    rw [scaleVol, ENNReal.toReal_ofReal (by positivity), abs_of_pos (by positivity),
      mul_inv_cancel₀ (by positivity)]
  rw [this, one_smul]

/-- Rescaled dual regularity: `|⟨T_j u, Δ_h g⟩| ≤ B (|h| 2^{-j})^ε 2^{-jd(1/p-1/q)} ‖u‖_p ‖g‖_{q'}`
for `|h| ≤ 2^j`. -/
theorem enorm_pairing_op_diff_le {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q ε B : ℝ} (hp : 0 < p)
    (hq : 1 < q)
    (hreg : ∀ f (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) (h : Rd d), ‖h‖ ≤ 1 →
      ENNReal.ofReal ‖pairing (dilOp j T f) (SimpleCpt.diff h g)‖ ≤
        ENNReal.ofReal (B * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume *
          eLpNorm g (.ofReal q.conjExponent) volume)
    (u : SimpleCpt d 𝕜 B₁) (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) (h : Rd d)
    (hh : ‖h‖ ≤ 2 ^ j) :
    ‖pairing (T u) (SimpleCpt.diff h g)‖ₑ ≤
      ENNReal.ofReal (B * (‖h‖ / 2 ^ j) ^ ε) * scaleVol d j ^ (1 / q - 1 / p) *
        eLpNorm u (.ofReal p) volume * eLpNorm g (.ofReal q.conjExponent) volume := by
  have hpq := Real.HolderConjugate.conjExponent hq
  have hh' : ‖(2 : ℝ) ^ (-j) • h‖ ≤ 1 := by
    rw [norm_two_zpow_smul, div_le_one (by positivity)]
    exact hh
  rw [pairing_op_eq_dilOp, SimpleCpt.dil_diff, enorm_smul,
    Real.enorm_eq_ofReal ENNReal.toReal_nonneg,
    ENNReal.ofReal_toReal (scaleVol_ne_top j)]
  have h1 := hreg (SimpleCpt.dil j u) (SimpleCpt.dil j g) _ hh'
  rw [ofReal_norm, eLpNorm_dil j u hp, eLpNorm_dil j g hpq.symm.pos, norm_two_zpow_smul] at h1
  calc scaleVol d j * ‖pairing (dilOp j T (SimpleCpt.dil j u))
        (SimpleCpt.diff ((2 : ℝ) ^ (-j) • h) (SimpleCpt.dil j g))‖ₑ
      ≤ scaleVol d j * (ENNReal.ofReal (B * (‖h‖ / 2 ^ j) ^ ε) *
          ((scaleVol d j)⁻¹ ^ (1 / p) * eLpNorm u (.ofReal p) volume) *
          ((scaleVol d j)⁻¹ ^ (1 / q.conjExponent) *
            eLpNorm g (.ofReal q.conjExponent) volume)) := by gcongr
    _ = ENNReal.ofReal (B * (‖h‖ / 2 ^ j) ^ ε) *
          (scaleVol d j ^ (1 : ℝ) * scaleVol d j ^ (-(1 / p)) *
            scaleVol d j ^ (-(1 / q.conjExponent))) *
          eLpNorm u (.ofReal p) volume * eLpNorm g (.ofReal q.conjExponent) volume := by
        rw [ENNReal.rpow_one, ENNReal.inv_rpow, ENNReal.inv_rpow, ← ENNReal.rpow_neg,
          ← ENNReal.rpow_neg]
        ring
    _ = _ := by
        rw [← ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j),
          ← ENNReal.rpow_add _ _ (scaleVol_ne_zero j) (scaleVol_ne_top j)]
        have : (1 : ℝ) + -(1 / p) + -(1 / q.conjExponent) = 1 / q - 1 / p := by
          have := hpq.inv_add_inv_eq_one
          simp only [one_div] at this ⊢
          linarith
        rw [this]

end RescaledRegularity

/-! ### Corollary 3.4(ii): (Tjrega) and (Tjregb) on the prototype lattice -/

/-- The constant `K(d, ε) = (2^d d^{ε/2} + 2 d^{ε/2}) / (1 - 2^{-ε})` in (Tjrega), (Tjregb). -/
noncomputable def Kreg (d : ℕ) (ε : ℝ) : ℝ :=
  (2 ^ d * Real.sqrt d ^ ε + 2 * Real.sqrt d ^ ε) / (1 - (2 : ℝ) ^ (-ε))

theorem Kreg_nonneg (d : ℕ) {ε : ℝ} (hε : 0 < ε) : 0 ≤ Kreg d ε := by
  unfold Kreg
  have : (2 : ℝ) ^ (-ε) < 1 := Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)
  have h1 : 0 ≤ Real.sqrt d ^ ε := Real.rpow_nonneg (Real.sqrt_nonneg _) _
  exact div_nonneg (by positivity) (by linarith)

/-- The per-level constant: both the regularity bound and the trivial bound at level `m` are at
most `(2^d + 2) d^{ε/2} (B + A₀) 2^{ε(m - j)}`. -/
theorem level_bounds {ε B A₀ : ℝ} (hε : 0 < ε) (hB : 0 ≤ B) (hA₀ : 0 ≤ A₀) (m j : ℤ) :
    (Real.sqrt d * (2 : ℝ) ^ (m - 1) ≤ 2 ^ j →
      2 ^ d * (B * (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε) ≤
        (2 ^ d * Real.sqrt d ^ ε + 2 * Real.sqrt d ^ ε) * (B + A₀) * (2 : ℝ) ^ (ε * (m - j))) ∧
    (2 ^ j < Real.sqrt d * (2 : ℝ) ^ (m - 1) →
      2 * A₀ ≤
        (2 ^ d * Real.sqrt d ^ ε + 2 * Real.sqrt d ^ ε) * (B + A₀) * (2 : ℝ) ^ (ε * (m - j))) := by
  have hsq := Real.sqrt_nonneg (d : ℝ)
  have hx : Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j =
      Real.sqrt d * (2 : ℝ) ^ ((m - 1 - j : ℤ) : ℝ) := by
    rw [mul_div_assoc, Real.rpow_intCast, zpow_sub₀ (two_ne_zero' ℝ) (m - 1) j]
  have hxe : (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε =
      Real.sqrt d ^ ε * (2 : ℝ) ^ (ε * ((m - 1 - j : ℤ) : ℝ)) := by
    rw [hx, Real.mul_rpow hsq (by positivity), ← Real.rpow_mul (by norm_num), mul_comm _ ε]
  have hmono : (2 : ℝ) ^ (ε * ((m - 1 - j : ℤ) : ℝ)) ≤ (2 : ℝ) ^ (ε * (m - j)) := by
    apply Real.rpow_le_rpow_of_exponent_le (by norm_num)
    push_cast
    nlinarith
  have h2pos : 0 < (2 : ℝ) ^ (ε * (m - j)) := by positivity
  have hsqe : 0 ≤ Real.sqrt d ^ ε := Real.rpow_nonneg hsq _
  constructor
  · intro _
    rw [hxe]
    have h3 : 0 ≤ (2 : ℝ) ^ (ε * ((m - 1 - j : ℤ) : ℝ)) := by positivity
    have : B * (Real.sqrt d ^ ε * (2 : ℝ) ^ (ε * ((m - 1 - j : ℤ) : ℝ))) ≤
        Real.sqrt d ^ ε * B * (2 : ℝ) ^ (ε * (m - j)) := by
      rw [← mul_assoc, mul_comm B, mul_assoc]
      exact mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left hmono hB) hsqe |>.trans
        (by ring_nf; rfl)
    calc 2 ^ d * (B * (Real.sqrt d ^ ε * (2 : ℝ) ^ (ε * ((m - 1 - j : ℤ) : ℝ))))
        ≤ 2 ^ d * (Real.sqrt d ^ ε * B * (2 : ℝ) ^ (ε * (m - j))) := by gcongr
      _ ≤ _ := by nlinarith [mul_nonneg hsqe h2pos.le, mul_nonneg (mul_nonneg hsqe hA₀) h2pos.le,
          mul_nonneg (mul_nonneg hsqe hB) h2pos.le, pow_pos (two_pos (α := ℝ)) d]
  · intro hbad
    have hx1 : 1 ≤ (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε :=
      Real.one_le_rpow (by rw [le_div_iff₀ (by positivity), one_mul]; exact hbad.le) hε.le
    rw [hxe] at hx1
    have h4 : 1 ≤ Real.sqrt d ^ ε * (2 : ℝ) ^ (ε * (m - j)) :=
      hx1.trans (mul_le_mul_of_nonneg_left hmono hsqe)
    nlinarith [mul_nonneg (mul_nonneg hsqe hB) h2pos.le, pow_pos (two_pos (α := ℝ)) d,
      mul_nonneg hsqe h2pos.le, mul_nonneg (mul_nonneg hsqe hA₀) h2pos.le]

section Tjreg

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]
  [NormedSpace ℝ B] [IsScalarTower ℝ 𝕜 B] [CompleteSpace B]

/-- **Corollary 3.4(ii) for subadditive functionals** on the prototype lattice `𝔔`: if
`Φ ≤ A₀ M ‖·‖_r` and `Φ ∘ Δ_h ≤ B (|h| 2^{-j})^ε M ‖·‖_r` for `|h| ≤ 2^j`, then
`Φ((I - 𝔼_{j-s}) u) ≤ K(d,ε) (B + A₀) 2^{-εs} M ‖u‖_r`. -/
theorem IsSubadditiveFun.le_proto {Φ : SimpleCpt d 𝕜 B → ℝ≥0∞} (hΦ : IsSubadditiveFun Φ)
    {r : ℝ} (hr : 1 ≤ r) {M : ℝ≥0∞} (hM : M ≠ ∞) {ε A₀ Bc : ℝ} (hε : 0 < ε) (hA₀ : 0 ≤ A₀)
    (hB : 0 ≤ Bc) (j : ℤ)
    (hbdd : ∀ u, Φ u ≤ ENNReal.ofReal A₀ * M * eLpNorm u (.ofReal r) volume)
    (hreg : ∀ u (h : Rd d), ‖h‖ ≤ 2 ^ j →
      Φ (SimpleCpt.diff h u) ≤ ENNReal.ofReal (Bc * (‖h‖ / 2 ^ j) ^ ε) * M *
        eLpNorm u (.ofReal r) volume)
    (s : ℕ) (u : SimpleCpt d 𝕜 B) :
    Φ (u - condExp (protoGrid d) (j - s) u) ≤
      ENNReal.ofReal (Kreg d ε * (Bc + A₀) * (2 : ℝ) ^ (-ε * s)) * M *
        eLpNorm u (.ofReal r) volume := by
  set G := protoGrid d
  set K' := 2 ^ d * Real.sqrt d ^ ε + 2 * Real.sqrt d ^ ε with hK'
  have hK'nn : 0 ≤ K' := by have := Real.rpow_nonneg (Real.sqrt_nonneg (d : ℝ)) ε; positivity
  set c : ℕ → ℝ := fun k => K' * (Bc + A₀) * (2 : ℝ) ^ (ε * (((j - s - k : ℤ)) - j)) with hc
  have hc_nn : ∀ k, 0 ≤ c k := fun k => by simp only [hc]; positivity
  have hsideG : ∀ m : ℤ, G.side (m - 1) = (2 : ℝ) ^ (m - 1) := fun m => by
    simp [G, protoGrid, GridData.side]
  -- per-level bounds
  have ha : ∀ (k : ℕ) u, Φ (condExp G (j - s - k - 1) u - condExp G (j - s - k) u) ≤
      (ENNReal.ofReal (c k) * M) * eLpNorm u (.ofReal r) volume := by
    intro k u
    set m : ℤ := j - s - k with hm
    obtain ⟨hgood, hbad⟩ := level_bounds (d := d) hε hB hA₀ m j
    by_cases hmj : Real.sqrt d * (2 : ℝ) ^ (m - 1) ≤ 2 ^ j
    · have h1 := hΦ.condExp_sub_le_of_diff G (m := m)
        (r := ENNReal.ofReal (Bc * (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε) * M) hr
        (fun v hv w hw u => by
          have hsh := G.norm_shift_le m hv hw
          rw [hsideG] at hsh
          refine (hreg u _ (hsh.trans hmj)).trans ?_
          gcongr) u
      refine h1.trans ?_
      have key : ENNReal.ofReal (2 ^ d * (Bc * (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε)) ≤
          ENNReal.ofReal (c k) :=
        ENNReal.ofReal_le_ofReal ((hgood hmj).trans (le_of_eq (by simp [hc, hm, hK'])))
      rw [ENNReal.ofReal_mul (by positivity), ENNReal.ofReal_pow (by norm_num),
        ENNReal.ofReal_ofNat] at key
      calc 2 ^ d * (ENNReal.ofReal (Bc * (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε) * M) *
            eLpNorm u (.ofReal r) volume
          = (2 ^ d * ENNReal.ofReal (Bc * (Real.sqrt d * (2 : ℝ) ^ (m - 1) / 2 ^ j) ^ ε)) * M *
            eLpNorm u (.ofReal r) volume := by ring
        _ ≤ ENNReal.ofReal (c k) * M * eLpNorm u (.ofReal r) volume := by gcongr
    · have h1 := hΦ.condExp_sub_le_of_bdd G hr hbdd m u
      refine h1.trans ?_
      have key : ENNReal.ofReal (2 * A₀) ≤ ENNReal.ofReal (c k) :=
        ENNReal.ofReal_le_ofReal ((hbad (not_le.1 hmj)).trans (le_of_eq (by simp [hc, hm, hK'])))
      rw [ENNReal.ofReal_mul (by norm_num), ENNReal.ofReal_ofNat] at key
      calc 2 * (ENNReal.ofReal A₀ * M) * eLpNorm u (.ofReal r) volume
          = (2 * ENNReal.ofReal A₀) * M * eLpNorm u (.ofReal r) volume := by ring
        _ ≤ ENNReal.ofReal (c k) * M * eLpNorm u (.ofReal r) volume := by gcongr
  have hC₀ : ENNReal.ofReal A₀ * M ≠ ∞ := ENNReal.mul_ne_top ENNReal.ofReal_ne_top hM
  have hmain := hΦ.le_of_condExp_sub_le G hC₀ hr hbdd
    (j - s) (fun k => ENNReal.ofReal (c k) * M) ha u
  refine hmain.trans (le_of_eq ?_)
  congr 1
  rw [ENNReal.tsum_mul_right]
  congr 1
  -- the geometric sum
  have hr2 : (2 : ℝ) ^ (-ε) < 1 := Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)
  have hr2' : 0 ≤ (2 : ℝ) ^ (-ε) := by positivity
  have hck : ∀ k : ℕ, c k = K' * (Bc + A₀) * (2 : ℝ) ^ (-ε * s) * ((2 : ℝ) ^ (-ε)) ^ k := by
    intro k
    have e1 : (2 : ℝ) ^ (ε * (((j - s - k : ℤ) : ℝ) - j)) =
        (2 : ℝ) ^ (-ε * s) * ((2 : ℝ) ^ (-ε)) ^ k := by
      rw [← Real.rpow_natCast ((2 : ℝ) ^ (-ε)) k, ← Real.rpow_mul (by norm_num),
        ← Real.rpow_add (by norm_num)]
      congr 1
      push_cast
      ring
    simp only [hc, e1]
    ring
  have hcfun : c = fun k : ℕ => K' * (Bc + A₀) * (2 : ℝ) ^ (-ε * s) * ((2 : ℝ) ^ (-ε)) ^ k :=
    funext hck
  have hsum : Summable c := by
    rw [hcfun]
    exact (summable_geometric_of_lt_one hr2' hr2).mul_left _
  rw [← ENNReal.ofReal_tsum_of_nonneg hc_nn hsum]
  congr 1
  rw [hcfun, tsum_mul_left, tsum_geometric_of_lt_one hr2' hr2, Kreg, ← hK']
  field_simp

end Tjreg

section TjregOps

variable {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedSpace ℝ B₁] [IsScalarTower ℝ 𝕜 B₁] [CompleteSpace B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂] [CompleteSpace B₂]

omit [NormedSpace ℝ B₁] [IsScalarTower ℝ 𝕜 B₁] [CompleteSpace B₁] [CompleteSpace B₂] in
theorem isSubadditiveFun_eLpNorm_op (T : Op d 𝕜 B₁ B₂) {q : ℝ} (hq : 1 ≤ q) :
    IsSubadditiveFun (fun u : SimpleCpt d 𝕜 B₁ => eLpNorm (T u) (.ofReal q) volume) where
  add_le u v := by
    rw [map_add]
    exact eLpNorm_add_le (by simp; linarith)
  smul_eq c u := by
    rw [map_smul]
    exact eLpNorm_const_smul _ _ _ _

omit [CompleteSpace B₂] in
/-- **(Tjrega)** (BRS eq. (Tjrega), Corollary 3.4(ii)): on the prototype lattice,
`‖T_j (I - 𝔼_{j-s}) u‖_q ≤ K(d,ε) (B + A∘) 2^{-εs} 2^{-jd(1/p-1/q)} ‖u‖_p`
(with `B + A∘` in place of `B`, ErrorReport E7). -/
theorem tjrega {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q ε A₀ Bc : ℝ} (hp : 1 ≤ p) (hq : 1 ≤ q)
    (hε : 0 < ε) (hA₀ : 0 ≤ A₀) (hB : 0 ≤ Bc) (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (hss : ∀ f, eLpNorm (dilOp j T f) (.ofReal q) volume ≤
      ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume)
    (hreg : ∀ f (h : Rd d), ‖h‖ ≤ 1 →
      eLpNorm (dilOp j T (SimpleCpt.diff h f)) (.ofReal q) volume ≤
        ENNReal.ofReal (Bc * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume)
    (s : ℕ) (u : SimpleCpt d 𝕜 B₁) :
    eLpNorm (T (u - condExp (protoGrid d) (j - s) u)) (.ofReal q) volume ≤
      ENNReal.ofReal (Kreg d ε * (Bc + A₀) * (2 : ℝ) ^ (-ε * s)) *
        scaleVol d j ^ (1 / q - 1 / p) * eLpNorm u (.ofReal p) volume :=
  (isSubadditiveFun_eLpNorm_op T hq).le_proto hp
    (ENNReal.rpow_ne_top_of_ne_zero (scaleVol_ne_zero j) (scaleVol_ne_top j)) hε hA₀ hB j
    (fun u => eLpNorm_op_le_of_singleScale (by linarith) (by linarith) hmeas hss u)
    (fun u h hh => eLpNorm_op_diff_le (by linarith) (by linarith) hmeas hreg u h hh) s u

end TjregOps

/-! ### The pairing is linear in its second argument -/

section PairingLinear

variable {𝕜 : Type*} [RCLike 𝕜] {B : Type*} [NormedAddCommGroup B] [NormedSpace 𝕜 B]

theorem SimpleCpt.memLp (f : SimpleCpt d 𝕜 B) {p : ℝ≥0∞} (hp0 : p ≠ 0) (hptop : p ≠ ∞) :
    MemLp f p volume := by
  refine (SimpleFunc.memLp_iff hp0 hptop).2 fun y hy => ?_
  refine lt_of_le_of_lt (measure_mono fun x hx => subset_tsupport _ ?_)
    f.2.isCompact.measure_lt_top
  rw [mem_preimage, mem_singleton_iff] at hx
  change f x ≠ 0
  rw [show f x = (f : SimpleFunc (Rd d) B) x from rfl, hx]
  exact hy

theorem SimpleCpt.eLpNorm_lt_top (f : SimpleCpt d 𝕜 B) {p : ℝ} (hp : 0 < p) :
    eLpNorm f (.ofReal p) volume < ∞ :=
  (SimpleCpt.memLp f (by simpa using hp) ENNReal.ofReal_ne_top).eLpNorm_lt_top

variable {B₂ : Type*} [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

theorem aestronglyMeasurable_pairing_integrand {F : Rd d → B₂} {g : Rd d → StrongDual 𝕜 B₂}
    (hF : AEStronglyMeasurable F volume) (hg : AEStronglyMeasurable g volume) :
    AEStronglyMeasurable (fun x => g x (F x)) volume :=
  (isBoundedBilinearMap_apply (𝕜 := 𝕜) (E := B₂) (F := 𝕜)).continuous.comp_aestronglyMeasurable
    (hg.prodMk hF)

theorem integrable_pairing_integrand {F : Rd d → B₂} (hF : AEStronglyMeasurable F volume)
    {q : ℝ} (hq : 1 < q) (hFq : eLpNorm F (.ofReal q) volume < ∞)
    (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) : Integrable (fun x => g x (F x)) volume := by
  have hpq := Real.HolderConjugate.conjExponent hq
  refine ⟨aestronglyMeasurable_pairing_integrand hF (SimpleCpt.aestronglyMeasurable g), ?_⟩
  have hq0 : ENNReal.ofReal q ≠ 0 := by simpa using hpq.pos
  have hq'0 : ENNReal.ofReal q.conjExponent ≠ 0 := by simpa using hpq.symm.pos
  have hH : ∫⁻ x, ‖g x (F x)‖ₑ ≤
      eLpNorm F (.ofReal q) volume * eLpNorm g (.ofReal q.conjExponent) volume := by
    rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hq0 ENNReal.ofReal_ne_top hF,
      eLpNorm_eq_lintegral_rpow_enorm_toReal hq'0 ENNReal.ofReal_ne_top
        (SimpleCpt.aestronglyMeasurable g),
      ENNReal.toReal_ofReal hpq.pos.le, ENNReal.toReal_ofReal hpq.symm.pos.le]
    calc ∫⁻ x, ‖g x (F x)‖ₑ ≤ ∫⁻ x, ‖F x‖ₑ * ‖g x‖ₑ := by
          refine lintegral_mono fun x => ?_
          rw [mul_comm]
          exact (g x).le_opENorm (F x)
      _ ≤ _ := ENNReal.lintegral_mul_le_Lp_mul_Lq volume hpq hF.enorm
          (SimpleCpt.aestronglyMeasurable g).enorm
  exact lt_of_le_of_lt hH (ENNReal.mul_lt_top hFq (SimpleCpt.eLpNorm_lt_top g hpq.symm.pos))

theorem pairing_add {F : Rd d → B₂} (hF : AEStronglyMeasurable F volume) {q : ℝ} (hq : 1 < q)
    (hFq : eLpNorm F (.ofReal q) volume < ∞) (g₁ g₂ : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) :
    pairing F (g₁ + g₂) = pairing F g₁ + pairing F g₂ := by
  unfold pairing
  rw [← integral_add (integrable_pairing_integrand hF hq hFq g₁)
    (integrable_pairing_integrand hF hq hFq g₂)]
  congr 1

theorem pairing_smul (F : Rd d → B₂) (c : 𝕜) (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) :
    pairing F (c • g) = c * pairing F g := by
  unfold pairing
  rw [← integral_const_mul]
  congr 1

end PairingLinear

section TjregDual

variable {𝕜 : Type*} [RCLike 𝕜] {B₁ B₂ : Type*} [NormedAddCommGroup B₁] [NormedSpace 𝕜 B₁]
  [NormedAddCommGroup B₂] [NormedSpace 𝕜 B₂]

/-- **(Tjregb)** (BRS eq. (Tjregb), Corollary 3.4(ii) for the adjoint, in dual form): on the
prototype lattice, `|⟨T_j f, (I - 𝔼_{j-s}) g⟩| ≤ K(d,ε) (B + A∘) 2^{-εs} 2^{-jd(1/p-1/q)}
‖f‖_p ‖g‖_{q'}` (with `B + A∘` in place of `B`, ErrorReport E7). -/
theorem tjregb {T : Op d 𝕜 B₁ B₂} {j : ℤ} {p q ε A₀ Bc : ℝ} (hp : 1 ≤ p) (hq : 1 < q)
    (hε : 0 < ε) (hA₀ : 0 ≤ A₀) (hB : 0 ≤ Bc) (hmeas : ∀ f, AEStronglyMeasurable (T f) volume)
    (hss : ∀ f, eLpNorm (dilOp j T f) (.ofReal q) volume ≤
      ENNReal.ofReal A₀ * eLpNorm f (.ofReal p) volume)
    (hreg : ∀ f (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) (h : Rd d), ‖h‖ ≤ 1 →
      ENNReal.ofReal ‖pairing (dilOp j T f) (SimpleCpt.diff h g)‖ ≤
        ENNReal.ofReal (Bc * ‖h‖ ^ ε) * eLpNorm f (.ofReal p) volume *
          eLpNorm g (.ofReal q.conjExponent) volume)
    (f : SimpleCpt d 𝕜 B₁) (s : ℕ) (g : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂)) :
    ‖pairing (T f) (g - condExp (protoGrid d) (j - s) g)‖ₑ ≤
      ENNReal.ofReal (Kreg d ε * (Bc + A₀) * (2 : ℝ) ^ (-ε * s)) *
        (scaleVol d j ^ (1 / q - 1 / p) * eLpNorm f (.ofReal p) volume) *
          eLpNorm g (.ofReal q.conjExponent) volume := by
  have hpq := Real.HolderConjugate.conjExponent hq
  have hTf := eLpNorm_op_le_of_singleScale (by linarith) (by linarith) hmeas hss f
  have hσ : scaleVol d j ^ (1 / q - 1 / p) ≠ ∞ :=
    ENNReal.rpow_ne_top_of_ne_zero (scaleVol_ne_zero j) (scaleVol_ne_top j)
  have hTfq : eLpNorm (T f) (.ofReal q) volume < ∞ :=
    lt_of_le_of_lt hTf (ENNReal.mul_lt_top (ENNReal.mul_lt_top ENNReal.ofReal_lt_top hσ.lt_top)
      (SimpleCpt.eLpNorm_lt_top f (by linarith)))
  have hΦ : IsSubadditiveFun
      (fun u : SimpleCpt d 𝕜 (StrongDual 𝕜 B₂) => ‖pairing (T f) u‖ₑ) :=
    ⟨fun u v => by
      rw [pairing_add (hmeas f) hq hTfq]
      exact enorm_add_le _ _,
    fun c u => by
      rw [pairing_smul, enorm_mul]⟩
  refine hΦ.le_proto hpq.symm.lt.le
    (ENNReal.mul_ne_top hσ (SimpleCpt.eLpNorm_lt_top f (by linarith)).ne)
    hε hA₀ hB j (fun u => ?_) (fun u h hh => ?_) s g
  · calc ‖pairing (T f) u‖ₑ ≤ eLpNorm (T f) (.ofReal q) volume *
          eLpNorm u (.ofReal q.conjExponent) volume :=
        enorm_pairing_le (hmeas f) (SimpleCpt.aestronglyMeasurable u) hq
      _ ≤ _ := by
        rw [← mul_assoc]
        gcongr
  · refine (enorm_pairing_op_diff_le (by linarith) hq hreg f u h hh).trans (le_of_eq ?_)
    ring

end TjregDual

end Auto
