/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Sparse and Carleson families

This file was automatically generated by Claude.

Let `(α, μ)` be a measure space and let `𝒮` be a finite *laminar* family of nonempty measurable
sets of finite measure (any two members are nested or disjoint), e.g. a finite family of cubes of
a dyadic lattice. For `0 < η` the family is *`η`-sparse* if there are pairwise disjoint measurable
sets `E_Q ⊆ Q` with `μ(E_Q) ≥ η μ(Q)`, and for `Λ ≥ 1` it is *`Λ`-Carleson* if
`∑_{R ∈ 𝒮, R ⊆ Q} μ(R) ≤ Λ μ(Q)` for every `Q ∈ 𝒮`.

The **sparse–Carleson equivalence** (Lerner–Nazarov, Lemma 6.3) states that `η`-sparse families
are `η⁻¹`-Carleson and, if `μ` has the intermediate value property (every measurable `A` has
measurable subsets of every measure `t ≤ μ(A)`, as Lebesgue measure does), `Λ`-Carleson families
are `Λ⁻¹`-sparse. The **splitting lemma** (Lerner–Nazarov, Lemma 6.6) states that a `Λ`-Carleson
family is the union of `M` families, each `(1 + (Λ - 1)/M)`-Carleson; here the families are the
classes of the *depth* (number of strictly larger members) modulo `M`.

Combining them, an `η`-sparse family splits into `M` families that are
`(1 + (η⁻¹ - 1)/M)⁻¹`-sparse, a sparseness constant that tends to `1` as `M → ∞`.

## Main results

* `Auto.IsSparseFamily.isCarlesonFamily`: sparse ⇒ Carleson.
* `Auto.IsCarlesonFamily.isSparseFamily`: Carleson ⇒ sparse.
* `Auto.IsCarlesonFamily.filter_depth_mod`: the splitting lemma.
* `Auto.IsSparseFamily.filter_depth_mod`: sparse families split into nearly `1`-sparse ones.

## References

* A. K. Lerner and F. Nazarov, *Intuitive dyadic calculus: the basics*, Expo. Math. 37 (2019),
  225–265, §6, Lemmas 6.3 and 6.6; arXiv:1508.05639.
* T. S. Hänninen, *Equivalence of sparse and Carleson coefficients for general sets*,
  Ark. Mat. 56 (2018), 333–339.
-/

@[expose] public section

open MeasureTheory Set Finset
open scoped ENNReal

namespace Auto

attribute [local instance] Classical.propDecidable

variable {α : Type*} [MeasurableSpace α]

/-- A finite family of sets is *laminar* if any two members are nested or disjoint. -/
def IsLaminar (𝒮 : Finset (Set α)) : Prop :=
  ∀ Q ∈ 𝒮, ∀ R ∈ 𝒮, Q ⊆ R ∨ R ⊆ Q ∨ Disjoint Q R

/-- A finite family `𝒮` is `η`-sparse if there are pairwise disjoint measurable sets
`E Q ⊆ Q` with `η μ(Q) ≤ μ(E Q)`. -/
def IsSparseFamily (μ : Measure α) (η : ℝ≥0∞) (𝒮 : Finset (Set α)) : Prop :=
  ∃ E : Set α → Set α, (∀ Q ∈ 𝒮, E Q ⊆ Q ∧ MeasurableSet (E Q) ∧ η * μ Q ≤ μ (E Q)) ∧
    (𝒮 : Set (Set α)).PairwiseDisjoint E

/-- A finite family `𝒮` is `Λ`-Carleson if `∑_{R ∈ 𝒮, R ⊆ Q} μ(R) ≤ Λ μ(Q)` for all `Q ∈ 𝒮`. -/
def IsCarlesonFamily (μ : Measure α) (Λ : ℝ≥0∞) (𝒮 : Finset (Set α)) : Prop :=
  ∀ Q ∈ 𝒮, ∑ R ∈ 𝒮 with R ⊆ Q, μ R ≤ Λ * μ Q

/-- The depth of `R` in `𝒮`: the number of members of `𝒮` strictly containing `R`. -/
noncomputable def depth (𝒮 : Finset (Set α)) (R : Set α) : ℕ :=
  #{P ∈ 𝒮 | R ⊂ P}

variable {μ : Measure α}

omit [MeasurableSpace α] in
theorem IsLaminar.subset {𝒮 𝒯 : Finset (Set α)} (h : IsLaminar 𝒮) (hT : 𝒯 ⊆ 𝒮) :
    IsLaminar 𝒯 := fun Q hQ R hR => h Q (hT hQ) R (hT hR)

theorem IsSparseFamily.mono {η η' : ℝ≥0∞} {𝒮 : Finset (Set α)} (h : IsSparseFamily μ η 𝒮)
    (hle : η' ≤ η) : IsSparseFamily μ η' 𝒮 := by
  obtain ⟨E, hE, hdisj⟩ := h
  exact ⟨E, fun Q hQ => ⟨(hE Q hQ).1, (hE Q hQ).2.1,
    (mul_le_mul_left hle _).trans (hE Q hQ).2.2⟩, hdisj⟩

/-- **Sparse families are Carleson** (Lerner–Nazarov, Lemma 6.3, easy direction). -/
theorem IsSparseFamily.isCarlesonFamily {η : ℝ≥0∞} {𝒮 : Finset (Set α)}
    (h : IsSparseFamily μ η 𝒮) (hη : η ≠ 0) (hηtop : η ≠ ∞) :
    IsCarlesonFamily μ η⁻¹ 𝒮 := by
  obtain ⟨E, hE, hdisj⟩ := h
  intro Q hQ
  have hdisj' : ((𝒮.filter (· ⊆ Q)) : Set (Set α)).PairwiseDisjoint E :=
    hdisj.subset fun x hx => (Finset.mem_filter.1 hx).1
  calc ∑ R ∈ 𝒮 with R ⊆ Q, μ R
      ≤ ∑ R ∈ 𝒮 with R ⊆ Q, η⁻¹ * μ (E R) := by
        refine Finset.sum_le_sum fun R hR => ?_
        have h1 := (hE R (Finset.mem_filter.1 hR).1).2.2
        calc μ R = η⁻¹ * (η * μ R) := by
              rw [← mul_assoc, ENNReal.inv_mul_cancel hη hηtop, one_mul]
          _ ≤ η⁻¹ * μ (E R) := by gcongr
    _ = η⁻¹ * μ (⋃ R ∈ 𝒮.filter (· ⊆ Q), E R) := by
        rw [← Finset.mul_sum, measure_biUnion_finset hdisj'
          (fun R hR => (hE R (Finset.mem_filter.1 hR).1).2.1)]
    _ ≤ η⁻¹ * μ Q := by
        gcongr
        refine iUnion₂_subset fun R hR => ?_
        exact (hE R (Finset.mem_filter.1 hR).1).1.trans (Finset.mem_filter.1 hR).2

theorem IsCarlesonFamily.subset {Λ : ℝ≥0∞} {𝒮 𝒯 : Finset (Set α)}
    (h : IsCarlesonFamily μ Λ 𝒮) (hT : 𝒯 ⊆ 𝒮) : IsCarlesonFamily μ Λ 𝒯 := by
  intro Q hQ
  refine le_trans ?_ (h Q (hT hQ))
  exact Finset.sum_le_sum_of_subset (Finset.filter_subset_filter _ hT)

/-- Exact-measure version of Carleson ⇒ sparse, proved by induction removing a maximal member. -/
theorem IsCarlesonFamily.exists_sparse_eq {Λ : ℝ≥0∞} (hΛ : 1 ≤ Λ) (hΛtop : Λ ≠ ∞)
    (hIVP : ∀ A, MeasurableSet A → ∀ t ≤ μ A, ∃ B ⊆ A, MeasurableSet B ∧ μ B = t) :
    ∀ (𝒮 : Finset (Set α)), IsLaminar 𝒮 → (∀ Q ∈ 𝒮, MeasurableSet Q) →
      (∀ Q ∈ 𝒮, μ Q ≠ ∞) → IsCarlesonFamily μ Λ 𝒮 →
      ∃ E : Set α → Set α, (∀ Q ∈ 𝒮, E Q ⊆ Q ∧ MeasurableSet (E Q) ∧ μ (E Q) = Λ⁻¹ * μ Q) ∧
        (𝒮 : Set (Set α)).PairwiseDisjoint E := by
  have hΛ0 : Λ ≠ 0 := (lt_of_lt_of_le one_pos hΛ).ne'
  intro 𝒮
  induction 𝒮 using Finset.strongInduction with
  | H 𝒮 ih =>
  intro hlam hmeas hfin hC
  rcases 𝒮.eq_empty_or_nonempty with rfl | hne
  · exact ⟨fun _ => ∅, by simp, by simp⟩
  obtain ⟨Q, hQ, hQmax⟩ := 𝒮.exists_maximal hne
  set 𝒮' := 𝒮.erase Q with h𝒮'
  have hsub : 𝒮' ⊆ 𝒮 := Finset.erase_subset _ _
  obtain ⟨E', hE', hdisj'⟩ := ih 𝒮' (Finset.erase_ssubset hQ)
    (fun A hA B hB => hlam A (hsub hA) B (hsub hB)) (fun A hA => hmeas A (hsub hA))
    (fun A hA => hfin A (hsub hA)) (hC.subset hsub)
  -- the available part of `Q`
  set avail := Q \ ⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R with havail
  have havail_meas : MeasurableSet avail :=
    (hmeas Q hQ).diff (Finset.measurableSet_biUnion _ fun R hR =>
      (hE' R (Finset.mem_filter.1 hR).1).2.1)
  set X := ∑ R ∈ 𝒮' with R ⊆ Q, μ R with hX
  have hsplit : ∑ R ∈ 𝒮 with R ⊆ Q, μ R = μ Q + X := by
    rw [hX, h𝒮', Finset.filter_erase,
      Finset.add_sum_erase _ _
        (Finset.mem_filter.2 ⟨hQ, subset_rfl⟩ : Q ∈ 𝒮.filter (· ⊆ Q))]
  have hXle : μ Q + X ≤ Λ * μ Q := hsplit ▸ hC Q hQ
  have hμQ := hfin Q hQ
  have hUnion : μ (⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R) ≤ Λ⁻¹ * X := by
    calc μ (⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R)
        ≤ ∑ R ∈ 𝒮' with R ⊆ Q, μ (E' R) := measure_biUnion_finset_le _ _
      _ = ∑ R ∈ 𝒮' with R ⊆ Q, Λ⁻¹ * μ R := by
          refine Finset.sum_congr rfl fun R hR => (hE' R (Finset.mem_filter.1 hR).1).2.2
      _ = Λ⁻¹ * X := by rw [Finset.mul_sum]
  have hQle : μ Q ≤ μ avail + Λ⁻¹ * X := by
    calc μ Q ≤ μ (avail ∪ ⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R) := by
          apply measure_mono
          intro x hx
          by_cases h : x ∈ ⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R
          · exact Or.inr h
          · exact Or.inl ⟨hx, h⟩
      _ ≤ μ avail + μ (⋃ R ∈ 𝒮'.filter (· ⊆ Q), E' R) := measure_union_le _ _
      _ ≤ μ avail + Λ⁻¹ * X := by gcongr
  have hXfin : X ≠ ∞ := by
    refine ne_top_of_le_ne_top (ENNReal.mul_ne_top hΛtop hμQ) ?_
    exact le_trans le_add_self hXle
  have hgoal : Λ⁻¹ * μ Q ≤ μ avail := by
    -- multiply `hQle` by `Λ`
    have h1 : Λ * μ Q ≤ Λ * μ avail + X := by
      calc Λ * μ Q ≤ Λ * (μ avail + Λ⁻¹ * X) := by gcongr
        _ = Λ * μ avail + X := by
            rw [mul_add, ← mul_assoc, ENNReal.mul_inv_cancel hΛ0 hΛtop, one_mul]
    have h2 : μ Q ≤ Λ * μ avail := by
      have h3 : μ Q + Λ * μ Q ≤ Λ * μ avail + Λ * μ Q :=
        calc μ Q + Λ * μ Q ≤ μ Q + (Λ * μ avail + X) := by gcongr
          _ = Λ * μ avail + (μ Q + X) := by ring
          _ ≤ Λ * μ avail + Λ * μ Q := by gcongr
      exact (ENNReal.add_le_add_iff_right (ENNReal.mul_ne_top hΛtop hμQ)).1 h3
    calc Λ⁻¹ * μ Q ≤ Λ⁻¹ * (Λ * μ avail) := by gcongr
      _ = μ avail := by rw [← mul_assoc, ENNReal.inv_mul_cancel hΛ0 hΛtop, one_mul]
  obtain ⟨EQ, hEQsub, hEQmeas, hEQμ⟩ := hIVP avail havail_meas _ hgoal
  refine ⟨fun R => if R = Q then EQ else E' R, ?_, ?_⟩
  · intro R hR
    by_cases hRQ : R = Q
    · subst hRQ
      simp only [↓reduceIte]
      exact ⟨hEQsub.trans sdiff_subset, hEQmeas, hEQμ⟩
    · simp only [hRQ, ↓reduceIte]
      exact hE' R (Finset.mem_erase.2 ⟨hRQ, hR⟩)
  · intro R hR R' hR' hne
    simp only [Function.onFun]
    -- disjointness of `EQ` from the old sets
    have key : ∀ R ∈ 𝒮, R ≠ Q → Disjoint EQ (E' R) := by
      intro R hR hRQ
      have hR'' : R ∈ 𝒮' := Finset.mem_erase.2 ⟨hRQ, hR⟩
      rcases hlam Q hQ R hR with hQR | hRQ' | hd
      · exact absurd (subset_antisymm (hQmax hR hQR) hQR) hRQ
      · refine Disjoint.mono_left hEQsub ?_
        refine Set.disjoint_left.2 fun x hx hxR => hx.2 ?_
        exact mem_iUnion₂.2 ⟨R, Finset.mem_filter.2 ⟨hR'', hRQ'⟩, hxR⟩
      · exact (hd.mono_left (hEQsub.trans sdiff_subset)).mono_right (hE' R hR'').1
    by_cases h1 : R = Q
    · subst h1
      have h2 : R' ≠ R := Ne.symm hne
      simp only [↓reduceIte, h2, ↓reduceIte]
      exact key R' hR' h2
    · by_cases h2 : R' = Q
      · subst h2
        simp only [h1, ↓reduceIte, ↓reduceIte]
        exact (key R hR h1).symm
      · simp only [h1, h2, ↓reduceIte]
        exact hdisj' (Finset.mem_erase.2 ⟨h1, hR⟩) (Finset.mem_erase.2 ⟨h2, hR'⟩) hne

/-- **Carleson families are sparse** (Lerner–Nazarov, Lemma 6.3): a finite laminar
`Λ`-Carleson family of measurable sets of finite measure is `Λ⁻¹`-sparse, provided `μ` has the
intermediate value property. -/
theorem IsCarlesonFamily.isSparseFamily {Λ : ℝ≥0∞} {𝒮 : Finset (Set α)}
    (h : IsCarlesonFamily μ Λ 𝒮) (hΛ : 1 ≤ Λ) (hΛtop : Λ ≠ ∞) (hlam : IsLaminar 𝒮)
    (hmeas : ∀ Q ∈ 𝒮, MeasurableSet Q) (hfin : ∀ Q ∈ 𝒮, μ Q ≠ ∞)
    (hIVP : ∀ A, MeasurableSet A → ∀ t ≤ μ A, ∃ B ⊆ A, MeasurableSet B ∧ μ B = t) :
    IsSparseFamily μ Λ⁻¹ 𝒮 := by
  obtain ⟨E, hE, hdisj⟩ := IsCarlesonFamily.exists_sparse_eq hΛ hΛtop hIVP 𝒮 hlam hmeas hfin h
  exact ⟨E, fun Q hQ => ⟨(hE Q hQ).1, (hE Q hQ).2.1, (hE Q hQ).2.2.ge⟩, hdisj⟩

section depth

variable {𝒮 : Finset (Set α)}

omit [MeasurableSpace α] in
theorem depth_lt_of_ssubset {R P : Set α} (hP : P ∈ 𝒮) (hRP : R ⊂ P) :
    depth 𝒮 P < depth 𝒮 R := by
  unfold depth
  apply Finset.card_lt_card
  refine ⟨fun X hX => ?_, fun hsub => ?_⟩
  · rw [Finset.mem_filter] at hX ⊢
    exact ⟨hX.1, hRP.trans hX.2⟩
  · have := hsub (Finset.mem_filter.2 ⟨hP, hRP⟩)
    exact (Finset.mem_filter.1 this).2.ne rfl

omit [MeasurableSpace α] in
theorem disjoint_of_depth_eq (hlam : IsLaminar 𝒮) {R R' : Set α} (hR : R ∈ 𝒮) (hR' : R' ∈ 𝒮)
    (hne : R ≠ R') (hd : depth 𝒮 R = depth 𝒮 R') : Disjoint R R' := by
  rcases hlam R hR R' hR' with h | h | h
  · exact absurd hd (depth_lt_of_ssubset hR' (lt_of_le_of_ne h hne)).ne'
  · exact absurd hd (depth_lt_of_ssubset hR (lt_of_le_of_ne h hne.symm)).ne
  · exact h

omit [MeasurableSpace α] in
/-- Every member strictly contained in another member has a *parent*: a smallest strictly
larger member, whose depth is one less. -/
theorem exists_parent (hlam : IsLaminar 𝒮) (hne : ∀ Q ∈ 𝒮, Q.Nonempty) {R Q : Set α}
    (hR : R ∈ 𝒮) (hQ : Q ∈ 𝒮) (hRQ : R ⊂ Q) :
    ∃ P ∈ 𝒮, R ⊂ P ∧ P ⊆ Q ∧ depth 𝒮 R = depth 𝒮 P + 1 := by
  set A := 𝒮.filter (R ⊂ ·) with hA
  have hAdef : ∀ X, X ∈ A ↔ X ∈ 𝒮 ∧ R ⊂ X := fun X => by rw [hA, Finset.mem_filter]
  have hAne : A.Nonempty := ⟨Q, (hAdef Q).2 ⟨hQ, hRQ⟩⟩
  obtain ⟨P, hPA, hPmin⟩ := A.exists_minimal hAne
  have hP := (hAdef P).1 hPA
  -- members strictly containing `R` are `P` or strictly contain `P`
  have hcomp : ∀ P' ∈ A, P' = P ∨ P ⊂ P' := by
    intro P' hP'A
    have hP' := (hAdef P').1 hP'A
    obtain ⟨x, hx⟩ := hne R hR
    rcases hlam P' hP'.1 P hP.1 with h | h | h
    · exact Or.inl (subset_antisymm h (hPmin hP'A h))
    · by_cases heq : P' = P
      · exact Or.inl heq
      · exact Or.inr (lt_of_le_of_ne h (Ne.symm heq))
    · exact absurd (hP.2.1 hx) (Set.disjoint_left.1 h (hP'.2.1 hx))
  refine ⟨P, hP.1, hP.2, ?_, ?_⟩
  · rcases hcomp Q ((hAdef Q).2 ⟨hQ, hRQ⟩) with h | h
    · exact h ▸ le_rfl
    · exact h.le
  · have : A = insert P (𝒮.filter (P ⊂ ·)) := by
      ext X
      rw [hAdef]
      simp only [Finset.mem_insert, Finset.mem_filter]
      constructor
      · intro hX
        rcases hcomp X ((hAdef X).2 hX) with h | h
        · exact Or.inl h
        · exact Or.inr ⟨hX.1, h⟩
      · rintro (rfl | ⟨hX, hPX⟩)
        · exact hP
        · exact ⟨hX, hP.2.trans hPX⟩
    unfold depth
    rw [show (𝒮.filter (R ⊂ ·)) = A from hA.symm, this, Finset.card_insert_of_notMem]
    simp

end depth

/-- Summation lemma for antitone sequences: `M ∑_{m < K} a((m+1)M) ≤ ∑_{1 ≤ t ≤ KM} a(t)`. -/
theorem mul_sum_antitone_le (a : ℕ → ℝ≥0∞) (ha : Antitone a) (M K : ℕ) :
    M * ∑ m ∈ range K, a ((m + 1) * M) ≤ ∑ t ∈ Finset.Ico 1 (K * M + 1), a t := by
  induction K with
  | zero => simp
  | succ K ih =>
    rw [Finset.sum_range_succ, mul_add,
      ← Finset.sum_Ico_consecutive _ (by nlinarith : 1 ≤ K * M + 1)
        (by nlinarith : K * M + 1 ≤ (K + 1) * M + 1)]
    gcongr
    calc (M : ℝ≥0∞) * a ((K + 1) * M)
        = ∑ _t ∈ Finset.Ico (K * M + 1) ((K + 1) * M + 1), a ((K + 1) * M) := by
          rw [Finset.sum_const, Nat.card_Ico, nsmul_eq_mul]
          congr 2
          ring_nf
          omega
      _ ≤ ∑ t ∈ Finset.Ico (K * M + 1) ((K + 1) * M + 1), a t := by
          refine Finset.sum_le_sum fun t ht => ha ?_
          have := (Finset.mem_Ico.1 ht).2
          omega

/-- **Splitting lemma** (Lerner–Nazarov, Lemma 6.6): if a finite laminar family of nonempty
measurable sets is `Λ`-Carleson and `0 < M`, then each class of members of equal depth modulo `M`
is `(1 + (Λ - 1)/M)`-Carleson. -/
theorem IsCarlesonFamily.filter_depth_mod {Λ : ℝ≥0∞} {𝒮 : Finset (Set α)}
    (h : IsCarlesonFamily μ Λ 𝒮) (hlam : IsLaminar 𝒮) (hne : ∀ Q ∈ 𝒮, Q.Nonempty)
    (hmeas : ∀ Q ∈ 𝒮, MeasurableSet Q) (hfin : ∀ Q ∈ 𝒮, μ Q ≠ ∞) {M : ℕ} (hM : 0 < M)
    (i : ℕ) :
    IsCarlesonFamily μ (1 + (Λ - 1) / M) (𝒮.filter fun R => depth 𝒮 R % M = i) := by
  intro Q hQ'
  obtain ⟨hQ, hQi⟩ := Finset.mem_filter.1 hQ'
  set dQ := depth 𝒮 Q
  -- the layers below `Q`
  let L : ℕ → Finset (Set α) := fun t => 𝒮.filter fun R => R ⊆ Q ∧ depth 𝒮 R = dQ + t
  let a : ℕ → ℝ≥0∞ := fun t => ∑ R ∈ L t, μ R
  have hdepth_ge : ∀ R ∈ 𝒮, R ⊆ Q → dQ ≤ depth 𝒮 R := by
    intro R hR hRQ
    by_cases h : R = Q
    · rw [h]
    · exact (depth_lt_of_ssubset hQ (lt_of_le_of_ne hRQ h)).le
  have ha0 : a 0 = μ Q := by
    have : L 0 = {Q} := by
      ext R
      simp only [L, Finset.mem_filter, Finset.mem_singleton, add_zero]
      constructor
      · rintro ⟨hR, hRQ, hd⟩
        by_contra h
        exact absurd hd (depth_lt_of_ssubset hQ (lt_of_le_of_ne hRQ h)).ne'
      · rintro rfl
        exact ⟨hQ, le_rfl, rfl⟩
    simp [a, this]
  -- the layers decrease
  have ha_succ : ∀ t, a (t + 1) ≤ a t := by
    intro t
    have hpar : ∀ R ∈ L (t + 1), ∃ P ∈ L t, R ⊆ P := by
      intro R hR
      simp only [L, Finset.mem_filter] at hR
      have hRQ : R ⊂ Q := lt_of_le_of_ne hR.2.1 (fun h => by
        rw [h] at hR; omega)
      obtain ⟨P, hP, hRP, hPQ, hd⟩ := exists_parent hlam hne hR.1 hQ hRQ
      exact ⟨P, Finset.mem_filter.2 ⟨hP, hPQ, by omega⟩, hRP.le⟩
    choose! par hparL hparsub using hpar
    calc a (t + 1) = ∑ P ∈ L t, ∑ R ∈ (L (t + 1)).filter (fun R => par R = P), μ R :=
          (Finset.sum_fiberwise_of_maps_to hparL _).symm
      _ ≤ ∑ P ∈ L t, μ P := by
          refine Finset.sum_le_sum fun P _ => ?_
          rw [← measure_biUnion_finset]
          · refine measure_mono (iUnion₂_subset fun R hR => ?_)
            have hR' := Finset.mem_filter.1 hR
            exact hR'.2 ▸ hparsub R hR'.1
          · intro R hR R' hR' hne'
            have h1 := Finset.mem_filter.1 (Finset.mem_filter.1 hR).1
            have h2 := Finset.mem_filter.1 (Finset.mem_filter.1 hR').1
            exact disjoint_of_depth_eq hlam h1.1 h2.1 hne' (h1.2.2.trans h2.2.2.symm)
          · intro R hR
            exact hmeas R (Finset.mem_filter.1 (Finset.mem_filter.1 hR).1).1
  have hanti : Antitone a := antitone_nat_of_succ_le ha_succ
  -- the total mass of the layers is controlled by the Carleson condition
  have htotal : ∀ N, ∑ t ∈ range N, a t ≤ Λ * μ Q := by
    intro N
    refine le_trans ?_ (h Q hQ)
    rw [← Finset.sum_biUnion]
    · refine Finset.sum_le_sum_of_subset fun R hR => ?_
      obtain ⟨t, _, hRt⟩ := Finset.mem_biUnion.1 hR
      have := Finset.mem_filter.1 hRt
      exact Finset.mem_filter.2 ⟨this.1, this.2.1⟩
    · intro t _ t' _ htt'
      simp only [Function.onFun]
      rw [Finset.disjoint_left]
      intro R hR hR'
      have h1 := (Finset.mem_filter.1 hR).2.2
      have h2 := (Finset.mem_filter.1 hR').2.2
      omega
  -- the members of the class below `Q` are the layers at multiples of `M`
  set N := #𝒮 + 1
  have hdepth_le : ∀ R ∈ 𝒮, depth 𝒮 R < N := fun R _ =>
    Nat.lt_succ_of_le (Finset.card_filter_le _ _)
  have hclass : (𝒮.filter fun R => depth 𝒮 R % M = i).filter (· ⊆ Q) =
      (range N).biUnion fun m => L (m * M) := by
    ext R
    simp only [Finset.mem_filter, Finset.mem_biUnion, Finset.mem_range, L]
    constructor
    · rintro ⟨⟨hR, hRi⟩, hRQ⟩
      have hge := hdepth_ge R hR hRQ
      have hlt := hdepth_le R hR
      refine ⟨(depth 𝒮 R - dQ) / M, ?_, hR, hRQ, ?_⟩
      · exact lt_of_le_of_lt (Nat.div_le_self _ _) (by omega)
      · have hmod : (depth 𝒮 R - dQ) % M = 0 := by
          have := Nat.sub_mod_eq_zero_of_mod_eq (hRi.trans hQi.symm)
          exact this
        have := Nat.div_mul_cancel (Nat.dvd_of_mod_eq_zero hmod)
        omega
    · rintro ⟨m, _, hR, hRQ, hd⟩
      refine ⟨⟨hR, ?_⟩, hRQ⟩
      rw [hd, ← hQi, Nat.add_mul_mod_self_right]
  have hdisjL : ∀ m ∈ range N, ∀ m' ∈ range N, m ≠ m' →
      Disjoint (L (m * M)) (L (m' * M)) := by
    intro m _ m' _ hmm'
    rw [Finset.disjoint_left]
    intro R hR hR'
    have h1 := (Finset.mem_filter.1 hR).2.2
    have h2 := (Finset.mem_filter.1 hR').2.2
    have : m * M = m' * M := by omega
    exact hmm' (Nat.eq_of_mul_eq_mul_right hM this)
  rw [hclass, Finset.sum_biUnion hdisjL]
  -- conclude
  have hsum_split : ∑ m ∈ range N, a (m * M) = a 0 + ∑ m ∈ range (N - 1), a ((m + 1) * M) := by
    have : N = (N - 1) + 1 := by omega
    rw [this, Finset.sum_range_succ', zero_mul, add_comm]
    simp
  change ∑ m ∈ range N, a (m * M) ≤ _
  rw [hsum_split, ha0]
  have hμQ := hfin Q hQ
  have hkey : (M : ℝ≥0∞) * ∑ m ∈ range (N - 1), a ((m + 1) * M) ≤ (Λ - 1) * μ Q := by
    refine (mul_sum_antitone_le a hanti M (N - 1)).trans ?_
    have h1 := htotal ((N - 1) * M + 1)
    rw [Finset.sum_range_succ', ha0, add_comm] at h1
    have h2 : ∑ t ∈ Finset.Ico 1 ((N - 1) * M + 1), a t =
        ∑ k ∈ range ((N - 1) * M), a (k + 1) := by
      rw [Finset.sum_Ico_eq_sum_range]
      simp [add_comm]
    rw [h2, ENNReal.sub_mul (fun _ _ => hμQ), one_mul]
    exact ENNReal.le_sub_of_add_le_left hμQ h1
  have hMne : (M : ℝ≥0∞) ≠ 0 := by exact_mod_cast hM.ne'
  calc μ Q + ∑ m ∈ range (N - 1), a ((m + 1) * M)
      ≤ μ Q + (Λ - 1) * μ Q / M := by
        gcongr
        rw [ENNReal.le_div_iff_mul_le (Or.inl hMne) (Or.inl (ENNReal.natCast_ne_top M)),
          mul_comm]
        exact hkey
    _ = (1 + (Λ - 1) / M) * μ Q := by
        rw [add_mul, one_mul, ENNReal.div_eq_inv_mul, ENNReal.div_eq_inv_mul, mul_assoc]

/-- **Sparse families split into nearly `1`-sparse families**: a finite laminar `η`-sparse
family of nonempty measurable sets of finite measure (for a measure with the intermediate value
property) is, for every `M > 0`, the union of the `M` depth classes modulo `M`, each of which is
`(1 + (η⁻¹ - 1)/M)⁻¹`-sparse. -/
theorem IsSparseFamily.filter_depth_mod {η : ℝ≥0∞} {𝒮 : Finset (Set α)}
    (h : IsSparseFamily μ η 𝒮) (hη : η ≠ 0) (hη1 : η ≤ 1) (hlam : IsLaminar 𝒮)
    (hne : ∀ Q ∈ 𝒮, Q.Nonempty) (hmeas : ∀ Q ∈ 𝒮, MeasurableSet Q) (hfin : ∀ Q ∈ 𝒮, μ Q ≠ ∞)
    (hIVP : ∀ A, MeasurableSet A → ∀ t ≤ μ A, ∃ B ⊆ A, MeasurableSet B ∧ μ B = t)
    {M : ℕ} (hM : 0 < M) (i : ℕ) :
    IsSparseFamily μ (1 + (η⁻¹ - 1) / M)⁻¹ (𝒮.filter fun R => depth 𝒮 R % M = i) := by
  have hηtop : η ≠ ∞ := ne_top_of_le_ne_top ENNReal.one_ne_top hη1
  have hC := (h.isCarlesonFamily hη hηtop).filter_depth_mod hlam hne hmeas hfin hM i
  refine hC.isSparseFamily le_self_add ?_ (hlam.subset (Finset.filter_subset _ _))
    (fun Q hQ => hmeas Q (Finset.mem_filter.1 hQ).1) (fun Q hQ => hfin Q (Finset.mem_filter.1 hQ).1)
    hIVP
  refine ENNReal.add_ne_top.2 ⟨ENNReal.one_ne_top, ?_⟩
  refine ENNReal.div_ne_top ?_ (by exact_mod_cast hM.ne')
  exact ne_top_of_le_ne_top (ENNReal.inv_ne_top.2 hη) tsub_le_self

end Auto
