/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# The Whitney decomposition

This file was automatically generated by Claude.

Let `X` be a metric space and let `(P k)_{k ∈ ℤ}` be a *nested sequence of partitions* of `X`:
each `P k` is a partition of `X` into cells, every cell of `P (k+1)` is contained in a cell of
`P k`, and cells of `P k` have diameter at most `δ 2^{-k}`. The prototype is the family of dyadic
cubes of side length `2^{-k}` in `ℝ^d` (with `δ = √d`), or any dyadic lattice in the sense of
Lerner–Nazarov.

The **Whitney decomposition theorem** states that every open set `Ω` with nonempty complement is
the disjoint union of cells `W` (the *Whitney cells*) whose distance to `Ωᶜ` is comparable to
their size. Precisely, for every `a > 0` there is a family `𝒲` of pairwise disjoint cells covering
`Ω` such that each `W ∈ 𝒲` belongs to some `P k` and
`a δ 2^{-k} ≤ dist(y, z)` for all `y ∈ W`, `z ∉ Ω`, while `dist(y, z) < (2a + 2) δ 2^{-k}` for
some `y ∈ W`, `z ∉ Ω`.

The Whitney cells are the maximal cells `Q` of `P k` with `dist(Q, Ωᶜ) ≥ a δ 2^{-k}`.
With `a = 5` and dyadic cubes this gives `5 diam W ≤ dist(W, Ωᶜ) ≤ 12 diam W`.

## Main results

* `Auto.IsNestedPartition`: nested sequences of partitions with geometric diameter bounds.
* `Auto.exists_whitney_decomposition`: the Whitney decomposition.

## References

* E. M. Stein, *Singular integrals and differentiability properties of functions*,
  Princeton Univ. Press, 1970, Chapter VI, §1, Theorem 1 (VI.1.1) and its proof (VI.1.2).
* L. Grafakos, *Modern Fourier Analysis*, 3rd ed., GTM 250, Springer, 2014, Appendix J.
-/

@[expose] public section

open Set Metric

namespace Auto

variable {X : Type*} [MetricSpace X]

/-- A nested sequence of partitions `(P k)_{k ∈ ℤ}` of `X` whose cells at scale `k` have
diameter at most `δ * 2 ^ (-k)`. -/
structure IsNestedPartition (P : ℤ → Set (Set X)) (δ : ℝ) : Prop where
  /-- every point lies in a cell of every scale -/
  cover : ∀ k x, ∃ Q ∈ P k, x ∈ Q
  /-- cells of the same scale are disjoint or equal -/
  eq_of_nonempty_inter : ∀ k, ∀ Q ∈ P k, ∀ Q' ∈ P k, (Q ∩ Q').Nonempty → Q = Q'
  /-- every cell is contained in a cell of the next coarser scale -/
  nest : ∀ k, ∀ Q ∈ P (k + 1), ∃ Q' ∈ P k, Q ⊆ Q'
  /-- cells at scale `k` have diameter at most `δ * 2 ^ (-k)` -/
  dist_le : ∀ k, ∀ Q ∈ P k, ∀ x ∈ Q, ∀ y ∈ Q, dist x y ≤ δ * (2 : ℝ) ^ (-k)

namespace IsNestedPartition

variable {P : ℤ → Set (Set X)} {δ : ℝ}

/-- The cell of scale `k` containing `x`. -/
noncomputable def cell (hP : IsNestedPartition P δ) (k : ℤ) (x : X) : Set X :=
  Classical.choose (hP.cover k x)

theorem cell_mem (hP : IsNestedPartition P δ) (k : ℤ) (x : X) : hP.cell k x ∈ P k :=
  (Classical.choose_spec (hP.cover k x)).1

theorem mem_cell (hP : IsNestedPartition P δ) (k : ℤ) (x : X) : x ∈ hP.cell k x :=
  (Classical.choose_spec (hP.cover k x)).2

theorem eq_cell (hP : IsNestedPartition P δ) {k : ℤ} {Q : Set X} (hQ : Q ∈ P k) {x : X}
    (hx : x ∈ Q) : Q = hP.cell k x :=
  hP.eq_of_nonempty_inter k Q hQ _ (hP.cell_mem k x) ⟨x, hx, hP.mem_cell k x⟩

theorem cell_eq_of_mem (hP : IsNestedPartition P δ) {k : ℤ} {x y : X}
    (hy : y ∈ hP.cell k x) : hP.cell k y = hP.cell k x :=
  (hP.eq_cell (hP.cell_mem k x) hy).symm

theorem cell_succ_subset (hP : IsNestedPartition P δ) (k : ℤ) (x : X) :
    hP.cell (k + 1) x ⊆ hP.cell k x := by
  obtain ⟨Q', hQ', hsub⟩ := hP.nest k _ (hP.cell_mem (k + 1) x)
  rw [hP.eq_cell hQ' (hsub (hP.mem_cell (k + 1) x))] at hsub
  exact hsub

theorem cell_subset_of_le (hP : IsNestedPartition P δ) {m k : ℤ} (hmk : m ≤ k) (x : X) :
    hP.cell k x ⊆ hP.cell m x := by
  induction k, hmk using Int.leInduction with
  | base => exact le_rfl
  | succ k _ ih => exact (hP.cell_succ_subset k x).trans ih

theorem cell_eq_of_mem_of_le (hP : IsNestedPartition P δ) {m k : ℤ} (hmk : m ≤ k) {x y : X}
    (hy : y ∈ hP.cell k x) : hP.cell m y = hP.cell m x :=
  hP.cell_eq_of_mem (hP.cell_subset_of_le hmk x hy)

end IsNestedPartition

/-- **Whitney decomposition.** Let `(P k)` be a nested sequence of partitions of the metric space
`X` with cells of scale `k` of diameter at most `δ 2^{-k}`, let `Ω ⊆ X` be open with nonempty
complement and let `a > 0`. Then there is a family `𝒲` of pairwise disjoint cells with union `Ω`
such that every `W ∈ 𝒲` is a cell of some scale `k` with `a δ 2^{-k} ≤ dist(y, z)` for all
`y ∈ W`, `z ∉ Ω`, and `dist(y, z) < (2a + 2) δ 2^{-k}` for some `y ∈ W`, `z ∉ Ω`. -/
theorem exists_whitney_decomposition {P : ℤ → Set (Set X)} {δ : ℝ} (hP : IsNestedPartition P δ)
    (hδ : 0 < δ) {Ω : Set X} (hΩ : IsOpen Ω) (hΩc : Ωᶜ.Nonempty) {a : ℝ} (ha : 0 < a) :
    ∃ 𝒲 : Set (Set X), 𝒲.PairwiseDisjoint id ∧ ⋃₀ 𝒲 = Ω ∧
      ∀ W ∈ 𝒲, ∃ k : ℤ, W ∈ P k ∧
        (∀ y ∈ W, ∀ z ∉ Ω, a * (δ * (2 : ℝ) ^ (-k)) ≤ dist y z) ∧
        ∃ y ∈ W, ∃ z ∉ Ω, dist y z < (2 * a + 2) * (δ * (2 : ℝ) ^ (-k)) := by
  classical
  set s : ℤ → ℝ := fun k => δ * (2 : ℝ) ^ (-k) with hs
  have hs_pos : ∀ k, 0 < s k := fun k => mul_pos hδ (zpow_pos (by norm_num) _)
  have hs_succ : ∀ k, s (k - 1) = 2 * s k := by
    intro k
    simp only [hs]
    rw [show -(k - 1) = -k + 1 by ring, zpow_add_one₀ (by norm_num : (2 : ℝ) ≠ 0)]
    ring
  -- admissibility of the cell of scale `k` containing `x`
  let adm : X → ℤ → Prop := fun x k =>
    ∀ y ∈ hP.cell k x, ∀ z ∉ Ω, a * s k ≤ dist y z
  obtain ⟨z₀, hz₀⟩ := hΩc
  -- admissible scales exist
  have hadm_ex : ∀ x ∈ Ω, ∃ k, adm x k := by
    intro x hx
    obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.1 hΩ x hx
    obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one
      (div_pos hε (mul_pos (by linarith : (0 : ℝ) < a + 1) hδ))
      (by norm_num : (1 / 2 : ℝ) < 1)
    refine ⟨n, fun y hy z hz => ?_⟩
    have hsn : (a + 1) * s n < ε := by
      have : s n = δ * (1 / 2) ^ n := by simp [hs, zpow_neg, zpow_natCast]
      rw [this]
      rw [lt_div_iff₀ (mul_pos (by linarith) hδ)] at hn
      nlinarith
    have hxz : ε ≤ dist x z := by
      by_contra h
      exact hz (hball (mem_ball.2 (by rw [dist_comm]; exact not_le.1 h)))
    have hxy : dist x y ≤ s n := hP.dist_le n _ (hP.cell_mem n x) x (hP.mem_cell n x) y hy
    have := dist_triangle x y z
    nlinarith
  -- admissible scales are bounded below
  have hadm_bdd : ∀ x, ∃ b : ℤ, ∀ k, adm x k → b ≤ k := by
    intro x
    obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt (dist x z₀ / (a * δ)) (by norm_num : (1 : ℝ) < 2)
    refine ⟨-n, fun k hk => ?_⟩
    by_contra hlt
    rw [not_le] at hlt
    have h1 := hk x (hP.mem_cell k x) z₀ hz₀
    have h2 : (2 : ℝ) ^ n ≤ (2 : ℝ) ^ (-k) := by
      rw [← zpow_natCast]
      exact zpow_le_zpow_right₀ (by norm_num) (by omega)
    have h3 : dist x z₀ < a * δ * (2 : ℝ) ^ n := by
      rwa [div_lt_iff₀ (mul_pos ha hδ), mul_comm] at hn
    have : a * δ * (2 : ℝ) ^ n ≤ a * s k := by
      simp only [hs]
      rw [← mul_assoc]
      exact mul_le_mul_of_nonneg_left h2 (mul_pos ha hδ).le
    linarith
  -- admissibility is upward closed in the scale
  have hadm_succ : ∀ x k, adm x k → adm x (k + 1) := by
    intro x k hk y hy z hz
    have h := hk y (hP.cell_succ_subset k x hy) z hz
    have : s (k + 1) ≤ s k := by
      have := hs_succ (k + 1)
      simp only [add_sub_cancel_right] at this
      linarith [hs_pos (k + 1)]
    nlinarith
  have hadm_mono : ∀ x {m k}, m ≤ k → adm x m → adm x k := by
    intro x m k hmk hm
    induction k, hmk using Int.leInduction with
    | base => exact hm
    | succ k _ ih => exact hadm_succ x k ih
  -- the minimal admissible scale
  have hmin : ∀ x ∈ Ω, ∃ k, adm x k ∧ ∀ m, adm x m → k ≤ m := fun x hx =>
    Int.exists_least_of_bdd (hadm_bdd x) (hadm_ex x hx)
  let kstar : X → ℤ := fun x => if hx : x ∈ Ω then Classical.choose (hmin x hx) else 0
  have hkstar : ∀ x ∈ Ω, adm x (kstar x) ∧ ∀ m, adm x m → kstar x ≤ m := by
    intro x hx
    simp only [kstar, hx, ↓reduceDIte]
    exact Classical.choose_spec (hmin x hx)
  -- admissibility only depends on the cell
  have hadm_cell : ∀ {x y : X} {k m : ℤ}, m ≤ k → y ∈ hP.cell k x → (adm x m ↔ adm y m) := by
    intro x y k m hmk hy
    simp only [adm, hP.cell_eq_of_mem_of_le hmk hy]
  let Wc : X → Set X := fun x => hP.cell (kstar x) x
  refine ⟨Wc '' Ω, ?_, ?_, ?_⟩
  · -- disjointness
    rintro _ ⟨x, hx, rfl⟩ _ ⟨x', hx', rfl⟩ hne
    rw [Function.onFun, Set.disjoint_iff]
    rintro y ⟨hy, hy'⟩
    apply hne
    have hk := hkstar x hx
    have hk' := hkstar x' hx'
    have key : ∀ {x x' : X}, x ∈ Ω → x' ∈ Ω → kstar x ≤ kstar x' →
        y ∈ hP.cell (kstar x) x → y ∈ hP.cell (kstar x') x' → kstar x = kstar x' := by
      intro x x' hx hx' hle hy hy'
      apply le_antisymm hle
      apply (hkstar x' hx').2
      rw [hadm_cell hle hy', ← hadm_cell le_rfl hy]
      exact (hkstar x hx).1
    have hkk : kstar x = kstar x' := by
      rcases le_total (kstar x) (kstar x') with h | h
      · exact key hx hx' h hy hy'
      · exact (key hx' hx h hy' hy).symm
    simp only [Wc]
    rw [← hP.cell_eq_of_mem hy, ← hP.cell_eq_of_mem hy', hkk]
  · -- covering
    ext x
    constructor
    · rintro ⟨_, ⟨x', hx', rfl⟩, hxW⟩
      by_contra hxΩ
      have := (hkstar x' hx').1 x hxW x hxΩ
      rw [dist_self] at this
      exact absurd this (not_le.2 (mul_pos ha (hs_pos _)))
    · intro hx
      exact ⟨Wc x, ⟨x, hx, rfl⟩, hP.mem_cell _ x⟩
  · -- distance bounds
    rintro _ ⟨x, hx, rfl⟩
    refine ⟨kstar x, hP.cell_mem _ x, (hkstar x hx).1, ?_⟩
    have hnot : ¬ adm x (kstar x - 1) := by
      intro h
      have := (hkstar x hx).2 _ h
      omega
    simp only [adm, not_forall, not_le, exists_prop] at hnot
    obtain ⟨y, hy, z, hz, hyz⟩ := hnot
    refine ⟨x, hP.mem_cell _ x, z, hz, ?_⟩
    have hxy : dist x y ≤ s (kstar x - 1) :=
      hP.dist_le _ _ (hP.cell_mem _ x) x (hP.mem_cell _ x) y hy
    rw [hs_succ] at hxy hyz
    have := dist_triangle x y z
    simp only [hs] at hxy hyz ⊢
    nlinarith

end Auto
